// Generate a self-contained browser/Node boundary from wasm-pack's generated CJS.
// Only the byte source changes; all wasm-bindgen marshalling remains generated.
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const digest = (value) => createHash('sha256').update(value).digest('hex')
const sources = [
  'Cargo.toml',
  'Cargo.lock',
  'scripts/embed-wasm.mjs',
  ...(await readdir(path.join(root, 'src'), { recursive: true }))
    .filter((name) => name.endsWith('.rs'))
    .map((name) => `src/${name}`),
].sort()
const sourceDigest = digest(
  (
    await Promise.all(
      sources.map(async (name) => `${name}\n${await readFile(path.join(root, name), 'utf8')}`),
    )
  ).join('\n'),
)
const outputDir = path.join(root, 'browser')

if (process.argv.includes('--check')) {
  // Source/output fingerprints make the fast check work on a fresh clone before pkg/ exists.
  // Full rebuild parity is wasm-pack build followed by --verify-build.
  const manifest = JSON.parse(await readFile(path.join(outputDir, 'manifest.json'), 'utf8'))
  if (manifest.sourceDigest !== sourceDigest)
    throw new Error('Rust/browser source drift: rebuild WASM and run scripts/embed-wasm.mjs')
  for (const [name, expected] of Object.entries(manifest.outputs)) {
    if (digest(await readFile(path.join(outputDir, name))) !== expected)
      throw new Error(`Generated browser core changed: ${name}`)
  }
  process.exit(0)
}

const source = await readFile(path.join(root, 'pkg/loro_core.js'), 'utf8')
const bytes = await readFile(path.join(root, 'pkg/loro_core_bg.wasm'))
const marker = source.indexOf('const wasmPath = ')
if (marker < 0) throw new Error('wasm-bindgen Node loader changed; review the embedding generator')
const generated =
  '// GENERATED by scripts/embed-wasm.mjs. Do not edit.\n' +
  source.slice(0, marker) +
  `const encodedWasm = '${bytes.toString('base64')}';\n` +
  `const wasmBytes = Uint8Array.from(atob(encodedWasm), c => c.charCodeAt(0));\n` +
  `const wasmModule = new WebAssembly.Module(wasmBytes);\n` +
  `const wasm = new WebAssembly.Instance(wasmModule, __wbg_get_imports()).exports;\n` +
  `wasm.__wbindgen_start();\n`
const outputs = {
  'loro_core.js': generated,
  'loro_core.d.ts': await readFile(path.join(root, 'pkg/loro_core.d.ts'), 'utf8'),
}
await mkdir(outputDir, { recursive: true })
for (const [name, text] of Object.entries(outputs)) {
  const target = path.join(outputDir, name)
  if (process.argv.includes('--verify-build')) {
    if ((await readFile(target, 'utf8')) !== text)
      throw new Error(`Rebuilt browser core drift: ${name}`)
  } else await writeFile(target, text)
}
if (!process.argv.includes('--verify-build')) {
  await writeFile(
    path.join(outputDir, 'manifest.json'),
    JSON.stringify(
      {
        sourceDigest,
        outputs: Object.fromEntries(
          Object.entries(outputs).map(([name, text]) => [name, digest(text)]),
        ),
      },
      null,
      2,
    ) + '\n',
  )
}
