/**
 * Generate typed tokens for every target.
 *
 * out/ is COMMITTED and drift-checked in CI, because the native widget targets build
 * without the JS toolchain. Never hand-edit it — fix this generator. See ADR-0013.
 *
 * Run: pnpm tokens:build
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadTokens, type Tokens } from './tokens.js'

const here = dirname(fileURLToPath(import.meta.url))
const outDir = join(here, '..', 'out')

const BANNER = `// GENERATED by packages/design-tokens — DO NOT EDIT.
// Source: packages/design-tokens/tokens/*.json  ·  Run: pnpm tokens:build
// CI fails if this file drifts from the source. See ADR-0013.`

const camel = (s: string): string => s.replace(/[-.](\w)/g, (_, c: string) => c.toUpperCase())
const nativeIdentifier = (s: string): string => {
  const identifier = camel(s)
  return /^\d/.test(identifier) ? `r${identifier}` : identifier
}
const swiftIdentifier = (s: string): string => {
  const identifier = nativeIdentifier(s)
  return identifier === 'default' ? '`default`' : identifier
}

const capitalized = (s: string): string => {
  const identifier = nativeIdentifier(s)
  return identifier.charAt(0).toUpperCase() + identifier.slice(1)
}

function sheetCorners(value: string | number): [number, number, number, number] {
  if (typeof value !== 'string') throw new Error('radius.sheet must contain four pixel values')
  const corners = value.match(/\d+(?:\.\d+)?/g)?.map(Number)
  if (corners?.length !== 4) throw new Error('radius.sheet must contain four pixel values')
  return corners as [number, number, number, number]
}

// ─────────────────────────────────────────────────────────────────────────────
// TypeScript — the app
// ─────────────────────────────────────────────────────────────────────────────

function emitTs(t: Tokens): string {
  const obj = (o: Record<string, unknown>, indent = 2): string => {
    const pad = ' '.repeat(indent)
    return Object.entries(o)
      .map(([k, v]) => {
        const key = /^[a-zA-Z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)
        if (Array.isArray(v)) return `${pad}${key}: ${JSON.stringify(v)},`
        if (v !== null && typeof v === 'object') {
          return `${pad}${key}: {\n${obj(v as Record<string, unknown>, indent + 2)}\n${pad}},`
        }
        return `${pad}${key}: ${JSON.stringify(v)},`
      })
      .join('\n')
  }

  return `${BANNER}

export const surface = {
${obj(t.surface)}
} as const

export const ink = {
${obj(t.ink)}
} as const

export const line = {
${obj(t.line)}
} as const

export const semantic = {
${obj(t.semantic)}
} as const

export const scale = {
${obj(t.scale)}
} as const

export const onDark = {
${obj(t.onDark)}
} as const

export const gradient = {
${obj(t.gradient)}
} as const

/**
 * Accent themes. THE RULE THE NAMES ENCODE:
 *   accent       -> fills, borders, >=17px semibold text ON the accent
 *   accentInk    -> accent-coloured TEXT on light surfaces
 *   accentOnDark -> text and marks on dark cards
 *
 * \`accent\` fails AA for body text. Reach for \`accentInk\`.
 */
export const accents = {
${obj(t.accents)}
} as const

export const defaultAccent = ${JSON.stringify(t.defaultAccent)} as const

export const space = {
${obj(t.space)}
} as const

export const gutter = {
${obj(t.gutter)}
} as const

export const radius = {
${obj(t.radius)}
} as const

export const shadow = {
${obj(t.shadow)}
} as const

export const size = {
${obj(t.size as unknown as Record<string, unknown>)}
} as const

export const typography = {
${obj(t.typography as unknown as Record<string, unknown>)}
} as const

export const motion = {
${obj(t.motion as unknown as Record<string, unknown>)}
} as const

export type AccentName = keyof typeof accents
export type SurfaceName = keyof typeof surface
export type InkName = keyof typeof ink
export type SemanticName = keyof typeof semantic
export type WarmBand = keyof typeof scale.warming

/** Resolve an accent theme by name, falling back to the default. */
export function accentTheme(name: string = defaultAccent): (typeof accents)[AccentName] {
  return accents[name as AccentName] ?? accents[defaultAccent as AccentName]
}

export const tokens = {
  surface, ink, line, semantic, scale, onDark, gradient,
  accents, defaultAccent, space, gutter, radius, shadow, size, typography, motion,
} as const
`
}

// ─────────────────────────────────────────────────────────────────────────────
// Swift — the iOS widget target (built by Xcode, without the JS toolchain)
// ─────────────────────────────────────────────────────────────────────────────

export function emitSwift(t: Tokens): string {
  const swiftColor = (hex: string): string => {
    const h = hex.replace('#', '')
    const ch = (i: number): string => (parseInt(h.slice(i, i + 2), 16) / 255).toFixed(4)
    return `Color(red: ${ch(0)}, green: ${ch(2)}, blue: ${ch(4)})`
  }
  const group = (name: string, o: Record<string, string>): string =>
    `    public enum ${name} {\n` +
    Object.entries(o)
      .filter(([, v]) => v.startsWith('#'))
      .map(([k, v]) => `        public static let ${swiftIdentifier(k)} = ${swiftColor(v)}`)
      .join('\n') +
    '\n    }'
  const numberGroup = (name: string, o: Record<string, number>): string =>
    `    public enum ${name} {\n` +
    Object.entries(o)
      .map(([k, v]) => `        public static let ${swiftIdentifier(k)}: CGFloat = ${String(v)}`)
      .join('\n') +
    '\n    }'
  const typographyScale = Object.entries(t.typography.scale)
    .map(([name, token]) => {
      const fields = [
        `            public static let size: CGFloat = ${token.size}`,
        ...(token.sizeMax === undefined
          ? []
          : [`            public static let sizeMax: CGFloat = ${token.sizeMax}`]),
        `            public static let weight = ${token.weight}`,
        ...(token.tracking === undefined
          ? []
          : [`            public static let tracking = ${JSON.stringify(token.tracking)}`]),
        ...(token.lineHeight === undefined
          ? []
          : [`            public static let lineHeight: CGFloat = ${token.lineHeight}`]),
        ...(token.family === undefined
          ? []
          : [`            public static let family = ${JSON.stringify(token.family)}`]),
        ...(token.style === undefined
          ? []
          : [`            public static let style = ${JSON.stringify(token.style)}`]),
        ...(token.variant === undefined
          ? []
          : [`            public static let variant = ${JSON.stringify(token.variant)}`]),
        ...(token.transform === undefined
          ? []
          : [`            public static let transform = ${JSON.stringify(token.transform)}`]),
      ]
      return `        public enum ${capitalized(name)} {\n${fields.join('\n')}\n        }`
    })
    .join('\n')
  const motionSteps = (steps: Tokens['motion']['animation']): string =>
    Object.entries(steps)
      .map(([name, token]) => {
        const fields = [
          ...(token.duration === undefined
            ? []
            : [`            public static let durationMs = ${token.duration}`]),
          ...(token.stepMs === undefined
            ? []
            : [`            public static let stepMs = ${token.stepMs}`]),
          ...(token.totalMs === undefined
            ? []
            : [`            public static let totalMs = ${token.totalMs}`]),
          ...(token.range === undefined
            ? []
            : [`            public static let rangeMs = ${JSON.stringify(token.range)}`]),
          ...(token.easing === undefined
            ? []
            : [`            public static let easing = ${JSON.stringify(token.easing)}`]),
          ...(token.reducedMotion === undefined
            ? []
            : [
                `            public static let reducedMotion = ${JSON.stringify(token.reducedMotion)}`,
              ]),
          ...(token.properties === undefined
            ? []
            : [`            public static let properties = ${JSON.stringify(token.properties)}`]),
          ...(token.loop === undefined
            ? []
            : [`            public static let loop = ${String(token.loop)}`]),
          ...(token.stagger === undefined
            ? []
            : [`            public static let staggerMs = ${token.stagger}`]),
        ]
        return `        public enum ${capitalized(name)} {\n${fields.join('\n')}\n        }`
      })
      .join('\n')
  const pressFeedback = Object.entries(t.motion.press)
    .filter((entry): entry is [string, Exclude<(typeof entry)[1], string>] => {
      return typeof entry[1] !== 'string'
    })
    .map(([name, token]) => {
      const fields = [
        `            public static let scale: CGFloat = ${token.scale}`,
        `            public static let durationMs = ${token.duration}`,
        ...(token.backgroundShift === undefined
          ? []
          : [`            public static let backgroundShift = ${String(token.backgroundShift)}`]),
        ...(token.brightness === undefined
          ? []
          : [`            public static let brightness: CGFloat = ${token.brightness}`]),
        ...(token.opacity === undefined
          ? []
          : [`            public static let opacity: CGFloat = ${token.opacity}`]),
        ...(token.shadow === undefined
          ? []
          : [`            public static let shadow = ${String(token.shadow)}`]),
      ]
      return `        public enum ${capitalized(name)} {\n${fields.join('\n')}\n        }`
    })
    .join('\n')
  const [sheetTopLeft, sheetTopRight, sheetBottomRight, sheetBottomLeft] = sheetCorners(
    t.radius.sheet ?? '',
  )

  return `${BANNER.replace(/^/gm, '')}

import SwiftUI

public enum LoroTokens {
${group('Surface', t.surface)}

${group('Ink', t.ink)}

${group('Line', t.line)}

    public enum Accent {
${Object.entries(t.accents)
  .map(
    ([k, v]) =>
      `        public enum ${k.charAt(0).toUpperCase() + k.slice(1)} {\n` +
      `            public static let accent = ${swiftColor(v.accent)}\n` +
      `            public static let accentInk = ${swiftColor(v.accentInk)}\n` +
      `            public static let accentOnDark = ${swiftColor(v.accentOnDark)}\n` +
      `        }`,
  )
  .join('\n')}
    }

    public enum Radius {
${Object.entries(t.radius)
  .filter(([, v]) => typeof v === 'number')
  .map(([k, v]) => `        public static let ${swiftIdentifier(k)}: CGFloat = ${String(v)}`)
  .join('\n')}
    }

    public enum Space {
${Object.entries(t.space)
  .map(([k, v]) => `        public static let s${k.replace('.', '_')}: CGFloat = ${String(v)}`)
  .join('\n')}
    }

${numberGroup('Gutter', t.gutter)}

    public enum Size {
${numberGroup('EmojiTile', t.size.emojiTile).replace(/^/gm, '    ')}
${numberGroup('MicButton', t.size.micButton).replace(/^/gm, '    ')}
${numberGroup('ProgressBar', t.size.progressBar).replace(/^/gm, '    ')}
        public static let scoreRing: CGFloat = ${t.size.scoreRing}
        public static let chartHeight: CGFloat = ${t.size.chartHeight}
        public static let waveformBars = ${t.size.waveformBars}
        public static let contourPoints = ${t.size.contourPoints}
    }

    public enum Sheet {
        public static let topLeftRadius: CGFloat = ${sheetTopLeft}
        public static let topRightRadius: CGFloat = ${sheetTopRight}
        public static let bottomRightRadius: CGFloat = ${sheetBottomRight}
        public static let bottomLeftRadius: CGFloat = ${sheetBottomLeft}
        public static let handleWidth: CGFloat = ${t.size.sheetHandle.width}
        public static let handleHeight: CGFloat = ${t.size.sheetHandle.height}
    }

    public enum Typography {
        public enum Family {
${Object.entries(t.typography.family)
  .map(([name, token]) => {
    const style = token.style
      ? `\n                public static let style = ${JSON.stringify(token.style)}`
      : ''
    return `            public enum ${capitalized(name)} {
                public static let name = ${JSON.stringify(token.value)}
                public static let weights = ${JSON.stringify(token.weights)}${style}
            }`
  })
  .join('\n')}
        }
        public enum Scale {
${typographyScale}
        }
    }

    public enum Motion {
        public enum Easing {
${Object.entries(t.motion.easing)
  .map(
    ([name, token]) =>
      `            public static let ${swiftIdentifier(name)} = ${JSON.stringify(token.value)}`,
  )
  .join('\n')}
        }
        public enum Animation {
${motionSteps(t.motion.animation)}
        }
        public enum Transition {
${motionSteps(t.motion.transition)}
        }
        public enum Press {
${pressFeedback}
            public static let reducedMotion = ${JSON.stringify(t.motion.press.reducedMotion)}
        }
        public enum AudioTiming {
${Object.entries(t.motion.audioTiming)
  .map(([name, token]) => `            public static let ${swiftIdentifier(name)} = ${token.value}`)
  .join('\n')}
        }
    }

    public enum Touch {
        public static let minTapTarget: CGFloat = ${t.motion.touch.minTapTarget}
        public static let iconHitArea: CGFloat = ${t.motion.touch.iconHitArea}
    }
}
`
}

// ─────────────────────────────────────────────────────────────────────────────
// Kotlin — the Glance widget
// ─────────────────────────────────────────────────────────────────────────────

export function emitKotlin(t: Tokens): string {
  const argb = (hex: string): string => `Color(0xFF${hex.replace('#', '').toUpperCase()})`
  const group = (name: string, o: Record<string, string>): string =>
    `    object ${name} {\n` +
    Object.entries(o)
      .filter(([, v]) => v.startsWith('#'))
      .map(([k, v]) => `        val ${nativeIdentifier(k)} = ${argb(v)}`)
      .join('\n') +
    '\n    }'
  const dpGroup = (name: string, o: Record<string, number>): string =>
    `    object ${name} {\n` +
    Object.entries(o)
      .map(([k, v]) => `        val ${nativeIdentifier(k)}: Dp = ${String(v)}.dp`)
      .join('\n') +
    '\n    }'
  const typographyScale = Object.entries(t.typography.scale)
    .map(([name, token]) => {
      const fields = [
        `            val size: TextUnit = ${token.size}.sp`,
        ...(token.sizeMax === undefined
          ? []
          : [`            val sizeMax: TextUnit = ${token.sizeMax}.sp`]),
        `            const val weight = ${token.weight}`,
        ...(token.tracking === undefined
          ? []
          : [`            const val tracking = ${JSON.stringify(token.tracking)}`]),
        ...(token.lineHeight === undefined
          ? []
          : [`            const val lineHeight = ${token.lineHeight}`]),
        ...(token.family === undefined
          ? []
          : [`            const val family = ${JSON.stringify(token.family)}`]),
        ...(token.style === undefined
          ? []
          : [`            const val style = ${JSON.stringify(token.style)}`]),
        ...(token.variant === undefined
          ? []
          : [`            const val variant = ${JSON.stringify(token.variant)}`]),
        ...(token.transform === undefined
          ? []
          : [`            const val transform = ${JSON.stringify(token.transform)}`]),
      ]
      return `        object ${capitalized(name)} {\n${fields.join('\n')}\n        }`
    })
    .join('\n')
  const motionSteps = (steps: Tokens['motion']['animation']): string =>
    Object.entries(steps)
      .map(([name, token]) => {
        const fields = [
          ...(token.duration === undefined
            ? []
            : [`            const val durationMs = ${token.duration}`]),
          ...(token.stepMs === undefined ? [] : [`            const val stepMs = ${token.stepMs}`]),
          ...(token.totalMs === undefined
            ? []
            : [`            const val totalMs = ${token.totalMs}`]),
          ...(token.range === undefined
            ? []
            : [`            val rangeMs = listOf(${token.range.join(', ')})`]),
          ...(token.easing === undefined
            ? []
            : [`            const val easing = ${JSON.stringify(token.easing)}`]),
          ...(token.reducedMotion === undefined
            ? []
            : [`            const val reducedMotion = ${JSON.stringify(token.reducedMotion)}`]),
          ...(token.properties === undefined
            ? []
            : [
                `            val properties = listOf(${token.properties
                  .map((property) => JSON.stringify(property))
                  .join(', ')})`,
              ]),
          ...(token.loop === undefined
            ? []
            : [`            const val loop = ${String(token.loop)}`]),
          ...(token.stagger === undefined
            ? []
            : [`            const val staggerMs = ${token.stagger}`]),
        ]
        return `        object ${capitalized(name)} {\n${fields.join('\n')}\n        }`
      })
      .join('\n')
  const kotlinPressFeedback = Object.entries(t.motion.press)
    .filter((entry): entry is [string, Exclude<(typeof entry)[1], string>] => {
      return typeof entry[1] !== 'string'
    })
    .map(([name, token]) => {
      const fields = [
        `            const val scale = ${token.scale}`,
        `            const val durationMs = ${token.duration}`,
        ...(token.backgroundShift === undefined
          ? []
          : [`            const val backgroundShift = ${String(token.backgroundShift)}`]),
        ...(token.brightness === undefined
          ? []
          : [`            const val brightness = ${token.brightness}`]),
        ...(token.opacity === undefined
          ? []
          : [`            const val opacity = ${token.opacity}`]),
        ...(token.shadow === undefined
          ? []
          : [`            const val shadow = ${String(token.shadow)}`]),
      ]
      return `        object ${capitalized(name)} {\n${fields.join('\n')}\n        }`
    })
    .join('\n')
  const [sheetTopLeft, sheetTopRight, sheetBottomRight, sheetBottomLeft] = sheetCorners(
    t.radius.sheet ?? '',
  )

  return `${BANNER}

package app.loro.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.sp

object LoroTokens {
${group('Surface', t.surface)}

${group('Ink', t.ink)}

${group('Line', t.line)}

    object Accent {
${Object.entries(t.accents)
  .map(
    ([k, v]) =>
      `        object ${k.charAt(0).toUpperCase() + k.slice(1)} {\n` +
      `            val accent = ${argb(v.accent)}\n` +
      `            val accentInk = ${argb(v.accentInk)}\n` +
      `            val accentOnDark = ${argb(v.accentOnDark)}\n` +
      `        }`,
  )
  .join('\n')}
    }

    object Radius {
${Object.entries(t.radius)
  .filter(([, v]) => typeof v === 'number')
  .map(([k, v]) => `        val ${nativeIdentifier(k)}: Dp = ${String(v)}.dp`)
  .join('\n')}
    }

${dpGroup('Gutter', t.gutter)}

    object Size {
${dpGroup('EmojiTile', t.size.emojiTile).replace(/^/gm, '    ')}
${dpGroup('MicButton', t.size.micButton).replace(/^/gm, '    ')}
${dpGroup('ProgressBar', t.size.progressBar).replace(/^/gm, '    ')}
        val scoreRing: Dp = ${t.size.scoreRing}.dp
        val chartHeight: Dp = ${t.size.chartHeight}.dp
        const val waveformBars = ${t.size.waveformBars}
        const val contourPoints = ${t.size.contourPoints}
    }

    object Sheet {
        val topLeftRadius: Dp = ${sheetTopLeft}.dp
        val topRightRadius: Dp = ${sheetTopRight}.dp
        val bottomRightRadius: Dp = ${sheetBottomRight}.dp
        val bottomLeftRadius: Dp = ${sheetBottomLeft}.dp
        val handleWidth: Dp = ${t.size.sheetHandle.width}.dp
        val handleHeight: Dp = ${t.size.sheetHandle.height}.dp
    }

    object Typography {
        object Family {
${Object.entries(t.typography.family)
  .map(([name, token]) => {
    const style = token.style
      ? `\n                const val style = ${JSON.stringify(token.style)}`
      : ''
    return `            object ${capitalized(name)} {
                const val name = ${JSON.stringify(token.value)}
                val weights = listOf(${token.weights.join(', ')})${style}
            }`
  })
  .join('\n')}
        }
        object Scale {
${typographyScale}
        }
    }

    object Motion {
        object Easing {
${Object.entries(t.motion.easing)
  .map(
    ([name, token]) =>
      `            const val ${nativeIdentifier(name)} = ${JSON.stringify(token.value)}`,
  )
  .join('\n')}
        }
        object Animation {
${motionSteps(t.motion.animation)}
        }
        object Transition {
${motionSteps(t.motion.transition)}
        }
        object Press {
${kotlinPressFeedback}
            const val reducedMotion = ${JSON.stringify(t.motion.press.reducedMotion)}
        }
        object AudioTiming {
${Object.entries(t.motion.audioTiming)
  .map(([name, token]) => `            const val ${nativeIdentifier(name)} = ${token.value}`)
  .join('\n')}
        }
    }

    object Touch {
        val minTapTarget: Dp = ${t.motion.touch.minTapTarget}.dp
        val iconHitArea: Dp = ${t.motion.touch.iconHitArea}.dp
    }
}
`
}

// ─────────────────────────────────────────────────────────────────────────────

export function generateOutputs(t: Tokens = loadTokens()): Record<string, string> {
  return {
    'tokens.ts': emitTs(t),
    'Tokens.swift': emitSwift(t),
    'Tokens.kt': emitKotlin(t),
  }
}

function main(): void {
  const t = loadTokens()
  mkdirSync(outDir, { recursive: true })

  for (const [name, contents] of Object.entries(generateOutputs(t))) {
    writeFileSync(join(outDir, name), contents, 'utf8')
    console.log(`  out/${name}`)
  }

  const accentCount = Object.keys(t.accents).length
  console.log(
    `tokens: ${Object.keys(t.surface).length + Object.keys(t.ink).length + Object.keys(t.line).length} colours, ` +
      `${accentCount} accent themes, ${Object.keys(t.radius).length} radii, ${Object.keys(t.space).length} space steps`,
  )
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main()
