/**
 * Generate typed tokens for every target.
 *
 * out/ is COMMITTED and drift-checked in CI, because the native widget targets build
 * without the JS toolchain. Never hand-edit it — fix this generator. See ADR-0013.
 *
 * Run: pnpm tokens:build
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadTokens, type Tokens } from './tokens.js'

const here = dirname(fileURLToPath(import.meta.url))
const outDir = join(here, '..', 'out')

const BANNER = `// GENERATED by packages/design-tokens — DO NOT EDIT.
// Source: packages/design-tokens/tokens/*.json  ·  Run: pnpm tokens:build
// CI fails if this file drifts from the source. See ADR-0013.`

const camel = (s: string): string => s.replace(/[-.](\w)/g, (_, c: string) => c.toUpperCase())

// ─────────────────────────────────────────────────────────────────────────────
// TypeScript — the app
// ─────────────────────────────────────────────────────────────────────────────

function emitTs(t: Tokens): string {
  const obj = (o: Record<string, unknown>, indent = 2): string => {
    const pad = ' '.repeat(indent)
    return Object.entries(o)
      .map(([k, v]) => {
        const key = /^[a-zA-Z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)
        if (v !== null && typeof v === 'object') {
          return `${pad}${key}: {\n${obj(v as Record<string, unknown>, indent + 2)}\n${pad}},`
        }
        return `${pad}${key}: ${JSON.stringify(v)},`
      })
      .join('\n')
  }

  return `${BANNER}

export const surface = {
${obj(t.surface)}
} as const

export const ink = {
${obj(t.ink)}
} as const

export const line = {
${obj(t.line)}
} as const

export const semantic = {
${obj(t.semantic)}
} as const

export const scale = {
${obj(t.scale)}
} as const

export const onDark = {
${obj(t.onDark)}
} as const

export const gradient = {
${obj(t.gradient)}
} as const

/**
 * Accent themes. THE RULE THE NAMES ENCODE:
 *   accent       -> fills, borders, >=17px semibold text ON the accent
 *   accentInk    -> accent-coloured TEXT on light surfaces
 *   accentOnDark -> text and marks on dark cards
 *
 * \`accent\` fails AA for body text. Reach for \`accentInk\`.
 */
export const accents = {
${obj(t.accents)}
} as const

export const defaultAccent = ${JSON.stringify(t.defaultAccent)} as const

export const space = {
${obj(t.space)}
} as const

export const radius = {
${obj(t.radius)}
} as const

export const shadow = {
${obj(t.shadow)}
} as const

export type AccentName = keyof typeof accents
export type SurfaceName = keyof typeof surface
export type InkName = keyof typeof ink
export type SemanticName = keyof typeof semantic
export type WarmBand = keyof typeof scale.warming

/** Resolve an accent theme by name, falling back to the default. */
export function accentTheme(name: string = defaultAccent): (typeof accents)[AccentName] {
  return accents[name as AccentName] ?? accents[defaultAccent as AccentName]
}

export const tokens = {
  surface, ink, line, semantic, scale, onDark, gradient,
  accents, defaultAccent, space, radius, shadow,
} as const
`
}

// ─────────────────────────────────────────────────────────────────────────────
// Swift — the iOS widget target (built by Xcode, without the JS toolchain)
// ─────────────────────────────────────────────────────────────────────────────

function emitSwift(t: Tokens): string {
  const swiftColor = (hex: string): string => {
    const h = hex.replace('#', '')
    const ch = (i: number): string => (parseInt(h.slice(i, i + 2), 16) / 255).toFixed(4)
    return `Color(red: ${ch(0)}, green: ${ch(2)}, blue: ${ch(4)})`
  }
  const group = (name: string, o: Record<string, string>): string =>
    `    public enum ${name} {\n` +
    Object.entries(o)
      .filter(([, v]) => v.startsWith('#'))
      .map(([k, v]) => `        public static let ${camel(k)} = ${swiftColor(v)}`)
      .join('\n') +
    '\n    }'

  return `${BANNER.replace(/^/gm, '')}

import SwiftUI

public enum LoroTokens {
${group('Surface', t.surface)}

${group('Ink', t.ink)}

${group('Line', t.line)}

    public enum Accent {
${Object.entries(t.accents)
  .map(
    ([k, v]) =>
      `        public enum ${k.charAt(0).toUpperCase() + k.slice(1)} {\n` +
      `            public static let accent = ${swiftColor(v.accent)}\n` +
      `            public static let accentInk = ${swiftColor(v.accentInk)}\n` +
      `            public static let accentOnDark = ${swiftColor(v.accentOnDark)}\n` +
      `        }`,
  )
  .join('\n')}
    }

    public enum Radius {
${Object.entries(t.radius)
  .filter(([, v]) => typeof v === 'number')
  .map(([k, v]) => `        public static let ${camel(k)}: CGFloat = ${String(v)}`)
  .join('\n')}
    }

    public enum Space {
${Object.entries(t.space)
  .map(([k, v]) => `        public static let s${k.replace('.', '_')}: CGFloat = ${String(v)}`)
  .join('\n')}
    }
}
`
}

// ─────────────────────────────────────────────────────────────────────────────
// Kotlin — the Glance widget
// ─────────────────────────────────────────────────────────────────────────────

function emitKotlin(t: Tokens): string {
  const argb = (hex: string): string => `Color(0xFF${hex.replace('#', '').toUpperCase()})`
  const group = (name: string, o: Record<string, string>): string =>
    `    object ${name} {\n` +
    Object.entries(o)
      .filter(([, v]) => v.startsWith('#'))
      .map(([k, v]) => `        val ${camel(k)} = ${argb(v)}`)
      .join('\n') +
    '\n    }'

  return `${BANNER}

package app.loro.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object LoroTokens {
${group('Surface', t.surface)}

${group('Ink', t.ink)}

${group('Line', t.line)}

    object Accent {
${Object.entries(t.accents)
  .map(
    ([k, v]) =>
      `        object ${k.charAt(0).toUpperCase() + k.slice(1)} {\n` +
      `            val accent = ${argb(v.accent)}\n` +
      `            val accentInk = ${argb(v.accentInk)}\n` +
      `            val accentOnDark = ${argb(v.accentOnDark)}\n` +
      `        }`,
  )
  .join('\n')}
    }

    object Radius {
${Object.entries(t.radius)
  .filter(([, v]) => typeof v === 'number')
  .map(([k, v]) => `        val ${camel(k)}: Dp = ${String(v)}.dp`)
  .join('\n')}
    }
}
`
}

// ─────────────────────────────────────────────────────────────────────────────

function main(): void {
  const t = loadTokens()
  mkdirSync(outDir, { recursive: true })

  const files: [string, string][] = [
    ['tokens.ts', emitTs(t)],
    ['Tokens.swift', emitSwift(t)],
    ['Tokens.kt', emitKotlin(t)],
  ]

  for (const [name, contents] of files) {
    writeFileSync(join(outDir, name), contents, 'utf8')
    console.log(`  out/${name}`)
  }

  const accentCount = Object.keys(t.accents).length
  console.log(
    `tokens: ${Object.keys(t.surface).length + Object.keys(t.ink).length + Object.keys(t.line).length} colours, ` +
      `${accentCount} accent themes, ${Object.keys(t.radius).length} radii, ${Object.keys(t.space).length} space steps`,
  )
}

main()
