// Bulgarian UI copy. Awaiting native review (see content/meta.json).
import type { Copy, Plural } from './en';

export function makeBg(n: Plural): Copy {
  const phrases = (c: number) => n(c, { one: `${c} фраза`, other: `${c} фрази` });
  const sets = (c: number) => n(c, { one: `${c} набор`, other: `${c} набора` });
  return {
    locale: 'bg-BG',
    common: {
      close: 'Затвори',
      back: 'Назад',
      cancel: 'Отказ',
      charsLeft: (c) => n(c, { one: `Остава ${c} знак`, other: `Остават ${c} знака` }),
      save: 'Запази',
      undo: 'Отмени',
      play: 'Пусни',
      pause: 'Пауза',
      delete: 'Изтрий',
      moreOptions: 'Още',
      phrases,
      sets,
      points: (c) => n(c, { one: `${c} точка`, other: `${c} точки` }),
      level: (level) => level,
      grade: { missed: 'Не се сетих', hard: 'Трудно', easy: 'Лесно' },
      register: { formal: 'Учтиво', informal: 'Неофициално', neutral: 'Неутрално' },
      tag: {
        politeness: 'Учтивост',
        question: 'Въпроси',
        request: 'Молби',
        numbers: 'Числа',
        food: 'Храна и напитки',
        directions: 'Посоки',
        social: 'Общуване',
      },
      fullPlay: (time) => `${time} при 1×`,
    },
    nav: {
      main: 'Главно меню',
      home: 'Начало',
      explore: 'Разгледай',
      library: 'Библиотека',
      settings: (name) => (name ? `${name}: настройки` : 'Настройки'),
      learning: (language) => `Учите ${language}`,
      add: 'Добавете фраза или набор',
      addSheet: 'Добавяне',
      points: (c) => n(c, { one: `${c} точка`, other: `${c} точки` }),
      pointsShort: () => 'т.',
    },
    status: {
      new: 'Нова',
      listenedNotRated: 'Чута, без оценка',
      due: 'За преговор',
      learned: (pct) => `Научена · памет ${pct}%`,
      learning: (pct, when) => `Памет ${pct}% · отново ${when}`,
      set: { new: 'Нов', 'in-progress': 'Започнат', learned: 'Всичко научено' },
    },
    home: {
      firstRun: 'Чуйте фраза и я кажете сами, преди да я чуете отново.',
      learned: 'Научени',
      started: 'Започнати',
      today: (heard, rated) =>
        `Днес: ${n(heard, { one: `${heard} чута фраза`, other: `${heard} чути фрази` })} · ${n(rated, { one: `${rated} оценена`, other: `${rated} оценени` })}`,
      reviewTitle: 'Преговор',
      reviewBody: (due) => n(due, { one: `${due} фраза е за преговор`, other: `${due} фрази са за преговор` }),
      reviewCapped: (shown) => `В това занимание — ${shown}-те най-отдавна чакащи.`,
      playPhrases: (c) => `Пусни ${phrases(c)}`,
      duration: (time) => `${time} при 1×`,
      startTitle: 'Започнете оттук',
      continueTitle: 'Продължете',
      nextTitle: 'Следващ набор',
      next: (c, when) => `Следва: ${phrases(c)} ${when}`,
      nextAfter: (c, when) => `След тях: още ${phrases(c)} ${when}`,
      jumpBackIn: 'Върнете се',
      history: 'История',
      notStarted: 'Още незапочнати',
      demoTitle: 'Опитайте цикъла',
      demoBody: 'Една фраза: чуйте, кажете, чуйте.',
      demoButton: 'Пусни една фраза',
      courseDoneTitle: 'Всички фрази от курса са научени',
      courseDoneBody: 'Преговорите ще се върнат, когато им дойде времето. Дотогава добавете свои фрази или опитайте друг курс.',
      addOwn: 'Ваша фраза',
      otherCourse: 'Друг курс',
    },
    history: {
      title: 'История',
      empty: 'Все още нищо не е пускано.',
      mixed: 'Смесена опашка',
      run: (p, points) => `${phrases(p)} · +${points} т.`,
    },
    explore: {
      search: 'Фрази, бележки, теми',
      searchShort: 'Търсене',
      topics: 'Теми',
      levels: 'Нива',
      tags: 'Етикети',
      allSets: 'Всички набори',
      sets,
      phrases,
      noPhrases: (q) => `Няма фрази за „${q}“.`,
      noPhrasesFiltered: 'Няма фрази с тези филтри.',
      noSets: 'Няма подходящи набори.',
      addAsOwn: (q) => `Добавете „${q}“ като своя фраза`,
      removeFilter: (label) => `Махни филтъра: ${label}`,
      clearFilters: 'Изчисти филтрите',
      quickPlay: (title) => `Пусни „${title}“`,
      searchedSets: 'Набори',
    },
    set: {
      phrasesHeading: 'Фрази',
      summary: (total, learned, due) => `${phrases(total)} · научени ${learned}${due > 0 ? ` · за преговор ${due}` : ''}`,
      sort: { set: 'Както в набора', az: 'А–Я', due: 'Първо за преговор', weakest: 'Първо най-слабите' },
      sortTitle: 'Подреждане на фразите',
      playsIn: (order) => `Ред: ${order}`,
      playAll: (title) => `Пусни „${title}“`,
      pauseAll: (title) => `Пауза: „${title}“`,
      resume: (title) => `Продължи „${title}“`,
      pausedAt: (position, total) => `На пауза: ${position} от ${total}`,
      playDueNew: (c) => `Само нови и за преговор (${c})`,
      pauseDueNew: 'Пауза: нови и за преговор',
      shufflePlay: 'Разбъркано',
      like: 'Харесай набора',
      duration: (time) => `Целият набор: ${time} при 1×`,
      playNext: 'Пусни следващо',
      addToQueue: 'Добави в опашката',
      share: 'Сподели връзка',
      linkCopied: 'Връзката е копирана',
      copyUnavailable: 'Копирането не е достъпно тук',
      rename: 'Преименувай',
      delete: 'Изтрий набора',
      deleted: 'Наборът е изтрит',
      own: 'Ваш набор',
      ownEmpty: 'Добавяйте фрази от подробностите им (⋮) или от плейъра.',
      addPhrases: 'Добави фрази',
      addedNext: 'Ще е следваща',
      addedEnd: 'Добавено в опашката',
      notFound: 'Този набор не е достъпен.',
      otherCourse: (language) => `Този набор е от курса по ${language}.`,
      switchCourse: (language) => `Учи ${language}`,
    },
    phrase: {
      details: (text) => `Подробности: ${text}`,
      play: (text) => `Пусни: ${text}`,
      playNext: 'Пусни следваща',
      addToQueue: 'Добави в опашката',
      like: 'Харесай',
      liked: 'Харесана',
      likeLabel: 'Харесай фразата',
      addToSet: 'Добави в набор…',
      heard: (c) => `чута ${c}×`,
      notes: { mnemonic: 'Подсказка', grammar: 'Граматика', pronunciation: 'Звуци' },
      notesTitle: 'Бележки',
      notesInEnglish: 'Засега бележките са на английски.',
      words: 'Докоснете дума, за да видите значението ѝ.',
      glossHint: 'Показва значението',
      edit: 'Редактирай фразата',
      delete: 'Изтрий фразата',
      deleted: 'Фразата е изтрита',
      removeFromSet: 'Махни от набора',
      removedFromSet: 'Махната от набора',
      moveUp: 'Премести нагоре в набора',
      moveDown: 'Премести надолу в набора',
      yours: 'Ваша фраза',
      yoursShort: 'Ваша',
      sounds: 'Звучене:',
      notesByDevice: (language: string) => `Loro изведе тези бележки на това устройство от правилата за ${language} правопис и граматика. Никой носител на езика не ги е проверил.`,
      writeNotes: 'Поискай бележки от услугата',
      writingNotes: 'Бележките се пишат…',
      notesFailed: 'Услугата не отговори. Опитайте отново след малко.',
      notesByAi: 'Бележките ѝ са написани от ИИ. Никой носител на езика не ги е проверил.',
    },
    addToSet: {
      title: 'Добави в набор',
      newSet: 'Нов набор…',
      added: (title) => `Добавено в „${title}“`,
      already: (title) => `Вече е в „${title}“`,
      alreadyHere: 'Вече е в този набор',
      none: 'Все още нямате свои набори.',
    },
    pickPhrases: {
      search: 'Търсене на фрази',
      add: 'Добави',
      added: 'Добавена',
      done: 'Готово',
    },
    createSet: {
      title: 'Нов набор',
      renameTitle: 'Преименувай набора',
      name: 'Име',
      create: 'Създай',
      created: (title) => `Създаден е „${title}“`,
      taken: 'Набор с това име вече съществува.',
    },
    addPhrase: {
      title: 'Ваша фраза',
      target: (language) => `На ${language}`,
      native: (language) => `На ${language}`,
      hint: 'Звучи с гласа на устройството.',
      add: 'Добави фразата',
      added: 'Фразата е добавена',
      editTitle: 'Редактиране на фразата',
      edited: 'Фразата е обновена',
      duplicate: 'Вече е в курса:',
    },
    make: {
      title: 'Направи набор',
      into: (set) => `Добави към „${set}“`,
      entryDetail: 'Предложени фрази по тема, думи или текст',
      intro: 'Кажи за какво искаш да говориш. Loro предлага фрази: добави тези, които искаш, пропусни останалите.',
      modesLabel: 'Предложи по',
      modes: { topic: 'Тема', keywords: 'Думи', text: 'Текст' },
      field: { topic: 'Тема или ситуация', keywords: 'Няколко думи', text: 'Твоят текст' },
      placeholder: {
        topic: 'В аптеката',
        keywords: 'хотел, кърпа, закуска',
        text: 'Съобщение, меню, няколко реда, които искаш да кажеш',
      },
      hintTopic: 'Най-добре е място или момент.',
      hintKeywords: 'Раздели ги със запетаи.',
      hintText: (language) => `На всеки език: фразите ще са на ${language}.`,
      tryTopics: 'Или избери',
      suggest: 'Предложи фрази',
      writing: 'Фразите се пишат…',
      byAi: 'Предложенията се пишат от ИИ. Никой носител на езика не ги е проверил.',
      byDevice: 'Предложенията идват от фразите на това устройство.',
      fellBack: 'Услугата за фрази не отговори, затова тези са от това устройство.',
      none: (input) => `Още няма фрази за „${input}“.`,
      noneHint: 'Опитай с други думи или напиши фразата си.',
      writeOwn: 'Добави своя фраза',
      progress: (position, total) => `${position} от ${total}`,
      addedCount: (count) => n(count, { one: `${count} добавена`, other: `${count} добавени` }),
      cardLabel: (position, total) => `Предложение ${position} от ${total}`,
      source: {
        course: (set) => `От „${set}“`,
        mine: 'Твоя фраза',
        bank: 'Фрази на Loro',
        ai: 'Написано от ИИ · непроверено',
      },
      listen: (text) => `Чуй ${text}`,
      edit: 'Поправи',
      editLabel: (text) => `Поправи ${text}`,
      add: 'Добави',
      skip: 'Пропусни',
      addLabel: (text) => `Добави ${text}`,
      skipLabel: (text) => `Пропусни ${text}`,
      undoLabel: (text) => `Отмени: ${text}`,
      swipeHint: 'Плъзни надясно, за да добавиш, наляво, за да пропуснеш.',
      keysHint: 'Клавиши: → добави, ← пропусни.',
      announceAdded: (text) => `Добавена: ${text}`,
      announceSkipped: (text) => `Пропусната: ${text}`,
      done: 'Готово',
      endTitle: (count) => (count === 1 ? 'Това е единственото предложение' : `Това са всички ${count} предложения`),
      endAdded: (count) => (count === 0 ? 'Пропусна всички.' : n(count, { one: `Добави ${count} фраза.`, other: `Добави ${count} фрази.` })),
      more: 'Още предложения',
      noMore: 'Няма повече предложения за това.',
      another: 'Опитай с нещо друго',
      review: (count) => n(count, { one: `Запази ${count} фраза`, other: `Запази ${count} фрази` }),
      saveTitle: 'Запази набора',
      keptHeading: (count) => n(count, { one: `${count} фраза за запазване`, other: `${count} фрази за запазване` }),
      remove: (text) => `Махни ${text}`,
      addInto: (count, set) => n(count, { one: `Добави ${count} фраза към „${set}“`, other: `Добави ${count} фрази към „${set}“` }),
      addedInto: (count, set) => n(count, { one: `${count} фраза е добавена към „${set}“`, other: `${count} фрази са добавени към „${set}“` }),
      backToDeck: 'Обратно към предложенията',
      unsaved: (count) => n(count, { one: `${count} добавена фраза не е запазена`, other: `${count} добавени фрази не са запазени` }),
      reopen: 'Отвори отново',
      fromExplore: (query) => `Предложи фрази за „${query}“`,
      fromSet: 'Предложи фрази',
      originAi: 'Написано от ИИ. Никой носител на езика не го е проверил.',
      originBank: 'От фразите на Loro.',
      defaultTitleText: 'От моя текст',
    },
    player: {
      dialog: 'Сега звучи',
      close: 'Затвори плейъра',
      openQueue: 'Отвори опашката',
      summary: 'Обобщение на заниманието',
      position: (i, total) => `${i} от ${total}`,
      positionInQueue: (i, total) => `${i} от ${total} в опашката`,
      hidden: (language) => `Текстът на ${language} е скрит, докато не го чуете`,
      steps: 'Стъпки',
      yourTurn: 'Ваш ред',
      instruction: {
        native: (language) => `Слушайте на ${language}`,
        pause: (language) => `Ваш ред — кажете го на глас на ${language}`,
        target: (language) => `Чуйте го на ${language}`,
        rate: 'Оценете или изчакайте',
      },
      paused: 'Пауза',
      coach: 'Кажете я сега, преди да я чуете. Нищо не се записва — после оценявате как мина.',
      repetition: (r, total) => `Повторение ${r} от ${total}`,
      howDidItGo: 'Сетихте ли се?',
      rateAfterTurn: 'Оценете, след като я кажете',
      nextIn: (interval) => `след ${interval}`,
      rated: (grade, when) => `Оценка „${grade}“ — отново ${when}`,
      requeued: '· пак в опашката',
      undoFor: (time) => `Отмени · ${time}`,
      undoLabel: (time) => `Отмени оценката (остават ${time})`,
      previous: 'Предишна фраза',
      next: 'Следваща фраза',
      repeats: {
        auto: 'Повторения: автоматично (3 за нови или несигурни, 1 за усвоени)',
        one: 'Повторения: 1',
        three: 'Повторения: 3',
      },
      playMode: {
        repeat: 'Накрая: пусни опашката отново',
        continue: 'Накрая: продължи със следващите фрази',
      },
      captions: { reps: 'повт.', again: 'Отново', continue: 'Продължи', auto: 'Авто' },
      repeatsToast: {
        auto: 'Всяка фраза звучи 3× докато е нова, 1× щом я запомните',
        one: 'Всяка фраза звучи веднъж',
        three: 'Всяка фраза звучи 3 пъти',
      },
      playModeToast: {
        repeat: 'Накрая опашката започва отначало',
        continue: 'Накрая следват нови фрази',
      },
      speed: 'Скорост',
      speedIs: (speed) => `Скорост: ${speed}×`,
      keys: 'Клавиши: интервал — пусни или пауза · ← → предишна, следваща · 1 2 3 — оценка',
      audioError: (language) =>
        `На устройството няма глас за ${language}, затова фразата не звучи. Добавете го в настройките за реч на системата и натиснете „Пусни“.`,
      showText: (language) => `Покажи текста на ${language}`,
      end: {
        reviewTitle: 'Преговорът е готов',
        listTitle: 'Всичко е изслушано',
        playedThrough: 'Изслушано докрай',
        rated: (count) => `Оценени: ${count}`,
        nextReview: (when) => `Следващ преговор ${when}`,
        nothingDue: 'Още нищо не е за преговор',
        continueSet: (title) => `Продължи с „${title}“`,
        playAgain: 'Пусни отново',
        demoTitle: 'Това е цикълът',
        demoBody: 'Чуйте, кажете на глас, чуйте, оценете. Готови ли сте за цял набор?',
        startSet: (title) => `Започни „${title}“`,
        notNow: 'Не сега',
      },
      miniRate: 'Докоснете, за да оцените',
      noVoice: 'Няма глас за този език',
      audioSilent: 'Речта спря, преди фразата да прозвучи. Натиснете „Пусни“, за да опитате отново.',
      silent: 'Речта спря — натиснете „Пусни“',
      voice: (name) => `Глас: ${name}`,
      changeVoice: (name) => `Глас: ${name}. Смени гласа`,
    },
    toast: {
      updateReady: 'Има нова версия на Loro',
      reload: 'Презареди',
      dismiss: 'Затвори съобщението',
      learned: (points) => `Научена · +${points}`,
      passComplete: 'Опашката е изслушана докрай',
      nextSet: (title) => `Следва: ${title}`,
      removed: 'Махнато от опашката',
      cleared: 'Опашката е изчистена',
      saved: (title) => `Запазено като „${title}“`,
      storageFull: 'Паметта на устройството за Loro е пълна, затова новият напредък не се запазва.',
      storageUnavailable: 'Този браузър не позволява на Loro да запазва напредъка на устройството.',
      outdated: 'В друг раздел е отворена по-нова версия на Loro. Презаредете, за да се запазва напредъкът и тук.',
    },
    queue: {
      title: 'Опашка',
      back: 'Назад към плейъра',
      left: (c) => `Остават ${c}`,
      nowPlaying: 'Сега звучи',
      upNext: (c) => `Следват · ${c}`,
      nothing: 'След тази фраза няма нищо.',
      hint: 'Плъзнете надясно, за да пуснете сега, наляво — за да махнете. Хванете дръжката, за да пренаредите, или я докоснете за още.',
      handleHint: 'Enter — още действия; стрелки нагоре и надолу — премести, Delete — махни.',
      moveUp: 'Премести нагоре',
      moveDown: 'Премести надолу',
      removeFromQueue: 'Махни от опашката',
      moved: (position, total) => `Преместено на място ${position} от ${total}`,
      playNow: (text) => `Пусни сега: ${text}`,
      move: (text) => `Премести: ${text}`,
      swipePlay: 'Пусни',
      swipeRemove: 'Махни',
      previously: 'Вече звучали',
      again: 'Отново',
      justNow: 'току-що',
      playNext: (text) => `Пусни следваща: ${text}`,
      clear: 'Изчисти опашката',
      saveAsSet: 'Запази като набор',
      shuffle: 'Разбъркай следващите',
      defaultSetName: 'Моята опашка',
    },
    library: {
      learned: 'Научени',
      learnedNote: (days, recalls) => `Помни се ${days}+ дни, след ${recalls}+ сещания`,
      recall: 'Памет сега',
      recallNote: (rated) => n(rated, { one: `Средно за ${rated} оценена фраза`, other: `Средно за ${rated} оценени фрази` }),
      recallNone: 'Първо оценете фраза',
      started: 'Започнати',
      startedNote: 'Чути или оценени поне веднъж',
      phrasesSegment: 'Фрази',
      setsSegment: 'Набори',
      filters: {
        liked: 'Харесани',
        mine: 'Мои',
        due: 'За преговор',
        learning: 'Учат се',
        missed: 'Скоро несетени',
        learned: 'Научени',
        ownSets: 'Мои набори',
        likedSets: 'Харесани набори',
      },
      empty: {
        liked: 'Докоснете сърцето на фраза, за да я пазите тук.',
        mine: 'Добавете своя фраза — ще звучи като всяка друга.',
        due: 'В момента няма нищо за преговор.',
        learning: 'Тук са фразите, които сте чули или оценили, но още не сте научили.',
        missed: 'Тук са фразите с оценка „Не се сетих“ от последната седмица.',
        learned: (days, recalls) =>
          `Една фраза е научена, когато се очаква да се помни ${days} дни или повече, след поне ${recalls} успешни сещания.`,
        ownSets: 'Създайте набор, за да групирате фрази по свой начин.',
        likedSets: 'Докоснете сърцето на набор, за да го пазите тук.',
      },
      playAll: (c) => `Пусни всички (${c})`,
      addPhrase: 'Ваша фраза',
      newSet: 'Нов набор',
      recallChart: 'Очаквана памет сега',
      recallBucket: (from, to) => `${from}–${to}%`,
      recallBelow: (to) => `под ${to}%`,
      recallChartEmpty: 'Оценете фраза, за да видите това.',
      bucketCount: (label, c) => `${label}: ${phrases(c)}`,
      weeklyChart: 'Научени по седмици',
      weekOf: (date, c) => `Седмицата от ${date}: научени ${c}`,
      progress: 'Напредък',
    },
    settings: {
      title: 'Настройки',
      switched: (language, queueCleared) => `Курс: ${language}${queueCleared ? '. Опашката е изчистена' : ''}`,
      profile: 'Профил',
      name: 'Име',
      native: 'Говоря',
      course: 'Уча',
      courseNote: 'Напредъкът се пази за всяка двойка езици. Щом превключите обратно, той се връща.',
      voices: 'Гласове',
      voiceAuto: (name) => `Автоматично (${name})`,
      accessibility: 'Екранен четец',
      announceEveryStep: 'Обявявай всяка стъпка',
      announceHint: 'Изключено: обявяват се само „Ваш ред“ и отговорът.',
      listening: 'Слушане',
      pauseLength: 'Време да го кажете',
      pause: { standard: 'Стандартно', longer: 'По-дълго' },
      pauseHint: '„По-дълго“ дава около два пъти дължината на фразата.',
    },
    onboarding: {
      step: (i, total) => `Стъпка ${i} от ${total}`,
      welcome: 'Учете език фраза по фраза: чуйте, кажете, чуйте.',
      name: 'Как да ви наричаме?',
      namePlaceholder: 'Вашето име',
      native: 'Какъв език говорите?',
      course: 'Какъв език учите?',
      voices: 'Проверка на гласовете',
      voicesChecking: 'Търсим гласове на това устройство…',
      voiceOk: (language, name) => `${language}: ${name}`,
      voiceMissing: (language) => `${language}: няма глас на това устройство`,
      voiceHint: 'Добавете липсващия глас в настройките за реч на системата. Може да продължите, но тези фрази няма да звучат дотогава.',
      test: (language) => `Изпробвай: ${language}`,
      testShort: 'Изпробвай',
      loop: 'Как работи',
      loopSteps: (native, target) => [
        `Чуйте фразата на ${native}.`,
        `Кажете я на глас на ${target}, докато е тихо.`,
        `Чуйте я на ${target}.`,
        'Оценете как мина: „Не се сетих“, „Трудно“ или „Лесно“. Може да смените оценката в рамките на пет минути.',
      ],
      next: 'Напред',
      start: 'Започни с една фраза',
      skip: 'Започни без пример',
    },
    summary: {
      title: 'Това занимание',
      phrases: 'Фрази',
      repetitions: 'Повторения',
      ratings: 'Оценки',
      pending: (c) => `още могат да се сменят: ${c}; точките и следващият преговор се броят след пет минути`,
      points: 'Спечелени точки',
      passes: 'Пъти през опашката',
      nextDue: 'Следващ преговор',
      nothingDue: 'Все още нищо не е насрочено',
      none: 'В тази сесия още нищо не е пускано.',
    },
    connection: {
      loading: 'Зареждаме курса ви…',
      offlineTitle: 'Loro не може да се свърже със сървъра',
      offlineBody: 'Курсът се изтегля веднъж и после работи без връзка. Проверете връзката и опитайте отново.',
      retry: 'Опитай отново',
    },
    account: {
      title: 'Профил',
      signIn: 'Вход',
      signInTitle: 'Вход в Loro',
      signInBody: 'Създавайте набори от фрази, песни и корици с ИИ, пазете ги в профила си и ги споделяйте. Напредъкът на това устройство остава какъвто е.',
      email: 'Имейл',
      emailPlaceholder: 'vie@primer.bg',
      sendCode: 'Изпрати ми код',
      sending: 'Изпращаме…',
      codeTitle: 'Проверете имейла си',
      codeBody: (email) => `Изпратихме шестцифрен код на ${email}. Важи 10 минути.`,
      code: 'Шестцифрен код',
      verify: 'Влез',
      verifying: 'Влизаме…',
      resend: 'Изпрати нов код',
      changeEmail: 'Друг имейл',
      signedInAs: (email) => `Влезли сте като ${email}`,
      signOut: 'Изход',
      deleteData: 'Изтрий данните ми в Loro',
      deleteDataConfirm: 'Да изтрием ли наборите, албумите, песните, кориците и напредъка в профила ви? Тези, с които сте споделили, също ги губят. Напредъкът на това устройство остава. Това не може да се отмени.',
      deletedData: 'Данните ви в Loro са изтрити.',
      deleteAccount: 'Изтрий акаунта ми',
      deleteAccountConfirm: 'Да изтрием ли акаунта ви в Loro с всичко в него: наборите, албумите, песните, кориците и напредъка, пазен в него? Всеки, с когото сте споделили, също ги губи. Напредъкът на това устройство остава. Това не може да се отмени.',
      deleteAccountYes: 'Изтрий акаунта',
      deletedAccount: 'Акаунтът ви е изтрит.',
      synced: 'Напредъкът ви се пази в профила и ви следва на други устройства.',
      syncFailed: 'Напредъкът ви не можа да се запази в профила точно сега. Той е на сигурно на това устройство и ще се запази, когато връзката се върне.',
      signedOut: 'Излязохте. Напредъкът на това устройство е запазен.',
      welcome: 'Влязохте',
      displayName: 'Име върху споделеното',
      displayNameHint: 'Показва се като „от …“ на наборите и албумите, които направите публични. Оставете празно за „от учащ“.',
      displayNameSaved: 'Името е запазено',
      notNow: 'Не сега',
      google: 'Продължи с Google',
      apple: 'Продължи с Apple',
      needed: 'Влезте, за да създавате набори, песни и корици с ИИ и да ги споделяте.',
      errors: {
        badEmail: 'Това не прилича на имейл адрес.',
        badCode: 'Кодът не е верен или е изтекъл.',
        tooMany: 'Твърде много опити. Изчакайте няколко минути и опитайте отново.',
        unavailable: 'Вход с имейл не е настроен на този сървър.',
        providerUnavailable: (provider: string) => `Вход с ${provider} не е настроен за този адрес на Loro.`,
        offline: 'Loro не може да се свърже със сървъра. Проверете връзката.',
        generic: 'Нещо се обърка. Опитайте отново.',
        full: 'Профилът ви е достигнал лимита за тези. Изтрийте някой, за да направите място.',
        invalid: 'Не можа да се запази: нещо е твърде дълго или липсва.',
      },
      today: 'Днешният лимит',
      usage: {
        phrases: (left, limit) => `Набори фрази: остават ${left} от ${limit}`,
        cover: (left, limit) => `Корици: остават ${left} от ${limit}`,
        song: (left, limit) => `Песни: остават ${left} от ${limit}`,
      },
      kept: (sets, albums) => `${n(sets, { one: `${sets} набор`, other: `${sets} набора` })} и ${n(albums, { one: `${albums} албум`, other: `${albums} албума` })} в профила ви`,
      resets: (time) => `Подновява се в ${time}`,
      spent: (time) => `Днешният лимит е изчерпан. Подновява се в ${time}.`,
      writers: 'Кой го създава на този сървър',
      writer: {
        claude: 'Claude (ИИ)',
        bank: 'Банката фрази на Loro (няма настроен ИИ)',
        pattern: 'Рисувани шарки (няма настроен ИИ)',
        phrases: 'Вашите фрази като текст (няма настроен ИИ)',
        elevenlabs: 'Изпято от ElevenLabs Music',
        demo: 'Демо звук (няма настроена музика)',
      },
      writerKind: { phrases: 'Фрази', cover: 'Корици', lyrics: 'Текст', music: 'Звук' },
    },
    tabs: {
      home: 'Начало',
      phrases: 'Фрази',
      music: 'Музика',
      create: 'Създай',
      library: 'Библиотека',
    },
    share: {
      hidden: 'Хора го докладваха, затова вече не се показва в Общността. Всеки с връзката още може да го отвори.',
      visibility: 'Кой може да го вижда',
      private: 'Само вие',
      privateDetail: 'В профила ви, на вашите устройства',
      link: 'Всеки с връзката',
      linkDetail: 'Не е в списъците; връзката го отваря',
      public: 'Всички',
      publicDetail: 'В Общността за вашия курс',
      share: 'Сподели',
      shareMessage: (title, url) => `${title} в Loro: ${url}`,
      copied: 'Връзката е копирана',
      makeShareable: 'Само вие го виждате. Изберете кой може, преди да споделите.',
      by: (name) => `от ${name}`,
      byLearner: 'от учащ',
      yours: 'Ваше',
      save: 'Запази в библиотеката',
      saved: 'В библиотеката ви',
      unsave: 'Премахни от библиотеката',
      savedToast: 'Запазено в библиотеката ви',
      unsavedToast: 'Премахнато от библиотеката ви',
      delete: 'Изтрий',
      deleteSetConfirm: (title) => `Да изтрием ли „${title}“ от профила ви? Тези, с които сте го споделили, също го губят. Напредъкът ви по фразите му се запазва.`,
      deleteAlbumConfirm: (title) => `Да изтрием ли албума „${title}“ и песните му?`,
      deleted: 'Изтрито',
      cover: 'Нова корица',
      coverMaking: 'Рисуваме корица…',
      coverBy: { claude: 'Корица от Claude', pattern: 'Рисувана шарка' },
      changed: 'Запазено',
      notFound: 'Тази връзка не отваря нищо. Може да е станала лична или да е изтрита.',
      opening: 'Отваряме…',
      report: 'Сигнал',
      reported: 'Сигналът е изпратен. Благодарим.',
      reason: { offensive: 'Обидно или нараняващо', wrong: 'Грешен език или грешки', spam: 'Спам или реклама', other: 'Нещо друго' },
    },
    community: {
      title: 'Общност',
      sets: 'Споделени набори',
      albums: 'Споделени албуми',
      emptySets: 'Още никой не е споделил набор в този курс. Създайте един и изберете „Всички“.',
      emptyAlbums: 'Още никой не е споделил албум в този курс.',
      search: 'Търсене в споделените набори',
      searchAlbums: 'Търсене в споделените албуми',
      moreBy: (name: string) => `Още от ${name}`,
      moreByLearner: 'Още от този учащ',
      sortNew: 'Най-нови',
      sortPopular: 'Най-запазвани',
      sortLabel: 'Подредба',
      savedBy: (n: number) => (n === 1 ? 'запазен от 1' : `запазен от ${n}`),
      noSetsFound: (q: string) => `Няма споделен набор, който да съвпада с „${q}“.`,
      noAlbumsFound: (q: string) => `Няма споделен албум, който да съвпада с „${q}“.`,
      offline: 'Общността иска връзка.',
    },
    phrasesTab: {
      title: 'Фрази',
      course: 'Курсът на Loro',
      yourSets: 'Вашите набори',
      savedSets: 'Запазени набори',
      makeSet: 'Създай набор с ИИ',
      signInToMake: 'Влезте, за да създавате набори с ИИ',
    },
    music: {
      setSongs: 'Песни от този набор',
      title: 'Музика',
      loro: 'От Loro',
      yours: 'Вашите албуми',
      saved: 'Запазени албуми',
      songs: (c) => n(c, { one: `${c} песен`, other: `${c} песни` }),
      empty: 'Още няма албуми в този курс.',
      noSongs: 'Още няма песни тук.',
      loroAlbum: 'Всеки набор на Loro от този курс, изпят.',
      makeSong: 'Създай песен',
      renameAlbum: 'Преименувай албума',
      album: 'Албум',
      playAlbum: 'Пусни албума',
      playSong: (title) => `Пусни ${title}`,
      demoSound: 'Демо звук',
      spokenDemo: 'Изговорено демо',
      spokenNote: 'Редовете се изговарят с гласа на Loro върху инструментал, създаден от сървъра, и светват, докато звучат. Песните се пеят, когато е настроена музикална услуга.',
      demoNote: 'Сървърът създаде тази инструментална версия; текстът светва, докато свири. Песните се пеят, когато е настроена музикална услуга.',
      sung: 'Изпята',
      lyrics: 'Текст',
      lyricsBy: { claude: 'Текст от Claude', phrases: 'Текст: фразите на набора' },
      meanings: 'Значения',
      showMeanings: 'Покажи значенията',
      hideMeanings: 'Скрий значенията',
      section: { verse: 'Куплет', chorus: 'Припев', bridge: 'Бридж' },
      rendering: 'Създаваме песента…',
      renderingNote: 'Отнема малко време. Можете да излезете от този екран; песента продължава да се създава.',
      failed: 'Тази песен не можа да бъде създадена.',
      retrySong: (title: string) => `Опитай „${title}“ отново`,
      removeSong: 'Премахни песента',
      removeSongConfirm: (title: string) => `Да премахнем ли „${title}“ от албума?`,
      nowPlaying: 'Сега звучи',
      previous: 'Предишна песен',
      next: 'Следваща песен',
      openSet: 'Отвори набора',
      fromSet: (title) => `От набора „${title}“`,
      loadFailed: 'Албумът не можа да се зареди.',
      style: {
        modern_pop: 'Поп',
        acoustic_folk: 'Фолк',
        gentle_ballad: 'Балада',
        upbeat_kids: 'За пеене',
      },
    },
    create: {
      title: 'Създай',
      intro: 'Създавайте свои набори от фрази, песни и корици с ИИ. Създаденото е ваше: пазете го лично, споделете връзка или го публикувайте за всички.',
      phrasesTitle: 'Набор от фрази',
      phrasesBody: 'Назовете тема или поставете текст. ИИ пише фрази с бележките им; запазете тези, които искате.',
      songTitle: 'Песен от набор',
      songBody: 'Вашите фрази, изпети. Чуйте ги в песен и следете текста.',
      coverTitle: 'Корици',
      coverBody: 'Всеки ваш набор и албум може да получи своя рисувана корица.',
      coverNothing: 'Първо създайте набор или песен, после им нарисувайте корица тук.',
      left: (c) => n(c, { one: `Остава ${c} за днес`, other: `Остават ${c} за днес` }),
      none: 'Не остават за днес',
      pickSet: 'Кой набор?',
      pickSetEmpty: 'Още няма набори в този курс.',
      pickStyle: 'Стил',
      pickAlbum: 'Албум',
      newAlbum: 'Нов албум',
      songTitleLabel: 'Заглавие на песента',
      makeSong: 'Създай песента',
      songStarted: 'Песента се създава',
      saveToAccount: 'Запази в профила си',
      savedToAccount: 'Запазено в профила ви',
      setTitle: 'Заглавие',
      setDescription: 'За какво е (по желание)',
      withCover: 'Нарисувай корица',
      signedOutSave: 'Запазено на това устройство. Влезте, за да го пазите в профила си и да го споделяте.',
      from: { claude: 'Написано от Claude', bank: 'От банката фрази на Loro' },
      bankOnly: 'На този сървър няма настроен ИИ, затова тези са от банката фрази на Loro.',
      noMatch: 'Банката фрази няма нищо по темата. Опитайте някоя от тези:',
    },
    error: {
      title: 'Нещо се обърка',
      body: 'Презареждането обикновено помага и напредъкът се запазва. Ако се повтаря, запазеният напредък може да не пасва на тази версия: копирайте го, ако искате да го пазите, и нулирайте, за да започнете отначало на това устройство.',
      reload: 'Презареди',
      part: 'Тази част от екрана не можа да се покаже. Напредъкът ви е запазен.',
      copy: 'Копирай напредъка като JSON',
      copied: 'Копирано',
      reset: 'Нулирай напредъка',
    },
  };
}
