// Czech UI copy. Awaiting native review (see content/meta.json).
import type { Copy, Plural } from './en';

export function makeCs(n: Plural): Copy {
  // "španělština" → "španělsky", "angličtina" → "anglicky": the adverb a sentence needs
  // ("řekněte nahlas španělsky"). Other names fall back to a phrase that needs no declension.
  const adverb = (language: string) =>
    language.endsWith('ština') ? `${language.slice(0, -5)}sky` : language.endsWith('čtina') ? `${language.slice(0, -5)}cky` : `v jazyce: ${language}`;
  // Czech counts: 1 → one, 2–4 → few, 0 and 5+ → other (`many` is for fractions and falls back to `other`).
  const phrases = (c: number) => n(c, { one: `${c} fráze`, few: `${c} fráze`, other: `${c} frází` });
  const sets = (c: number) => n(c, { one: `${c} sada`, few: `${c} sady`, other: `${c} sad` });
  const points = (c: number) => n(c, { one: `${c} bod`, few: `${c} body`, other: `${c} bodů` });
  const days = (c: number) => n(c, { one: `${c} den`, few: `${c} dny`, other: `${c} dní` });
  const songs = (c: number) => n(c, { one: `${c} píseň`, few: `${c} písně`, other: `${c} písní` });
  const albums = (c: number) => n(c, { one: `${c} album`, few: `${c} alba`, other: `${c} alb` });
  return {
    locale: 'cs-CZ',
    common: {
      close: 'Zavřít',
      back: 'Zpět',
      cancel: 'Zrušit',
      charsLeft: (c) => n(c, { one: `Zbývá ${c} znak`, few: `Zbývají ${c} znaky`, other: `Zbývá ${c} znaků` }),
      save: 'Uložit',
      undo: 'Vrátit zpět',
      play: 'Poslouchat',
      pause: 'Pauza',
      delete: 'Smazat',
      moreOptions: 'Další možnosti',
      phrases,
      sets,
      points,
      level: (level) => level,
      grade: { missed: 'Nepamatuji si', hard: 'Těžké', easy: 'Snadné' },
      register: { formal: 'Zdvořile', informal: 'Neformálně', neutral: 'Neutrálně' },
      tag: {
        politeness: 'Zdvořilost',
        question: 'Otázky',
        request: 'Prosby',
        numbers: 'Čísla',
        food: 'Jídlo a pití',
        directions: 'Cesta',
        social: 'Společnost',
      },
      fullPlay: (time) => `${time} při 1×`,
    },
    nav: {
      main: 'Hlavní nabídka',
      home: 'Domů',
      explore: 'Objevovat',
      library: 'Knihovna',
      settings: (name) => (name ? `${name}: nastavení` : 'Nastavení'),
      learning: (language) => `Učíte se: ${language}`,
      add: 'Přidat frázi nebo sadu',
      addSheet: 'Přidat',
      points,
      pointsShort: (c) => n(c, { one: 'b.', few: 'b.', other: 'b.' }),
    },
    status: {
      new: 'Nová',
      listenedNotRated: 'Poslechnutá, bez hodnocení',
      due: 'Čas zopakovat',
      learned: (pct) => `Naučená · paměť ${pct}\u00a0%`,
      learning: (pct, when) => `Paměť ${pct}\u00a0% · znovu ${when}`,
      set: { new: 'Nová', 'in-progress': 'Rozpracovaná', learned: 'Vše naučeno' },
    },
    home: {
      firstRun: 'Poslechněte si frázi a řekněte ji sami, než ji uslyšíte znovu.',
      learned: 'Naučeno',
      started: 'Začato',
      today: (heard, rated) =>
        `Dnes: ${n(heard, { one: `poslechnutá ${heard} fráze`, few: `poslechnuté ${heard} fráze`, other: `poslechnutých ${heard} frází` })} · hodnocení:\u00a0${rated}`,
      reviewTitle: 'Opakování',
      reviewBody: (due) => `K opakování: ${phrases(due)}`,
      reviewCapped: (shown) => `V této relaci zazní ${shown} nejdéle odložených.`,
      playPhrases: (c) => `Poslouchat: ${phrases(c)}`,
      duration: (time) => `${time} při 1×`,
      startTitle: 'Odkud začít',
      continueTitle: 'Pokračovat',
      nextTitle: 'Další sada',
      next: (c, when) => `Dále: ${phrases(c)} ${when}`,
      nextAfter: (c, when) => `Potom: ještě ${phrases(c)} ${when}`,
      jumpBackIn: 'Vrátit se',
      history: 'Historie',
      notStarted: 'Zatím nezačaté',
      demoTitle: 'Vyzkoušejte smyčku',
      demoBody: 'Jedna fráze: uslyšet, říct, uslyšet.',
      demoButton: 'Poslechnout jednu frázi',
      courseDoneTitle: 'Všechny fráze tohoto kurzu jsou naučené',
      courseDoneBody: 'Opakování se vrátí, až na ně přijde čas. Zatím si můžete přidat vlastní fráze nebo zkusit jiný kurz.',
      addOwn: 'Vlastní fráze',
      otherCourse: 'Jiný kurz',
    },
    history: {
      title: 'Historie',
      empty: 'Zatím nic nezaznělo.',
      mixed: 'Smíšená fronta',
      run: (p, pts) => `${phrases(p)} · +${points(pts)}`,
    },
    explore: {
      search: 'Fráze, poznámky, témata',
      searchShort: 'Hledat',
      topics: 'Témata',
      levels: 'Úrovně',
      tags: 'Štítky',
      allSets: 'Všechny sady',
      sets,
      phrases,
      noPhrases: (q) => `Žádné fráze k hledání „${q}“.`,
      noPhrasesFiltered: 'Žádné fráze s těmito filtry.',
      noSets: 'Žádné vyhovující sady.',
      addAsOwn: (q) => `Přidat „${q}“ jako vlastní frázi`,
      removeFilter: (label) => `Odebrat filtr: ${label}`,
      clearFilters: 'Zrušit filtry',
      quickPlay: (title) => `Poslouchat „${title}“`,
      searchedSets: 'Sady',
    },
    set: {
      phrasesHeading: 'Fráze',
      summary: (total, learned, due) => `${phrases(total)} · naučeno ${learned}${due > 0 ? ` · k opakování ${due}` : ''}`,
      sort: { set: 'Jako v sadě', az: 'A–Ž', due: 'Nejdřív k opakování', weakest: 'Nejdřív slabší' },
      sortTitle: 'Řazení frází',
      playsIn: (order) => `Pořadí: ${order}`,
      playAll: (title) => `Poslouchat „${title}“`,
      pauseAll: (title) => `Pauza: „${title}“`,
      resume: (title) => `Pokračovat v „${title}“`,
      pausedAt: (position, total) => `Pozastaveno: ${position} z ${total}`,
      playDueNew: (c) => `Jen nové a k opakování (${c})`,
      pauseDueNew: 'Pauza: nové a k opakování',
      shufflePlay: 'Zamíchat',
      like: 'Přidat sadu k oblíbeným',
      duration: (time) => `Celá sada ${time} při 1×`,
      playNext: 'Zařadit jako další',
      addToQueue: 'Do fronty',
      share: 'Sdílet odkaz',
      linkCopied: 'Odkaz zkopírován',
      copyUnavailable: 'Kopírování tu není dostupné',
      own: 'Vaše sada',
      ownEmpty: 'Přidávejte fráze z jejich podrobností (⋮) nebo z přehrávače.',
      addPhrases: 'Přidat fráze',
      addedNext: 'Zazní jako další',
      addedEnd: 'Přidáno do fronty',
      notFound: 'Tato sada není dostupná.',
      otherCourse: (language) => `Tato sada patří ke kurzu: ${language}.`,
      switchCourse: (language) => `Učit se: ${language}`,
    },
    phrase: {
      details: (text) => `Podrobnosti: ${text}`,
      play: (text) => `Poslouchat: ${text}`,
      playNext: 'Zařadit jako další',
      addToQueue: 'Do fronty',
      like: 'Přidat k oblíbeným',
      liked: 'Oblíbená',
      likeLabel: 'Přidat frázi k oblíbeným',
      addToSet: 'Do sady…',
      heard: (c) => `poslechnuto ${c}×`,
      notes: { mnemonic: 'Mnemotechnika', grammar: 'Gramatika', pronunciation: 'Zvuky' },
      notesTitle: 'Poznámky',
      notesInEnglish: 'Poznámky jsou zatím anglicky.',
      noteAgain: { mnemonic: 'Nová mnemotechnika', grammar: 'Vysvětlit jinak' },
      noteWriting: (language: string) => `Píšu novou — jazyk: ${language}…`,
      noteEarlier: (count: number) => `Dřívější (${count})`,
      noteHideEarlier: 'Skrýt dřívější',
      words: 'Klepněte na slovo a uvidíte jeho význam.',
      glossHint: 'Ukáže význam',
      edit: 'Upravit frázi',
      delete: 'Smazat frázi',
      deleted: 'Fráze smazána',
      removeFromSet: 'Odebrat z této sady',
      removedFromSet: 'Odebráno ze sady',
      moveUp: 'Výš v této sadě',
      moveDown: 'Níž v této sadě',
      yours: 'Vaše fráze',
      yoursShort: 'Vaše',
      sounds: 'Výslovnost:',
      notesByRules: (language: string) =>
        `Loro sestavil tyto poznámky podle svých písemných pravidel pravopisu a gramatiky (jazyk: ${language}). Rodilý mluvčí je nekontroloval.`,
      deleteConfirm: (target: string) => `Smazat „${target}“ ze všech vašich sad? Spolu s ní se smaže i její pokrok.`,
      removeDeletes: (target: string) => `Žádná jiná vaše sada „${target}“ neobsahuje, takže její odebrání ji smaže i s pokrokem.`,
      writeNotes: 'Požádat o poznámky autora',
      writingNotes: 'Píšeme poznámky…',
      notesFailed: 'Autor neodpověděl. Zkuste to za chvíli znovu.',
      notesByAi: 'Poznámky k ní napsala umělá inteligence. Rodilý mluvčí je nekontroloval.',
    },
    addToSet: {
      title: 'Přidat do sady',
      newSet: 'Nová sada…',
      added: (title) => `Přidáno do „${title}“`,
      already: (title) => `Už je v „${title}“`,
      alreadyHere: 'Už je v této sadě',
      none: 'Zatím nemáte žádnou vlastní sadu.',
    },
    pickPhrases: {
      search: 'Hledat fráze',
      add: 'Přidat',
      added: 'Přidáno',
      done: 'Hotovo',
    },
    createSet: {
      title: 'Nová sada',
      renameTitle: 'Přejmenovat sadu',
      editTitle: 'Název a popis',
      description: 'Popis (nepovinné)',
      descriptionHint: 'Zobrazí se všude, kde ji ostatní najdou.',
      name: 'Název',
      create: 'Vytvořit',
      created: (title) => `Vytvořeno: „${title}“`,
      taken: 'Sada s tímto názvem už existuje.',
    },
    addPhrase: {
      title: 'Vlastní fráze',
      target: (language) => `Jazyk: ${language}`,
      native: (language) => `Jazyk: ${language}`,
      hint: 'Hlas Loro ji pronese, hned jak ji přidáte.',
      add: 'Přidat frázi',
      added: 'Fráze přidána',
      editTitle: 'Upravit vlastní frázi',
      edited: 'Fráze upravena',
      duplicate: 'Už je v kurzu:',
    },
    make: {
      title: 'Sestavit sadu',
      into: (set) => `Přidat do „${set}“`,
      entryDetail: 'Návrhy frází podle tématu, slov nebo textu',
      intro: 'O čem chcete mluvit?',
      modesLabel: 'Navrhnout podle',
      modes: { topic: 'Téma', keywords: 'Slova', text: 'Text' },
      field: { topic: 'Téma nebo situace', keywords: 'Pár slov', text: 'Váš text' },
      placeholder: {
        topic: 'V lékárně',
        keywords: 'hotel, ručník, snídaně',
        text: 'Zpráva, jídelní lístek, pár řádků, které chcete umět říct',
      },
      hintTopic: 'Nejlépe funguje místo nebo okamžik.',
      hintKeywords: 'Oddělte je čárkami.',
      hintText: (language) => `V libovolném jazyce: fráze budou ${adverb(language)}.`,
      tryTopics: 'Nebo si vyberte',
      suggest: 'Navrhnout fráze',
      writing: 'Píšeme fráze…',
      byAi: 'Návrhy píše umělá inteligence. Rodilý mluvčí je nekontroloval.',
      byBank: 'Z banky frází Loro: na tomto serveru není umělá inteligence nastavená.',
      none: (input) => `Pro „${input}“ zatím nejsou žádné fráze.`,
      noneHint: 'Zkuste jiná slova nebo napište frázi sami.',
      writeOwn: 'Přidat vlastní frázi',
      progress: (position, total) => `${position} z ${total}`,
      addedCount: (count) => `Přidáno: ${count}`,
      cardLabel: (position, total) => `Návrh ${position} z ${total}`,
      source: {
        course: (set) => `Ze sady „${set}“`,
        mine: 'Vaše fráze',
        bank: 'Fráze Loro',
        ai: 'Napsala AI · nezkontrolováno',
      },
      listen: (text) => `Poslechnout: ${text}`,
      edit: 'Opravit',
      editLabel: (text) => `Opravit: ${text}`,
      add: 'Přidat',
      skip: 'Přeskočit',
      addLabel: (text) => `Přidat: ${text}`,
      skipLabel: (text) => `Přeskočit: ${text}`,
      undoLabel: (text) => `Vrátit zpět: ${text}`,
      swipeHint: 'Přejetím doprava přidáte, doleva přeskočíte.',
      keysHint: 'Klávesy: → přidat, ← přeskočit.',
      announceAdded: (text) => `Přidáno: ${text}`,
      announceSkipped: (text) => `Přeskočeno: ${text}`,
      done: 'Hotovo',
      endTitle: (count) => (count === 1 ? 'To byl jediný návrh' : `To je všech návrhů: ${count}`),
      endAdded: (count) => (count === 0 ? 'Přeskočili jste všechny.' : `Přidané fráze: ${count}.`),
      more: 'Další návrhy',
      noMore: 'Další návrhy k tomuto nejsou.',
      another: 'Zkusit něco jiného',
      review: (count) => `Uložit: ${phrases(count)}`,
      saveTitle: 'Uložit sadu',
      keptHeading: (count) => `K uložení: ${phrases(count)}`,
      remove: (text) => `Vynechat: ${text}`,
      addInto: (count, set) => `Přidat do „${set}“: ${phrases(count)}`,
      addedInto: (count, set) => `Přidáno do „${set}“: ${phrases(count)}`,
      backToDeck: 'Zpět k návrhům',
      unsaved: (count) => `Neuloženo: ${phrases(count)}`,
      reopen: 'Otevřít znovu',
      fromExplore: (query) => `Navrhnout fráze k tématu „${query}“`,
      fromSet: 'Navrhnout fráze',
      originAi: 'Napsala umělá inteligence. Rodilý mluvčí to nekontroloval.',
      originBank: 'Z frází Loro.',
      defaultTitleText: 'Z mého textu',
    },
    player: {
      dialog: 'Právě hraje',
      close: 'Zavřít přehrávač',
      openQueue: 'Otevřít frontu',
      summary: 'Shrnutí relace',
      position: (i, total) => `${i} z ${total}`,
      positionInQueue: (i, total) => `${i} z ${total} ve frontě`,
      hidden: () => 'Fráze je skrytá, dokud ji neuslyšíte',
      steps: 'Kroky',
      yourTurn: 'Jste na řadě',
      again: 'Ještě jednou',
      instruction: {
        native: (language) => `Poslouchejte: ${language}`,
        pause: (language) => `Jste na řadě — řekněte to nahlas ${adverb(language)}`,
        target: (language) => `Poslouchejte: ${language}`,
        echo: (language) => `Zopakujte to ${adverb(language)} tak, jak jste to slyšeli`,
        rate: 'Ohodnoťte, nebo chvíli počkejte',
      },
      paused: 'Pauza',
      coach: 'Řekněte ji hned, než ji uslyšíte. Nic se nenahrává — potom sami ohodnotíte, jak to šlo.',
      repetition: (r, total) => `Opakování ${r} z ${total}`,
      howDidItGo: 'Vybavili jste si ji?',
      rateAfterTurn: 'Ohodnoťte, až ji řeknete',
      nextIn: (interval) => `za ${interval}`,
      rated: (grade, when) => `Hodnocení „${grade}“ — znovu ${when}`,
      scheduled: 'Opakování je naplánované',
      backLater: 'Vrátí se na konci fronty',
      ratedPrevious: (grade) => `Předchozí fráze: „${grade}“`,
      ratedAs: (grade) => `Hodnocení „${grade}“`,
      rateAs: (grade) => `Ohodnotit: „${grade}“`,
      undoGrade: (grade) => `Vrátit zpět „${grade}“`,
      pass: {
        title: 'Všechno poslechnuto',
        again: 'Začínáme znovu, od první fráze',
        next: (title) => `Dále — „${title}“`,
        nextReview: 'Dále — opakování',
        done: 'Zatím není nic nového',
        goOn: (title) => `Další sada: „${title}“`,
      },
      undoFor: (time) => `Vrátit zpět · ${time}`,
      undoLabel: (time) => `Vrátit hodnocení zpět (zbývá ${time})`,
      previous: 'Předchozí fráze',
      next: 'Další fráze',
      repeats: {
        auto: 'Opakování: automaticky (3× u nových a nejistých, 1× u zapamatovaných)',
        one: 'Opakování: 1',
        three: 'Opakování: 3',
      },
      playMode: {
        repeat: 'Na konci: začít frontu znovu',
        continue: 'Na konci: pokračovat dalšími frázemi',
      },
      captions: { reps: 'opak.', again: 'Znovu', continue: 'Dál', auto: 'Auto' },
      repeatsToast: {
        auto: 'Každá fráze zazní 3×, dokud je nová, a 1×, až se zapamatuje',
        one: 'Každá fráze zazní jednou',
        three: 'Každá fráze zazní 3×',
      },
      playModeToast: {
        repeat: 'Na konci začne fronta znovu',
        continue: 'Na konci přijdou nové fráze',
      },
      speedIs: (speed) => `Rychlost: ${speed}×`,
      keys: 'Klávesy: mezerník — přehrát nebo pozastavit · ← → zpět, vpřed · 1 2 3 — hodnocení',
      audioError: (language) => `Loro zatím nemá nahrávku této fráze (${language}), a proto se nepřehraje.`,
      showText: () => 'Zobrazit text',
      end: {
        reviewTitle: 'Opakování hotovo',
        listTitle: 'Všechno poslechnuto',
        playedThrough: 'Poslechnuto až do konce',
        rated: (count) => `Ohodnoceno: ${count}`,
        nextReview: (when) => `Další opakování ${when}`,
        nothingDue: 'Zatím není co opakovat',
        continueSet: (title) => `Pokračovat v „${title}“`,
        playAgain: 'Poslouchat znovu',
        demoTitle: 'Tak to funguje',
        demoBody: 'Uslyšet, říct nahlas, uslyšet, ohodnotit. Chcete zkusit celou sadu?',
        startSet: (title) => `Začít „${title}“`,
        notNow: 'Teď ne',
      },
      noClip: 'Nahrávka této fráze zatím není',
      audioSilent: 'Nahrávka nezazněla. Zkontrolujte připojení a stiskněte „Poslouchat“.',
      silent: 'Nezazněla — stiskněte „Poslouchat“',
      makingAudio: (language) => `Připravujeme nahrávku této fráze (${language}). Zazní, jakmile bude hotová.`,
      making: 'Připravujeme nahrávku…',
      audioUnmade: (language) => `Nahrávku této fráze (${language}) se teď nepodařilo připravit. Zkuste to za chvíli znovu.`,
      unmade: 'Nahrávku se zatím nepodařilo připravit',
    },
    toast: {
      updateReady: 'Je připravená nová verze Loro',
      reload: 'Načíst znovu',
      dismiss: 'Zavřít zprávu',
      learned: (pts) => `Naučeno · +${pts}`,
      removed: 'Odebráno z fronty',
      cleared: 'Fronta vyprázdněna',
      saved: (title) => `Uloženo jako „${title}“`,
      storageFull: 'Úložiště Loro v tomto zařízení je plné, nový pokrok se neukládá.',
      storageUnavailable: 'Tento prohlížeč Loro neumožňuje ukládat pokrok v zařízení.',
      outdated: 'V jiném panelu je otevřená novější verze Loro. Načtěte znovu, aby se pokrok ukládal i tady.',
    },
    queue: {
      title: 'Fronta',
      back: 'Zpět k přehrávači',
      left: (c) => `Zbývá ${c}`,
      nowPlaying: 'Právě hraje',
      upNext: (c) => `Dále · ${c}`,
      nothing: 'Po této frázi už nic nenásleduje.',
      hint: 'Přejetím doprava přehrajete hned, doleva odeberete. Tažením za úchyt změníte pořadí, klepnutím na něj otevřete možnosti.',
      handleHint: 'Enter — možnosti; šipky nahoru a dolů — přesunout, Delete — odebrat.',
      moveUp: 'Přesunout výš',
      moveDown: 'Přesunout níž',
      removeFromQueue: 'Odebrat z fronty',
      moved: (position, total) => `Nyní na pozici ${position} z ${total}`,
      playNow: (text) => `Poslouchat hned: ${text}`,
      move: (text) => `Přesunout: ${text}`,
      swipePlay: 'Poslouchat',
      swipeRemove: 'Odebrat',
      previously: 'Už zazněly',
      again: 'Znovu',
      justNow: 'právě teď',
      playNext: (text) => `Zařadit jako další: ${text}`,
      clear: 'Vyprázdnit frontu',
      saveAsSet: 'Uložit jako sadu',
      shuffle: 'Zamíchat následující',
      defaultSetName: 'Moje fronta',
    },
    library: {
      learned: 'Naučeno',
      learnedNote: (d, recalls) => `Paměť vydrží ${d}+ dní, po ${recalls}+ vybavení`,
      recall: 'Paměť teď',
      recallNote: (rated) =>
        n(rated, { one: `Průměr z ${rated} ohodnocené fráze`, few: `Průměr ze ${rated} ohodnocených frází`, other: `Průměr z ${rated} ohodnocených frází` }),
      recallNone: 'Nejdřív ohodnoťte frázi',
      started: 'Začato',
      startedNote: 'Poslechnuté nebo ohodnocené aspoň jednou',
      phrasesSegment: 'Fráze',
      setsSegment: 'Sady',
      albumsSegment: 'Alba',
      filters: {
        liked: 'Oblíbené',
        mine: 'Moje',
        due: 'K opakování',
        learning: 'Učím se',
        missed: 'Nedávno nevybavené',
        learned: 'Naučené',
        ownSets: 'Moje sady',
        likedSets: 'Oblíbené sady',
        albums: 'Alba',
      },
      empty: {
        liked: 'Klepněte na srdíčko u fráze a bude tady.',
        mine: 'Přidejte vlastní frázi — zazní jako každá jiná.',
        due: 'Teď není co opakovat.',
        learning: 'Tady jsou fráze, které jste slyšeli nebo ohodnotili, ale ještě je neumíte.',
        missed: 'Tady jsou fráze s hodnocením „Nepamatuji si“ za poslední týden.',
        learned: (d, recalls) =>
          `Fráze je naučená, když má paměť na ni vydržet ${days(d)} nebo déle, a to po aspoň ${recalls} úspěšných vybaveních.`,
        ownSets: 'Vytvořte sadu a seskupte si fráze po svém.',
        likedSets: 'Klepněte na srdíčko u sady a bude tady.',
      },
      playAll: (c) => `Poslouchat vše (${c})`,
      addPhrase: 'Vlastní fráze',
      myPhrases: 'Moje fráze',
      likedPhrases: 'Oblíbené fráze',
      onDevice: (p, s) => `Jen v tomto zařízení: vlastních frází — ${p}, vlastních sad — ${s}. Přihlaste se a uložte je do účtu; pokrok zůstane s nimi.`,
      uploaded: 'Vaše fráze a sady z tohoto zařízení jsou teď v účtu.',
      newSet: 'Nová sada',
      recallChart: 'Odhad paměti teď',
      recallBucket: (from, to) => `${from}–${to}\u00a0%`,
      recallBelow: (to) => `méně než ${to}\u00a0%`,
      recallChartEmpty: 'Ohodnoťte frázi a uvidíte to.',
      bucketCount: (label, c) => `${label}: ${phrases(c)}`,
      weeklyChart: 'Naučeno za týden',
      weekOf: (date, c) => `Týden od ${date}: naučeno ${c}`,
      progress: 'Pokrok',
    },
    settings: {
      title: 'Nastavení',
      switched: (language, queueCleared) => `Kurz: ${language}${queueCleared ? '. Fronta byla vyprázdněna' : ''}`,
      courseUnavailable: (language) => `Kurz se nepodařilo stáhnout (${language}). Zkontrolujte připojení a zkuste to znovu.`,
      profile: 'Profil',
      name: 'Jméno',
      native: 'Můj jazyk',
      course: 'Učím se',
      courseNote: 'Pokrok se uchovává pro každou dvojici jazyků. Až se přepnete zpět, vrátí se.',
      accessibility: 'Čtečka obrazovky',
      announceEveryStep: 'Oznamovat každý krok',
      announceHint: 'Vypnuto: oznamuje se jen „Jste na řadě“ a odhalení fráze.',
      listening: 'Poslech',
      pauseLength: 'Čas na odpověď',
      pause: { standard: 'Běžný', longer: 'Delší' },
      pauseHint: '„Delší“ je zhruba dvojnásobek délky fráze.',
      privacy: 'Soukromí',
      shareUsage: 'Sdílet data o používání',
      shareUsageHint: 'Klepnutí, obrazovky a záznam obrazovky nám pomáhají Loro zlepšovat. Váš hlas nikdy.',
    },
    onboarding: {
      step: (i, total) => `Krok ${i} z ${total}`,
      welcome: 'Učte se jazyk po frázích: uslyšet, říct, uslyšet.',
      name: 'Jak vám máme říkat?',
      namePlaceholder: 'Vaše jméno',
      native: 'Jakým jazykem mluvíte?',
      course: 'Jaký jazyk se učíte?',
      loop: 'Jak to funguje',
      loopSteps: (native, target) => [
        `Poslechněte si frázi: ${native}.`,
        `Řekněte ji nahlas ${adverb(target)}, dokud je ticho.`,
        `Poslechněte si ji: ${target}.`,
        'Ohodnoťte, jak to šlo: „Nepamatuji si“, „Těžké“ nebo „Snadné“. Hodnocení můžete pět minut měnit.',
      ],
      next: 'Dál',
      start: 'Začít jednou frází',
      skip: 'Začít bez ukázky',
    },
    summary: {
      title: 'Tato relace',
      phrases: 'Fráze',
      repetitions: 'Opakování',
      ratings: 'Hodnocení',
      pending: (c) => `ještě jde změnit: ${c}; jejich body a další opakování se započítají po pěti minutách`,
      points: 'Získané body',
      passes: 'Průchodů frontou',
      nextDue: 'Další opakování',
      nothingDue: 'Zatím nic naplánováno',
      none: 'V této relaci zatím nic nezaznělo.',
    },
    connection: {
      loading: 'Načítáme váš kurz…',
      offlineTitle: 'Loro se nemůže spojit se serverem',
      offlineBody: 'Kurz se stáhne jednou a pak funguje bez sítě. Zkontrolujte připojení a zkuste to znovu.',
      retry: 'Zkusit znovu',
      useCourse: (language) => `Pokračovat v kurzu: ${language}`,
    },
    account: {
      title: 'Účet',
      signIn: 'Přihlásit se',
      signInTitle: 'Přihlášení do Loro',
      signInBody: 'Vytvářejte sady frází, písně a obálky s umělou inteligencí, mějte je v účtu a sdílejte je. Pokrok v tomto zařízení zůstane, jak je.',
      email: 'E-mail',
      emailPlaceholder: 'vy@priklad.cz',
      sendCode: 'Poslat kód e-mailem',
      sending: 'Odesíláme…',
      codeTitle: 'Zkontrolujte e-mail',
      codeBody: (email) => `Poslali jsme šestimístný kód na ${email}. Platí 10 minut.`,
      code: 'Šestimístný kód',
      verify: 'Přihlásit se',
      verifying: 'Přihlašujeme…',
      resend: 'Poslat nový kód',
      changeEmail: 'Jiný e-mail',
      signedInAs: (email) => `Přihlášeni jako ${email}`,
      signedInWith: (provider) => `Přihlášeni přes ${provider}`,
      signOut: 'Odhlásit se',
      deleteData: 'Smazat moje data v Loro',
      deleteDataConfirm: 'Smazat vaše sady, alba, písně, obálky a pokrok uložený v účtu? Ti, s nimiž jste je sdíleli, o ně také přijdou. Pokrok v tomto zařízení zůstane. Nelze to vrátit zpět.',
      deletedData: 'Vaše data v Loro jsou smazaná.',
      deleteAccount: 'Smazat můj účet',
      deleteAccountConfirm: 'Smazat váš účet Loro se vším, co v něm je: sadami, alby, písněmi, obálkami a uloženým pokrokem? Ti, s nimiž jste je sdíleli, o ně také přijdou. Pokrok v tomto zařízení zůstane. Nelze to vrátit zpět.',
      deleteAccountYes: 'Smazat účet',
      deletedAccount: 'Váš účet je smazaný.',
      synced: 'Váš pokrok je uložený v účtu a objeví se i na dalších zařízeních.',
      syncFailed: 'Pokrok se teď nepodařilo uložit do účtu. V tomto zařízení je v bezpečí a uloží se, až bude zase připojení.',
      signedOut: 'Jste odhlášeni. Pokrok v tomto zařízení zůstal.',
      welcome: 'Jste přihlášeni',
      displayName: 'Jméno u toho, co sdílíte',
      displayNameHint: 'Zobrazí se jako „od …“ u sad a alb, které zveřejníte. Nechte prázdné, aby se zobrazilo „od studenta“.',
      displayNameSaved: 'Jméno uloženo',
      notNow: 'Teď ne',
      google: 'Pokračovat přes Google',
      apple: 'Pokračovat přes Apple',
      needed: 'Přihlaste se, abyste mohli vytvářet sady, písně a obálky s umělou inteligencí a sdílet je.',
      errors: {
        badEmail: 'Tohle nevypadá jako e-mailová adresa.',
        badCode: 'Kód není správný, nebo mu vypršela platnost.',
        tooMany: 'Příliš mnoho pokusů. Počkejte pár minut a zkuste to znovu.',
        unavailable: 'Přihlášení e-mailem na tomto serveru není nastavené.',
        providerUnavailable: (provider: string) => `Přihlášení přes ${provider} není pro tuto adresu Loro nastavené.`,
        offline: 'Loro se nemůže spojit se serverem. Zkontrolujte připojení.',
        generic: 'Něco se nepovedlo. Zkuste to znovu.',
        full: 'V účtu je už nejvyšší možný počet těchto položek. Smažte některou, abyste uvolnili místo.',
        invalid: 'Nepodařilo se to uložit: něco je příliš dlouhé, chybí, nebo obsahuje odkaz.',
      },
      today: 'Dnešní limit',
      usage: {
        phrases: (left, limit) => `Sady frází: zbývá ${left} z ${limit}`,
        cover: (left, limit) => `Obálky: zbývá ${left} z ${limit}`,
        song: (left, limit) => `Písně: zbývá ${left} z ${limit}`,
        lyrics: (left, limit) => `Texty: zbývá ${left} z ${limit}`,
      },
      kept: (s, a) => `V účtu: ${sets(s)} a ${albums(a)}`,
      resets: (time) => `Obnoví se v ${time}`,
      spent: (time) => `Dnešní limit je vyčerpaný. Obnoví se v ${time}.`,
      writers: 'Kdo to na tomto serveru vytváří',
      writer: {
        ai: 'Umělá inteligence',
        bank: 'Banka frází Loro (AI není nastavená)',
        pattern: 'Kreslené vzory (AI není nastavená)',
        phrases: 'Vaše fráze jako text písně (AI není nastavená)',
        elevenlabs: 'Zpívá ElevenLabs Music',
        demo: 'Ukázkový zvuk (hudba není nastavená)',
      },
      writerKind: { phrases: 'Fráze', cover: 'Obálky', lyrics: 'Text', music: 'Zvuk' },
    },
    tabs: {
      home: 'Domů',
      explore: 'Objevovat',
      create: 'Vytvořit',
      library: 'Knihovna',
    },
    share: {
      hidden: 'Někdo to nahlásil, proto to už není vidět v Komunitě. Přes odkaz to jde stále otevřít.',
      noName: 'Ostatní to vidí jako „od studenta“. Uveďte jméno, aby byl vidět autor.',
      addName: 'Uvést jméno',
      visibility: 'Kdo to může vidět',
      private: 'Jen vy',
      privateDetail: 'Ve vašem účtu, na vašich zařízeních',
      link: 'Každý, kdo má odkaz',
      linkDetail: 'Není ve výpisech; otevře se přes odkaz',
      public: 'Všichni',
      publicDetail: 'V Komunitě vašeho kurzu',
      share: 'Sdílet',
      shareMessage: (title, url) => `${title} v Loro: ${url}`,
      copied: 'Odkaz zkopírován',
      makeShareable: 'Vidíte to jen vy. Před sdílením vyberte, kdo to může vidět.',
      by: (name) => `od ${name}`,
      byLearner: 'od studenta',
      yours: 'Vaše',
      save: 'Uložit do knihovny',
      saved: 'Ve vaší knihovně',
      unsave: 'Odebrat z knihovny',
      savedToast: 'Uloženo do knihovny',
      unsavedToast: 'Odebráno z knihovny',
      delete: 'Smazat',
      deleteSetConfirm: (title) => `Smazat „${title}“ z účtu? Ti, s nimiž jste ji sdíleli, o ni také přijdou. Pokrok u jejích frází zůstane.`,
      deleteAlbumConfirm: (title) => `Smazat album „${title}“ a jeho písně?`,
      deleted: 'Smazáno',
      cover: 'Nová obálka',
      coverMaking: 'Kreslíme obálku…',
      coverBy: { ai: 'Obálku nakreslila AI', pattern: 'Kreslený vzor' },
      coverLater: 'Obálka se ještě kreslí. Objeví se, až bude hotová.',
      coverFor: (title) => `Nová obálka pro „${title}“`,
      coverAsk: {
        own: 'Nově nakreslená obálka nahradí tu současnou.',
        set: 'Sady Loro se nemění, proto dostanete vlastní kopii této sady s novou obálkou — v Knihovně. Pokrok u jejích frází zůstane.',
        album: 'Alba Loro se nemění, proto dostanete vlastní kopii tohoto alba a jeho písní s novou obálkou — v Knihovně.',
        phrase: 'Obálka této fráze, kterou vidíte jen vy: všude, kde se fráze zobrazuje, na všech zařízeních, kde jste přihlášeni.',
        song: 'Obálka této písně, kterou vidíte jen vy, na všech zařízeních, kde jste přihlášeni.',
      },
      coverDrawn: 'Obálky jsou kreslené obrázky bez slov, nikdy ne fotografie.',
      coverDraw: 'Nakreslit obálku',
      coverCopied: 'Vaše kopie je v Knihovně',
      coverPrompt: 'Co má zobrazovat?',
      coverPromptHint: 'Popište obrázek vlastními slovy.',
      coverEarlier: 'Vaše obálky',
      coverEarlierHint: 'Klepnutím obálku znovu použijete. Nečerpá to dnešní obálky.',
      coverUse: (prompt: string | null) => (prompt ? `Použít obálku „${prompt}“` : 'Použít tuto obálku'),
      coverInUse: 'Používá se',
      coverPut: 'Obálka změněna',
      changed: 'Uloženo',
      notFound: 'Tento odkaz nic neotevírá. Možná byl nastaven jako soukromý nebo smazán.',
      opening: 'Otevíráme…',
      report: 'Nahlásit',
      reported: 'Nahlášeno. Děkujeme.',
      reason: { offensive: 'Urážlivé nebo zraňující', wrong: 'Špatný jazyk nebo chyby', spam: 'Spam nebo reklama', other: 'Něco jiného' },
    },
    community: {
      title: 'Komunita',
      sets: 'Sdílené sady',
      albums: 'Sdílená alba',
      emptySets: 'V tomto kurzu zatím nikdo nesdílel sadu. Vytvořte svou a vyberte „Všichni“.',
      emptyAlbums: 'V tomto kurzu zatím nikdo nesdílel album.',
      search: 'Hledat ve sdílených sadách',
      searchAlbums: 'Hledat ve sdílených albech',
      moreBy: (name: string) => `Další od ${name}`,
      moreByLearner: 'Další od tohoto studenta',
      sortNew: 'Nejnovější',
      sortPopular: 'Nejčastěji ukládané',
      sortLabel: 'Pořadí',
      savedBy: (n: number) => `uloženo: ${n}×`,
      noSetsFound: (q: string) => `Žádná sdílená sada k hledání „${q}“.`,
      noAlbumsFound: (q: string) => `Žádné sdílené album k hledání „${q}“.`,
      offline: 'Komunita potřebuje připojení.',
    },
    phrasesTab: {
      title: 'Fráze',
      course: 'Kurz Loro',
      yourSets: 'Vaše sady',
      savedSets: 'Uložené sady',
      makeSet: 'Vytvořit sadu s AI',
      signInToMake: 'Přihlaste se a vytvářejte sady s AI',
    },
    music: {
      likedSongs: 'Oblíbené písně',
      likedEmpty: 'Klepněte na srdíčko u písně a bude tady.',
      songKind: 'Píseň',
      likeSong: 'Přidat píseň k oblíbeným',
      rateSong: (n: number) =>
        n === 1 ? 'Jak to šlo? Vaše hodnocení zopakuje frázi, kterou píseň zpívá.' : `Jak to šlo? Vaše hodnocení zopakuje fráze, které píseň zpívá (${n}).`,
      songRated: (grade: string, n: number) => (n === 1 ? `${grade}: její fráze je zopakovaná.` : `${grade}: její fráze jsou zopakované (${n}).`),
      songReviewed: (n: number) => (n === 1 ? 'Její fráze je zopakovaná.' : `Její fráze jsou zopakované (${n}).`),
      songReady: (title: string) => `„${title}“ je hotová`,
      songFailed: (title: string) => `„${title}“ se nepodařilo vytvořit. Můžete to zkusit znovu z jejího alba.`,
      play: 'Poslouchat',
      needsConnection: 'Písně potřebují připojení. Zkuste to znovu, až budete online.',
      cantPlay: 'Tuto píseň teď nejde přehrát.',
      setSongs: 'Písně',
      title: 'Hudba',
      loro: 'Od Loro',
      yours: 'Vaše alba',
      saved: 'Uložená alba',
      songs,
      empty: 'V tomto kurzu zatím nejsou žádná alba.',
      noSongs: 'Zatím tu nejsou žádné písně.',
      loroAlbum: 'Každá sada Loro z tohoto kurzu, zazpívaná.',
      makeSong: 'Vytvořit píseň',
      album: 'Album',
      playAlbum: 'Poslouchat album',
      playSong: (title) => `Poslouchat ${title}`,
      demoSound: 'Ukázkový zvuk',
      spokenDemo: 'Ukázka s hlasem',
      spokenNote: 'Řádky čte hlas Loro přes podkres, který vytvořil server; zvýrazňují se podle toho, jak zní. Písně se budou zpívat, až se nastaví hudební služba.',
      demoNote: 'Tento podkres vytvořil server; řádky textu se zvýrazňují podle toho, jak zní. Písně se budou zpívat, až se nastaví hudební služba.',
      sung: 'Zpívaná',
      lyrics: 'Text',
      lyricsBy: { ai: 'Text od AI', phrases: 'Text: fráze sady' },
      meanings: 'Významy',
      showMeanings: 'Ukázat významy',
      hideMeanings: 'Skrýt významy',
      section: { verse: 'Sloka', chorus: 'Refrén', bridge: 'Přechod' },
      rendering: 'Vytváříme píseň…',
      renderingNote: 'Chvíli to potrvá. Můžete opustit tuto obrazovku: píseň se bude dál vytvářet.',
      failed: 'Tuto píseň se nepodařilo vytvořit.',
      retrySong: (title: string) => `Zkusit „${title}“ znovu`,
      removeSong: 'Odebrat píseň',
      removeSongConfirm: (title: string) => `Odebrat „${title}“ z alba?`,
      songReadyTitle: 'Vaše písnička je hotová',
      songFailedTitle: 'Písničku se nepodařilo vytvořit',
      notificationChannel: 'Písně',
      heard: 'Poslechnuto',
      heardNote: 'Tento text je to, co Loro v písni slyšelo, každý řádek se svým časem. Kde zpěvák řádek změnil, je pod ním ten napsaný.',
      written: (text: string) => `Napsáno: ${text}`,
      skippedLine: 'V písni není slyšet',
      nowPlaying: 'Právě hraje',
      previous: 'Předchozí píseň',
      next: 'Další píseň',
      openSet: 'Otevřít sadu',
      fromSet: (title) => `Ze sady „${title}“`,
      loadFailed: 'Album se nepodařilo načíst.',
      style: {
        modern_pop: 'Pop',
        acoustic_folk: 'Folk',
        gentle_ballad: 'Balada',
        upbeat_kids: 'Zpívánky',
        indie_rock: 'Rock',
        hip_hop: 'Hip hop',
        reggaeton: 'Reggaeton',
        jazz_lounge: 'Jazz',
        electronic_dance: 'Dance',
        country: 'Country',
        lullaby: 'Ukolébavka',
        bossa_nova: 'Bossa nova',
      },
    },
    create: {
      title: 'Vytvořit',
      phrasesTitle: 'Sada frází',
      phrasesBody: 'Podle tématu, pár slov nebo textu.',
      songTitle: 'Píseň ze sady',
      songBody: 'Vaše fráze v písni.',
      left: (c) => `Dnes zbývá: ${c}`,
      none: 'Na dnešek nic nezbývá',
      source: { ai: 'AI', bank: 'Banka frází (bez AI)', elevenlabs: 'ElevenLabs Music', demo: 'Ukázkový zvuk' },
      pickSet: 'Která sada?',
      pickSetEmpty: 'V tomto kurzu zatím nejsou žádné sady.',
      pickStyle: 'Styl',
      pickAlbum: 'Album',
      newAlbum: 'Nové album',
      songTitleLabel: 'Název písně',
      makeSong: 'Vytvořit píseň',
      songStarted: 'Píseň se vytváří',
      writeLyrics: 'Napsat text',
      writingLyrics: 'Text se píše…',
      lyricsReady: 'Přečtěte si text. Nechte ho napsat znovu nebo změnit podle sebe, a pak zazpívat.',
      lyricsFailed: 'Text se nepodařilo napsat. Zkuste to znovu.',
      lyricsPlain: 'Na tomto serveru není nastavený AI autor, takže text jsou fráze sady tak, jak jsou.',
      draft: (n: number) => `Koncept ${n}`,
      rewriteLabel: 'Co změnit (nepovinné)',
      rewritePlaceholder: 'Kratší refrén, řádek o moři…',
      rewrite: 'Napsat znovu',
      rewriteAsAsked: 'Přepsat podle přání',
      approve: 'Zazpívat',
      backToSetup: 'Změnit sadu nebo styl',
      saveToAccount: 'Uložit do účtu',
      saving: 'Ukládáme…',
      savedToAccount: 'Uloženo do účtu',
      setTitle: 'Název',
      setDescription: 'K čemu je (nepovinné)',
      withCover: 'Nakreslit obálku',
      from: { ai: 'Napsala AI', bank: 'Z banky frází Loro' },
      bankOnly: 'Na tomto serveru není AI nastavená, proto tyto fráze pocházejí z banky frází Loro.',
      noMatch: 'V bance frází k tomu nic není. Zkuste jedno z těchto témat:',
    },
    error: {
      title: 'Něco se nepovedlo',
      body: 'Obvykle pomůže načíst znovu, pokrok se přitom zachová. Pokud se to opakuje, uložený pokrok možná neodpovídá této verzi: zkopírujte si ho, chcete-li ho zachovat, a pak ho obnovte, abyste v tomto zařízení začali od nuly.',
      reload: 'Načíst znovu',
      part: 'Tuto část obrazovky se nepodařilo zobrazit. Váš pokrok je v bezpečí.',
      copy: 'Zkopírovat pokrok jako JSON',
      copied: 'Zkopírováno',
      reset: 'Obnovit pokrok',
    },
  };
}
