// Every learner-facing string, in English. bg.ts and ru.ts must have the same
// shape (the Copy type enforces it). Numbers arrive already formatted; plurals
// go through `n()` so each language can use its own plural rules.
import type { Grade } from '../core/fsrs';
import type { Level, Register, Tag } from '../content';
import type { SuggestMode } from '../generate/types';
import type { PauseLength, PlayMode, SortKey } from '../state/types';
import type { PluralForms } from './plural';

export interface Plural {
  (count: number, forms: PluralForms): string;
}

export function makeEn(n: Plural) {
  return {
    locale: 'en-GB',
    common: {
      close: 'Close',
      back: 'Back',
      cancel: 'Cancel',
      charsLeft: (count: number) => n(count, { one: `${count} character left`, other: `${count} characters left` }),
      save: 'Save',
      undo: 'Undo',
      play: 'Play',
      pause: 'Pause',
      delete: 'Delete',
      moreOptions: 'More options',
      phrases: (count: number) => n(count, { one: `${count} phrase`, other: `${count} phrases` }),
      sets: (count: number) => n(count, { one: `${count} set`, other: `${count} sets` }),
      points: (count: number) => n(count, { one: `${count} point`, other: `${count} points` }),
      level: (level: Level) => level,
      grade: { missed: 'Missed', hard: 'Hard', easy: 'Easy' } satisfies Record<Grade, string>,
      register: { formal: 'Formal', informal: 'Informal', neutral: 'Neutral' } satisfies Record<Register, string>,
      tag: {
        politeness: 'Politeness',
        question: 'Questions',
        request: 'Requests',
        numbers: 'Numbers',
        food: 'Food & drink',
        directions: 'Directions',
        social: 'Social',
      } satisfies Record<Tag, string>,
      fullPlay: (time: string) => `${time} at 1×`,
    },
    nav: {
      main: 'Main',
      home: 'Home',
      explore: 'Explore',
      library: 'Library',
      settings: (name: string) => (name ? `${name}: settings` : 'Settings'),
      /** The avatar's description: the course its settings switch. */
      learning: (language: string) => `Learning ${language}`,
      /** Library's header action, and the sheet it opens. */
      add: 'Add a phrase or set',
      addSheet: 'Add',
      points: (count: number) => n(count, { one: `${count} point`, other: `${count} points` }),
      pointsShort: (count: number) => n(count, { one: 'pt', other: 'pts' }),
    },
    status: {
      new: 'New',
      listenedNotRated: 'Listened, not rated',
      due: 'Due now',
      learned: (pct: number) => `Learned · recall ${pct}%`,
      learning: (pct: number, when: string) => `Recall ${pct}% · back ${when}`,
      set: { new: 'New', 'in-progress': 'In progress', learned: 'All learned' },
    },
    home: {
      firstRun: 'Listen to a phrase, then say it before you hear it again.',
      learned: 'Learned',
      started: 'Started',
      today: (heard: number, rated: number) =>
        `Today: ${n(heard, { one: `${heard} phrase heard`, other: `${heard} phrases heard` })} · ${rated} rated`,
      reviewTitle: 'Review',
      reviewBody: (due: number) => n(due, { one: `${due} phrase is due`, other: `${due} phrases are due` }),
      reviewCapped: (shown: number) => `This session plays the ${shown} most overdue.`,
      playPhrases: (count: number) => n(count, { one: `Play ${count} phrase`, other: `Play ${count} phrases` }),
      duration: (time: string) => `${time} at 1×`,
      startTitle: 'Start here',
      continueTitle: 'Continue',
      /** The next set, not started yet, after the one before it has been through once. */
      nextTitle: 'Next set',
      next: (count: number, when: string) => n(count, { one: `Next: ${count} phrase ${when}`, other: `Next: ${count} phrases ${when}` }),
      nextAfter: (count: number, when: string) => n(count, { one: `After these: ${count} more phrase ${when}`, other: `After these: ${count} more phrases ${when}` }),
      jumpBackIn: 'Jump back in',
      history: 'History',
      notStarted: 'Not started yet',
      demoTitle: 'Try the loop',
      demoBody: 'One phrase: hear it, say it, hear it.',
      demoButton: 'Play one phrase',
      courseDoneTitle: 'Every phrase in this course is learned',
      courseDoneBody: 'Reviews come back as they fall due. Meanwhile, add phrases of your own or try another course.',
      addOwn: 'Add your phrase',
      otherCourse: 'Try another course',
    },
    history: {
      title: 'History',
      empty: 'Nothing played yet.',
      mixed: 'Mixed queue',
      run: (phrases: number, points: number) =>
        `${n(phrases, { one: `${phrases} phrase`, other: `${phrases} phrases` })} · +${n(points, { one: `${points} pt`, other: `${points} pts` })}`,
    },
    explore: {
      search: 'Phrases, notes, topics',
      /** The search field's placeholder when the whole one doesn't fit (large text). */
      searchShort: 'Search',
      topics: 'Topics',
      levels: 'Levels',
      tags: 'Tags',
      allSets: 'All sets',
      sets: (count: number) => n(count, { one: `${count} set`, other: `${count} sets` }),
      phrases: (count: number) => n(count, { one: `${count} phrase`, other: `${count} phrases` }),
      noPhrases: (query: string) => `No phrases match “${query}”.`,
      noPhrasesFiltered: 'No phrases match these filters.',
      noSets: 'No sets match.',
      addAsOwn: (query: string) => `Add “${query}” as your phrase`,
      removeFilter: (label: string) => `Remove filter: ${label}`,
      clearFilters: 'Clear filters',
      quickPlay: (title: string) => `Play ${title}`,
      searchedSets: 'Sets',
    },
    set: {
      phrasesHeading: 'Phrases',
      summary: (total: number, learned: number, due: number) =>
        `${n(total, { one: `${total} phrase`, other: `${total} phrases` })} · ${learned} learned${due > 0 ? ` · ${due} due` : ''}`,
      sort: { set: 'Set order', az: 'A–Z', due: 'Due first', weakest: 'Lowest recall first' } satisfies Record<SortKey, string>,
      sortTitle: 'Sort phrases',
      playsIn: (order: string) => `Plays in: ${order}`,
      playAll: (title: string) => `Play ${title}`,
      pauseAll: (title: string) => `Pause ${title}`,
      resume: (title: string) => `Resume ${title}`,
      pausedAt: (position: number, total: number) => `Paused at ${position} of ${total}`,
      playDueNew: (count: number) => `Play due and new (${count})`,
      pauseDueNew: 'Pause due and new',
      shufflePlay: 'Shuffle play',
      like: 'Like set',
      duration: (time: string) => `Full play ${time} at 1×`,
      playNext: 'Play next',
      addToQueue: 'Add to queue',
      share: 'Share link',
      linkCopied: 'Link copied',
      copyUnavailable: 'Copy is not available here',
      rename: 'Rename set',
      delete: 'Delete set',
      deleted: 'Set deleted',
      own: 'Your set',
      ownEmpty: 'Add phrases from their details (⋮) or from the player.',
      addPhrases: 'Add phrases',
      addedNext: 'Plays next',
      addedEnd: 'Added to queue',
      notFound: 'This set isn’t available.',
      otherCourse: (language: string) => `This set is in the ${language} course.`,
      switchCourse: (language: string) => `Learn ${language}`,
    },
    phrase: {
      details: (text: string) => `Details for ${text}`,
      play: (text: string) => `Play ${text}`,
      playNext: 'Play next',
      addToQueue: 'Add to queue',
      like: 'Like',
      liked: 'Liked',
      likeLabel: 'Like phrase',
      addToSet: 'Add to set…',
      heard: (count: number) => `heard ${count}×`,
      notes: { mnemonic: 'Memory tip', grammar: 'Grammar', pronunciation: 'Sounds' },
      notesTitle: 'Notes',
      notesInEnglish: 'Notes are in English for now.',
      words: 'Tap a word for its meaning.',
      glossHint: 'Shows its meaning',
      edit: 'Edit phrase',
      delete: 'Delete phrase',
      deleted: 'Phrase deleted',
      removeFromSet: 'Remove from this set',
      removedFromSet: 'Removed from the set',
      moveUp: 'Move up in this set',
      moveDown: 'Move down in this set',
      yours: 'Your phrase',
      yoursShort: 'Yours',
      /** Before a phrase's IPA and respelling in its details. */
      sounds: 'Sounds:',
      /** Where the notes of a phrase of the learner's own come from (plan 105). */
      notesByDevice: (language: string) => `Loro worked these notes out on this device from ${language} spelling and grammar. No native speaker has checked them.`,
      writeNotes: 'Ask the writer for its notes',
      writingNotes: 'Writing notes…',
      notesFailed: 'The writer didn’t answer. Try again in a moment.',
      notesByAi: 'Its notes are written by AI. No native speaker has checked them.',
    },
    addToSet: {
      title: 'Add to set',
      newSet: 'New set…',
      added: (title: string) => `Added to ${title}`,
      already: (title: string) => `Already in ${title}`,
      alreadyHere: 'Already in this set',
      none: 'You haven’t made a set yet.',
    },
    pickPhrases: {
      search: 'Search phrases',
      add: 'Add',
      added: 'Added',
      done: 'Done',
    },
    createSet: {
      title: 'New set',
      renameTitle: 'Rename set',
      name: 'Name',
      create: 'Create',
      created: (title: string) => `Created ${title}`,
      taken: 'A set with this name already exists.',
    },
    addPhrase: {
      title: 'Add your phrase',
      target: (language: string) => `In ${language}`,
      native: (language: string) => `In ${language}`,
      hint: 'It plays with the device voice.',
      add: 'Add phrase',
      added: 'Phrase added',
      editTitle: 'Edit your phrase',
      edited: 'Phrase updated',
      duplicate: 'Already in your course:',
    },
    make: {
      /** The flow's title, and its entry in Library's "+" and under My sets. */
      title: 'Make a set',
      into: (set: string) => `Add to ${set}`,
      entryDetail: 'Suggested phrases from a topic, keywords or a text',
      intro: 'Say what you want to talk about. Loro suggests phrases: add the ones you want, skip the rest.',
      modesLabel: 'Suggest from',
      modes: { topic: 'Topic', keywords: 'Keywords', text: 'Text' } satisfies Record<SuggestMode, string>,
      field: { topic: 'A topic or a situation', keywords: 'A few words', text: 'Your text' } satisfies Record<SuggestMode, string>,
      placeholder: {
        topic: 'At the pharmacy',
        keywords: 'hotel, towel, breakfast',
        text: 'A message, a menu, a few lines you want to say',
      } satisfies Record<SuggestMode, string>,
      hintTopic: 'A place or a moment works best.',
      hintKeywords: 'Separate them with commas.',
      hintText: (language: string) => `In any language: the phrases will be in ${language}.`,
      tryTopics: 'Or pick one',
      suggest: 'Suggest phrases',
      writing: 'Writing phrases…',
      byAi: 'AI writes the suggestions. No native speaker has checked them.',
      byDevice: 'Suggestions come from the phrases on this device.',
      fellBack: 'The phrase writer didn’t answer, so these come from this device.',
      none: (input: string) => `No phrases for “${input}” yet.`,
      noneHint: 'Try other words, or write the phrase yourself.',
      writeOwn: 'Add your own phrase',
      progress: (position: number, total: number) => `${position} of ${total}`,
      addedCount: (count: number) => `${count} added`,
      cardLabel: (position: number, total: number) => `Suggestion ${position} of ${total}`,
      source: {
        course: (set: string) => `From ${set}`,
        mine: 'Your phrase',
        bank: 'Loro phrase bank',
        ai: 'Written by AI · not checked',
      },
      listen: (text: string) => `Listen to ${text}`,
      edit: 'Correct',
      editLabel: (text: string) => `Correct ${text}`,
      add: 'Add',
      skip: 'Skip',
      addLabel: (text: string) => `Add ${text}`,
      skipLabel: (text: string) => `Skip ${text}`,
      undoLabel: (text: string) => `Undo: ${text}`,
      swipeHint: 'Swipe right to add, left to skip.',
      keysHint: 'Keys: → add, ← skip.',
      announceAdded: (text: string) => `Added ${text}`,
      announceSkipped: (text: string) => `Skipped ${text}`,
      done: 'Done',
      endTitle: (count: number) => (count === 1 ? 'That’s the only suggestion' : `That’s all ${count} suggestions`),
      endAdded: (count: number) =>
        count === 0 ? 'You skipped them all.' : n(count, { one: `You added ${count} phrase.`, other: `You added ${count} phrases.` }),
      more: 'More suggestions',
      noMore: 'No more suggestions for this.',
      another: 'Try something else',
      review: (count: number) => n(count, { one: `Save ${count} phrase`, other: `Save ${count} phrases` }),
      saveTitle: 'Save your set',
      keptHeading: (count: number) => n(count, { one: `${count} phrase to save`, other: `${count} phrases to save` }),
      remove: (text: string) => `Leave out ${text}`,
      addInto: (count: number, set: string) => n(count, { one: `Add ${count} phrase to ${set}`, other: `Add ${count} phrases to ${set}` }),
      addedInto: (count: number, set: string) => n(count, { one: `${count} phrase added to ${set}`, other: `${count} phrases added to ${set}` }),
      backToDeck: 'Back to the suggestions',
      unsaved: (count: number) => n(count, { one: `${count} added phrase wasn’t saved`, other: `${count} added phrases weren’t saved` }),
      reopen: 'Reopen',
      fromExplore: (query: string) => `Suggest phrases about “${query}”`,
      fromSet: 'Suggest phrases',
      originAi: 'Written by AI. No native speaker has checked it.',
      originBank: 'From Loro’s phrase bank.',
      defaultTitleText: 'From my text',
    },
    player: {
      dialog: 'Now playing',
      close: 'Close player',
      openQueue: 'Open queue',
      summary: 'Session summary',
      position: (i: number, total: number) => `${i} of ${total}`,
      /** When the queue holds more than its set (continue mode added the next one). */
      positionInQueue: (i: number, total: number) => `${i} of ${total} in the queue`,
      hidden: (language: string) => `${language} hidden until you hear it`,
      steps: 'Steps',
      yourTurn: 'Your turn',
      instruction: {
        native: (language: string) => `Listen in ${language}`,
        pause: (language: string) => `Your turn — say it out loud in ${language}`,
        target: (language: string) => `Hear it in ${language}`,
        rate: 'Rate it, or wait to go on',
      },
      paused: 'Paused',
      coach: 'Say it now, before you hear it. Nothing is recorded — you’ll rate how it went.',
      repetition: (r: number, total: number) => `Repetition ${r} of ${total}`,
      howDidItGo: 'Did you remember it?',
      /** Before the learner's first turn at the phrase in this play. */
      rateAfterTurn: 'Rate once you’ve said it',
      /** Under each grade: when the phrase comes back if rated so. */
      nextIn: (interval: string) => `in ${interval}`,
      rated: (grade: string, when: string) => `Rated ${grade} — back ${when}`,
      /** After “Rated …” when a Missed or Hard phrase also comes back later in this queue. */
      requeued: '· again in this queue',
      undoFor: (time: string) => `Undo · ${time}`,
      undoLabel: (time: string) => `Undo rating (${time} left)`,
      previous: 'Previous phrase',
      next: 'Next phrase',
      repeats: {
        auto: 'Repetitions: automatic (3 while new or shaky, 1 once it sticks)',
        one: 'Repetitions: 1',
        three: 'Repetitions: 3',
      },
      playMode: {
        repeat: 'At the end: play the queue again',
        continue: 'At the end: continue with the next phrases',
      } satisfies Record<PlayMode, string>,
      /** Visible words under the transport's two setting buttons. */
      captions: { reps: 'reps', again: 'Again', continue: 'Continue', auto: 'Auto' },
      repeatsToast: {
        auto: 'Each phrase plays 3× while new, 1× once it sticks',
        one: 'Each phrase plays once',
        three: 'Each phrase plays 3 times',
      },
      playModeToast: {
        repeat: 'At the end, the queue starts again',
        continue: 'At the end, new phrases follow',
      } satisfies Record<PlayMode, string>,
      speed: 'Speed',
      speedIs: (speed: number) => `Speed: ${speed}×`,
      keys: 'Keys: Space play or pause · ← → previous, next · 1 2 3 rate',
      audioError: (language: string) =>
        `This device has no ${language} voice, so the phrase can’t play. Add one in your system’s speech settings, then press Play.`,
      showText: (language: string) => `Show the ${language} text`,
      /** The panel a queue with a natural end stops on (a review, the demo, a Library list). */
      end: {
        reviewTitle: 'Review done',
        listTitle: 'All played',
        /** A review or list ended with nothing rated: not "done", just heard to the end. */
        playedThrough: 'Played through',
        rated: (count: number) => `${count} rated`,
        nextReview: (when: string) => `Next review ${when}`,
        nothingDue: 'Nothing due yet',
        continueSet: (title: string) => `Continue ${title}`,
        playAgain: 'Play again',
        demoTitle: 'That’s the loop',
        demoBody: 'Hear it, say it out loud, hear it, rate it. Ready for a whole set?',
        startSet: (title: string) => `Start ${title}`,
        notNow: 'Not now',
      },
      /** The mini-player during the rating hold: the grades are in the full player. */
      miniRate: 'Tap to rate',
      noVoice: 'No voice for this language',
      audioSilent: 'Speech stopped before the phrase played. Press Play to try again.',
      silent: 'Speech stopped — press Play',
      voice: (name: string) => `Voice: ${name}`,
      changeVoice: (name: string) => `Voice: ${name}. Change voice`,
    },
    toast: {
      updateReady: 'A new version of Loro is ready',
      reload: 'Reload',
      dismiss: 'Dismiss message',
      learned: (points: number) => `Learned · +${points}`,
      passComplete: 'Queue played through',
      nextSet: (title: string) => `Next: ${title}`,
      removed: 'Removed from queue',
      cleared: 'Queue cleared',
      saved: (title: string) => `Saved as ${title}`,
      storageFull: 'This device’s storage for Loro is full, so new progress isn’t being saved.',
      storageUnavailable: 'This browser isn’t letting Loro save progress on this device.',
      outdated: 'A newer version of Loro is open in another tab. Reload to keep saving here.',
    },
    queue: {
      title: 'Queue',
      back: 'Back to player',
      left: (count: number) => `${count} left`,
      nowPlaying: 'Now playing',
      upNext: (count: number) => `Up next · ${count}`,
      nothing: 'Nothing queued after this phrase.',
      hint: 'Swipe right to play now, left to remove. Drag the handle to reorder, or tap it for options.',
      handleHint: 'Enter for options; arrow up or down to move, Delete to remove.',
      moveUp: 'Move up',
      moveDown: 'Move down',
      removeFromQueue: 'Remove from queue',
      moved: (position: number, total: number) => `Moved to position ${position} of ${total}`,
      playNow: (text: string) => `Play ${text} now`,
      move: (text: string) => `Move ${text}`,
      swipePlay: 'Play now',
      swipeRemove: 'Remove',
      previously: 'Previously played',
      /** On an up-next phrase already played in this queue (a Missed or Hard one coming back). */
      again: 'Again',
      justNow: 'just now',
      playNext: (text: string) => `Play ${text} next`,
      clear: 'Clear queue',
      saveAsSet: 'Save as set',
      shuffle: 'Shuffle up next',
      defaultSetName: 'My queue',
    },
    library: {
      learned: 'Learned',
      learnedNote: (days: number, recalls: number) => `Recall lasts ${days}+ days, after ${recalls}+ recalls`,
      recall: 'Recall now',
      recallNote: (rated: number) => n(rated, { one: `Average of ${rated} rated phrase`, other: `Average of ${rated} rated phrases` }),
      recallNone: 'Rate a phrase first',
      started: 'Started',
      startedNote: 'Heard or rated at least once',
      phrasesSegment: 'Phrases',
      setsSegment: 'Sets',
      filters: {
        liked: 'Liked',
        mine: 'Mine',
        due: 'Due',
        learning: 'Learning',
        missed: 'Missed recently',
        learned: 'Learned',
        ownSets: 'My sets',
        likedSets: 'Liked sets',
      },
      empty: {
        liked: 'Tap the heart on a phrase to keep it here.',
        mine: 'Add a phrase of your own and it plays like any other.',
        due: 'Nothing is due right now.',
        learning: 'Phrases you have heard or rated but not yet learned show here.',
        missed: 'Phrases rated Missed in the last week show here.',
        learned: (days: number, recalls: number) =>
          `A phrase is learned once recall is expected to last ${days} days or more, after at least ${recalls} successful recalls.`,
        ownSets: 'Make a set to group phrases your way.',
        likedSets: 'Tap the heart on a set to keep it here.',
      },
      playAll: (count: number) => `Play all (${count})`,
      addPhrase: 'Add your phrase',
      newSet: 'New set',
      recallChart: 'Predicted recall now',
      recallBucket: (from: number, to: number) => `${from}–${to}%`,
      recallBelow: (to: number) => `under ${to}%`,
      recallChartEmpty: 'Rate a phrase to see this.',
      bucketCount: (label: string, count: number) => `${label}: ${n(count, { one: `${count} phrase`, other: `${count} phrases` })}`,
      weeklyChart: 'Learned per week',
      weekOf: (date: string, count: number) => `Week of ${date}: ${count} learned`,
      progress: 'Progress',
    },
    settings: {
      title: 'Settings',
      switched: (language: string, queueCleared: boolean) => `Now learning ${language}${queueCleared ? '. The queue was cleared' : ''}`,
      profile: 'Profile',
      name: 'Name',
      native: 'I speak',
      course: 'I’m learning',
      courseNote: 'Progress is kept for each pair of languages. Switching back brings it back.',
      accessibility: 'Screen reader',
      voices: 'Voices',
      voiceAuto: (name: string) => `Automatic (${name})`,
      announceEveryStep: 'Announce every step',
      announceHint: 'Off: only “Your turn” and the reveal are announced.',
      listening: 'Listening',
      pauseLength: 'Time to say it',
      pause: { standard: 'Standard', longer: 'Longer' } satisfies Record<PauseLength, string>,
      pauseHint: 'Longer gives you about twice the phrase’s length.',
    },
    onboarding: {
      step: (i: number, total: number) => `Step ${i} of ${total}`,
      welcome: 'Learn a language by the phrase: hear it, say it, hear it.',
      name: 'What should we call you?',
      namePlaceholder: 'Your name',
      native: 'Which language do you speak?',
      course: 'Which language are you learning?',
      voices: 'Checking voices',
      voicesChecking: 'Looking for voices on this device…',
      voiceOk: (language: string, name: string) => `${language}: ${name}`,
      voiceMissing: (language: string) => `${language}: no voice on this device`,
      voiceHint: 'Add the missing voice in your system’s speech settings. You can go on, but those phrases won’t play until then.',
      test: (language: string) => `Test ${language}`,
      testShort: 'Test',
      loop: 'How it works',
      loopSteps: (native: string, target: string) => [
        `Hear the phrase in ${native}.`,
        `Say it out loud in ${target} while it’s quiet.`,
        `Hear it in ${target}.`,
        'Rate how it went: Missed, Hard or Easy. You can change it for five minutes.',
      ],
      next: 'Continue',
      start: 'Start with one phrase',
      skip: 'Start without the demo',
    },
    summary: {
      title: 'This session',
      phrases: 'Phrases',
      repetitions: 'Repetitions',
      ratings: 'Ratings',
      pending: (count: number) => `${count} still changeable: their points and next review count once the five minutes are up`,
      points: 'Points earned',
      passes: 'Times through the queue',
      nextDue: 'Next review',
      nothingDue: 'Nothing scheduled yet',
      none: 'Nothing played in this session yet.',
    },
    connection: {
      loading: 'Getting your course…',
      offlineTitle: 'Loro can’t reach its server',
      offlineBody: 'Your course downloads once, then plays offline. Check the connection and try again.',
      retry: 'Try again',
    },
    account: {
      title: 'Account',
      signIn: 'Sign in',
      signInTitle: 'Sign in to Loro',
      signInBody: 'Make phrase sets, songs and covers with AI, keep them in your account, and share them. Your progress on this device stays as it is.',
      email: 'Email',
      emailPlaceholder: 'you@example.com',
      sendCode: 'Email me a code',
      sending: 'Sending…',
      codeTitle: 'Check your email',
      codeBody: (email: string) => `We sent a six-digit code to ${email}. It works for 10 minutes.`,
      code: 'Six-digit code',
      verify: 'Sign in',
      verifying: 'Signing in…',
      resend: 'Send a new code',
      changeEmail: 'Use another email',
      signedInAs: (email: string) => `Signed in as ${email}`,
      signOut: 'Sign out',
      deleteData: 'Delete my Loro data',
      deleteDataConfirm: 'Delete your sets, albums, songs, covers and the progress kept in your account? Anyone you shared with loses them too. The progress on this device stays. This can’t be undone.',
      deletedData: 'Your Loro data is deleted.',
      synced: 'Your progress is kept in your account and follows you to other devices.',
      syncFailed: 'Your progress couldn’t be saved to your account just now. It is safe on this device and will be saved when the connection is back.',
      signedOut: 'Signed out. Your progress on this device is kept.',
      welcome: 'Signed in',
      displayName: 'Name on what you share',
      displayNameHint: 'Shown as “by …” on sets and albums you make public. Leave it empty to show “by a learner”.',
      displayNameSaved: 'Name saved',
      notNow: 'Not now',
      google: 'Continue with Google',
      needed: 'Sign in to make sets, songs and covers with AI and to share them.',
      errors: {
        badEmail: 'That doesn’t look like an email address.',
        badCode: 'That code isn’t right, or it has expired.',
        tooMany: 'Too many tries. Wait a few minutes, then try again.',
        unavailable: 'Signing in by email isn’t set up on this server.',
        googleUnavailable: 'Signing in with Google isn’t set up for this address of Loro.',
        offline: 'Loro can’t reach its server. Check the connection.',
        generic: 'Something went wrong. Try again.',
        full: 'Your account holds as many of these as it can. Delete one to make room.',
        invalid: 'That couldn’t be saved: something in it is too long or missing.',
      },
      today: 'Today’s allowance',
      usage: {
        phrases: (left: number, limit: number) => `Phrase decks: ${left} of ${limit} left`,
        cover: (left: number, limit: number) => `Covers: ${left} of ${limit} left`,
        song: (left: number, limit: number) => `Songs: ${left} of ${limit} left`,
      },
      kept: (sets: number, albums: number) => `${n(sets, { one: `${sets} set`, other: `${sets} sets` })} and ${n(albums, { one: `${albums} album`, other: `${albums} albums` })} in your account`,
      resets: (time: string) => `Resets at ${time}`,
      spent: (time: string) => `Today’s allowance is used. It resets at ${time}.`,
      writers: 'Who makes it on this server',
      writer: {
        claude: 'Claude (AI)',
        bank: 'Loro’s phrase bank (no AI writer set up)',
        pattern: 'Drawn patterns (no AI writer set up)',
        phrases: 'Your phrases as lyrics (no AI writer set up)',
        elevenlabs: 'Sung by ElevenLabs Music',
        demo: 'Demo sound (no music provider set up)',
      },
      writerKind: { phrases: 'Phrases', cover: 'Covers', lyrics: 'Lyrics', music: 'Sound' },
    },
    tabs: {
      home: 'Home',
      phrases: 'Phrases',
      music: 'Music',
      create: 'Create',
      library: 'Library',
    },
    share: {
      visibility: 'Who can see it',
      private: 'Only you',
      privateDetail: 'In your account, on your devices',
      link: 'Anyone with the link',
      linkDetail: 'Not listed; the link opens it',
      public: 'Everyone',
      publicDetail: 'Listed in Community for your course',
      share: 'Share',
      shareMessage: (title: string, url: string) => `${title} on Loro: ${url}`,
      copied: 'Link copied',
      makeShareable: 'Only you can see it. Choose who can before sharing.',
      by: (name: string) => `by ${name}`,
      byLearner: 'by a learner',
      yours: 'Yours',
      save: 'Save to library',
      saved: 'In your library',
      unsave: 'Remove from library',
      savedToast: 'Saved to your library',
      unsavedToast: 'Removed from your library',
      delete: 'Delete',
      deleteSetConfirm: (title: string) => `Delete “${title}” from your account? Anyone you shared it with loses it too. Your progress on its phrases is kept.`,
      deleteAlbumConfirm: (title: string) => `Delete the album “${title}” and its songs?`,
      deleted: 'Deleted',
      cover: 'New cover',
      coverMaking: 'Drawing a cover…',
      coverBy: { claude: 'Cover by Claude', pattern: 'Drawn pattern' },
      changed: 'Saved',
      notFound: 'This link doesn’t open anything. It may have been made private or deleted.',
      opening: 'Opening…',
      report: 'Report',
      reported: 'Reported. Thank you.',
      reason: { offensive: 'Offensive or hurtful', wrong: 'Wrong language or mistakes', spam: 'Spam or advertising', other: 'Something else' },
    },
    community: {
      title: 'Community',
      sets: 'Shared sets',
      albums: 'Shared albums',
      emptySets: 'No one has shared a set in this course yet. Make one and choose Everyone.',
      emptyAlbums: 'No one has shared an album in this course yet.',
      search: 'Search shared sets',
      offline: 'Community needs a connection.',
    },
    phrasesTab: {
      title: 'Phrases',
      course: 'Loro’s course',
      yourSets: 'Your sets',
      savedSets: 'Saved sets',
      makeSet: 'Make a set with AI',
      signInToMake: 'Sign in to make sets with AI',
    },
    music: {
      title: 'Music',
      loro: 'From Loro',
      yours: 'Your albums',
      saved: 'Saved albums',
      songs: (count: number) => n(count, { one: `${count} song`, other: `${count} songs` }),
      empty: 'No albums in this course yet.',
      noSongs: 'No songs here yet.',
      loroAlbum: 'Every Loro set of this course, sung.',
      makeSong: 'Make a song',
      renameAlbum: 'Rename album',
      album: 'Album',
      playAlbum: 'Play album',
      playSong: (title: string) => `Play ${title}`,
      demoSound: 'Demo sound',
      spokenDemo: 'Spoken demo',
      spokenNote: 'The lines are spoken by Loro’s voice over an instrumental the server made; they light up as they play. Songs are sung once a music provider is set up.',
      demoNote: 'The server made this instrumental; the lyrics light up as it plays. Songs are sung once a music provider is set up.',
      sung: 'Sung',
      lyrics: 'Lyrics',
      lyricsBy: { claude: 'Lyrics by Claude', phrases: 'Lyrics: the set’s phrases' },
      meanings: 'Meanings',
      showMeanings: 'Show meanings',
      hideMeanings: 'Hide meanings',
      section: { verse: 'Verse', chorus: 'Chorus', bridge: 'Bridge' },
      rendering: 'Making the song…',
      renderingNote: 'It takes a moment. You can leave this screen; the song keeps being made.',
      failed: 'This song couldn’t be made.',
      nowPlaying: 'Now playing',
      previous: 'Previous song',
      next: 'Next song',
      openSet: 'Open the set',
      fromSet: (title: string) => `From the set “${title}”`,
      loadFailed: 'The album couldn’t be loaded.',
      style: {
        modern_pop: 'Pop',
        acoustic_folk: 'Folk',
        gentle_ballad: 'Ballad',
        upbeat_kids: 'Sing-along',
      },
    },
    create: {
      title: 'Create',
      intro: 'Make your own phrase sets, songs and covers with AI. What you make is yours: keep it private, share a link, or publish it for everyone.',
      phrasesTitle: 'A set of phrases',
      phrasesBody: 'Name a topic or paste a text. AI writes phrases with their notes; keep the ones you want.',
      songTitle: 'A song from a set',
      songBody: 'Your phrases, sung. Hear them in a song and read along.',
      coverTitle: 'Covers',
      coverBody: 'Every set and album you make can get its own drawn cover.',
      coverNothing: 'Make a set or a song first; then draw it a cover here.',
      left: (count: number) => n(count, { one: `${count} left today`, other: `${count} left today` }),
      none: 'None left today',
      pickSet: 'Which set?',
      pickSetEmpty: 'No sets in this course yet.',
      pickStyle: 'Style',
      pickAlbum: 'Album',
      newAlbum: 'A new album',
      songTitleLabel: 'Song title',
      makeSong: 'Make the song',
      songStarted: 'The song is being made',
      saveToAccount: 'Save to your account',
      savedToAccount: 'Saved to your account',
      setTitle: 'Title',
      setDescription: 'What it’s for (optional)',
      withCover: 'Draw a cover for it',
      signedOutSave: 'Saved on this device. Sign in to keep it in your account and share it.',
      from: { claude: 'Written by Claude', bank: 'From Loro’s phrase bank' },
      bankOnly: 'No AI writer is set up on this server, so these come from Loro’s phrase bank.',
      noMatch: 'The phrase bank has nothing on that. Try one of these topics:',
    },
    error: {
      title: 'Something went wrong',
      body: 'Reloading usually fixes it, and your progress is kept. If it keeps happening, the progress saved on this device may not fit this version: copy it first if you want to keep it, then reset to start from zero on this device.',
      reload: 'Reload',
      part: 'This part of the screen couldn’t be shown. Your progress is safe.',
      copy: 'Copy progress JSON',
      copied: 'Copied',
      reset: 'Reset progress',
    },
  };
}

export type Copy = ReturnType<typeof makeEn>;
