// Polish UI copy. Awaiting native review (see content/meta.json).
import type { Copy, Plural } from './en';

export function makePl(n: Plural): Copy {
  // "hiszpański" → "po hiszpańsku": the adverb a sentence needs ("powiedz na głos po hiszpańsku").
  // Other names fall back to a phrase that needs no declension.
  const adverb = (language: string) => (language.endsWith('ski') ? `po ${language.slice(0, -1)}u` : `w języku: ${language}`);
  // Polish counts: 1 → one, 2–4 (and 22–24…) → few, 0, 5–21… → many, fractions → other.
  const phrases = (c: number) => n(c, { one: `${c} fraza`, few: `${c} frazy`, many: `${c} fraz`, other: `${c} frazy` });
  const sets = (c: number) => n(c, { one: `${c} zestaw`, few: `${c} zestawy`, many: `${c} zestawów`, other: `${c} zestawu` });
  const points = (c: number) => n(c, { one: `${c} punkt`, few: `${c} punkty`, many: `${c} punktów`, other: `${c} punktu` });
  const songs = (c: number) => n(c, { one: `${c} piosenka`, few: `${c} piosenki`, many: `${c} piosenek`, other: `${c} piosenki` });
  const albums = (c: number) => n(c, { one: `${c} album`, few: `${c} albumy`, many: `${c} albumów`, other: `${c} albumu` });
  return {
    locale: 'pl-PL',
    common: {
      close: 'Zamknij',
      back: 'Wstecz',
      cancel: 'Anuluj',
      charsLeft: (c) => n(c, { one: `Został ${c} znak`, few: `Zostały ${c} znaki`, many: `Zostało ${c} znaków`, other: `Zostało ${c} znaku` }),
      save: 'Zapisz',
      undo: 'Cofnij',
      play: 'Słuchaj',
      pause: 'Pauza',
      delete: 'Usuń',
      moreOptions: 'Więcej',
      phrases,
      sets,
      points,
      level: (level) => level,
      grade: { missed: 'Nie pamiętam', hard: 'Trudno', easy: 'Łatwo' },
      register: { formal: 'Formalnie', informal: 'Nieformalnie', neutral: 'Neutralnie' },
      tag: {
        politeness: 'Uprzejmość',
        question: 'Pytania',
        request: 'Prośby',
        numbers: 'Liczby',
        food: 'Jedzenie i picie',
        directions: 'Droga',
        social: 'Towarzyskie',
      },
      fullPlay: (time) => `${time} przy 1×`,
    },
    nav: {
      main: 'Menu główne',
      home: 'Start',
      explore: 'Odkrywaj',
      library: 'Biblioteka',
      settings: (name) => (name ? `${name}: ustawienia` : 'Ustawienia'),
      learning: (language) => `Uczysz się: ${language}`,
      add: 'Dodaj frazę lub zestaw',
      addSheet: 'Dodaj',
      points,
      pointsShort: () => 'pkt',
    },
    status: {
      new: 'Nowa',
      listenedNotRated: 'Wysłuchana, bez oceny',
      due: 'Czas powtórzyć',
      learned: (pct) => `Wyuczona · pamięć ${pct}%`,
      learning: (pct, when) => `Pamięć ${pct}% · wróci ${when}`,
      set: { new: 'Nowy', 'in-progress': 'W trakcie', learned: 'Wszystko wyuczone' },
    },
    home: {
      firstRun: 'Posłuchaj frazy i powiedz ją na głos, zanim usłyszysz ją jeszcze raz.',
      learned: 'Wyuczone',
      started: 'Rozpoczęte',
      today: (heard, rated) =>
        `Dziś: ${n(heard, { one: `${heard} usłyszana fraza`, few: `${heard} usłyszane frazy`, many: `${heard} usłyszanych fraz`, other: `${heard} usłyszanej frazy` })} · ocenione:\u00a0${rated}`,
      reviewTitle: 'Powtórka',
      reviewBody: (due) =>
        n(due, { one: `${due} fraza czeka na powtórkę`, few: `${due} frazy czekają na powtórkę`, many: `${due} fraz czeka na powtórkę`, other: `${due} frazy czeka na powtórkę` }),
      reviewCapped: (shown) => `W tej sesji: ${shown} najdawniejszych.`,
      playPhrases: (c) => `Słuchaj: ${phrases(c)}`,
      duration: (time) => `${time} przy 1×`,
      startTitle: 'Od czego zacząć',
      continueTitle: 'Kontynuuj',
      nextTitle: 'Następny zestaw',
      next: (c, when) => `Dalej: ${phrases(c)} ${when}`,
      nextAfter: (c, when) => `Potem: jeszcze ${phrases(c)} ${when}`,
      jumpBackIn: 'Wróć do nauki',
      history: 'Historia',
      notStarted: 'Jeszcze nierozpoczęte',
      demoTitle: 'Wypróbuj pętlę',
      demoBody: 'Jedna fraza: usłyszeć, powiedzieć, usłyszeć.',
      demoButton: 'Posłuchaj jednej frazy',
      courseDoneTitle: 'Wszystkie frazy tego kursu są wyuczone',
      courseDoneBody: 'Powtórki wrócą, gdy nadejdzie ich czas. Tymczasem dodaj własne frazy albo spróbuj innego kursu.',
      addOwn: 'Dodaj własną frazę',
      otherCourse: 'Wypróbuj inny kurs',
    },
    history: {
      title: 'Historia',
      empty: 'Nic jeszcze nie odtworzono.',
      mixed: 'Kolejka mieszana',
      run: (p, pts) => `${phrases(p)} · +${pts} pkt`,
    },
    explore: {
      search: 'Frazy, notatki, tematy',
      searchShort: 'Szukaj',
      topics: 'Tematy',
      levels: 'Poziomy',
      tags: 'Tagi',
      allSets: 'Wszystkie zestawy',
      sets,
      phrases,
      noPhrases: (q) => `Brak fraz pasujących do „${q}”.`,
      noPhrasesFiltered: 'Brak fraz pasujących do tych filtrów.',
      noSets: 'Brak pasujących zestawów.',
      addAsOwn: (q) => `Dodaj „${q}” jako własną frazę`,
      removeFilter: (label) => `Usuń filtr: ${label}`,
      clearFilters: 'Wyczyść filtry',
      quickPlay: (title) => `Słuchaj: ${title}`,
      searchedSets: 'Zestawy',
    },
    set: {
      phrasesHeading: 'Frazy',
      summary: (total, learned, due) => `${phrases(total)} · wyuczone: ${learned}${due > 0 ? ` · do powtórki: ${due}` : ''}`,
      sort: { set: 'Jak w zestawie', az: 'A–Z', due: 'Najpierw do powtórki', weakest: 'Najpierw najsłabsze' },
      sortTitle: 'Sortowanie fraz',
      playsIn: (order) => `Kolejność: ${order}`,
      playAll: (title) => `Słuchaj: ${title}`,
      pauseAll: (title) => `Pauza: ${title}`,
      resume: (title) => `Wznów: ${title}`,
      pausedAt: (position, total) => `Wstrzymano: ${position} z ${total}`,
      playDueNew: (c) => `Tylko nowe i do powtórki (${c})`,
      pauseDueNew: 'Pauza: nowe i do powtórki',
      shufflePlay: 'Losowo',
      like: 'Polub zestaw',
      duration: (time) => `Całość ${time} przy 1×`,
      playNext: 'Odtwórz jako następną',
      addToQueue: 'Dodaj do kolejki',
      share: 'Udostępnij link',
      linkCopied: 'Link skopiowany',
      copyUnavailable: 'Kopiowanie jest tu niedostępne',
      own: 'Twój zestaw',
      ownEmpty: 'Dodawaj frazy z ich szczegółów (⋮) albo z odtwarzacza.',
      addPhrases: 'Dodaj frazy',
      addedNext: 'Zagra jako następna',
      addedEnd: 'Dodano do kolejki',
      notFound: 'Ten zestaw jest niedostępny.',
      otherCourse: (language) => `Ten zestaw jest w kursie: ${language}.`,
      switchCourse: (language) => `Ucz się: ${language}`,
    },
    phrase: {
      details: (text) => `Szczegóły: ${text}`,
      play: (text) => `Słuchaj: ${text}`,
      playNext: 'Odtwórz jako następną',
      addToQueue: 'Dodaj do kolejki',
      like: 'Polub',
      liked: 'Polubiona',
      likeLabel: 'Polub frazę',
      addToSet: 'Dodaj do zestawu…',
      heard: (c) => `usłyszana ${c}×`,
      notes: { mnemonic: 'Skojarzenie', grammar: 'Gramatyka', pronunciation: 'Dźwięki' },
      notesTitle: 'Notatki',
      notesInEnglish: 'Notatki są na razie po angielsku.',
      noteAgain: { mnemonic: 'Nowe skojarzenie', grammar: 'Wyjaśnij inaczej' },
      noteWriting: (language: string) => `Piszę nowe — język: ${language}…`,
      noteEarlier: (count: number) => `Wcześniejsze (${count})`,
      noteHideEarlier: 'Ukryj wcześniejsze',
      words: 'Dotknij słowa, żeby zobaczyć jego znaczenie.',
      glossHint: 'Pokazuje znaczenie',
      edit: 'Edytuj frazę',
      delete: 'Usuń frazę',
      deleted: 'Fraza usunięta',
      removeFromSet: 'Usuń z tego zestawu',
      removedFromSet: 'Usunięto z zestawu',
      moveUp: 'Wyżej w tym zestawie',
      moveDown: 'Niżej w tym zestawie',
      yours: 'Twoja fraza',
      yoursShort: 'Twoja',
      sounds: 'Wymowa:',
      notesByRules: (language: string) => `Loro przygotowało te notatki według własnych reguł pisowni i gramatyki: ${language}. Native speaker ich nie sprawdzał.`,
      deleteConfirm: (target: string) => `Usunąć „${target}” ze wszystkich Twoich zestawów? Postępy z nią znikną razem z nią.`,
      removeDeletes: (target: string) => `W żadnym innym Twoim zestawie nie ma „${target}”, więc usunięcie jej stąd usuwa ją całkiem, razem z postępami.`,
      writeNotes: 'Poproś autora o notatki',
      writingNotes: 'Piszę notatki…',
      notesFailed: 'Autor nie odpowiedział. Spróbuj ponownie za chwilę.',
      notesByAi: 'Notatki do niej napisała sztuczna inteligencja. Native speaker ich nie sprawdzał.',
    },
    addToSet: {
      title: 'Dodaj do zestawu',
      newSet: 'Nowy zestaw…',
      added: (title) => `Dodano do „${title}”`,
      already: (title) => `Już jest w „${title}”`,
      alreadyHere: 'Już jest w tym zestawie',
      none: 'Nie masz jeszcze własnych zestawów.',
    },
    pickPhrases: {
      search: 'Szukaj fraz',
      add: 'Dodaj',
      added: 'Dodana',
      done: 'Gotowe',
    },
    createSet: {
      title: 'Nowy zestaw',
      renameTitle: 'Zmień nazwę zestawu',
      editTitle: 'Nazwa i opis',
      description: 'Opis (opcjonalnie)',
      descriptionHint: 'Widoczny tam, gdzie inni znajdą zestaw.',
      name: 'Nazwa',
      create: 'Utwórz',
      created: (title) => `Utworzono „${title}”`,
      taken: 'Zestaw o takiej nazwie już istnieje.',
    },
    addPhrase: {
      title: 'Dodaj własną frazę',
      target: (language) => `W języku: ${language}`,
      native: (language) => `W języku: ${language}`,
      hint: 'Głos Loro wypowie ją, gdy tylko ją dodasz.',
      add: 'Dodaj frazę',
      added: 'Fraza dodana',
      editTitle: 'Edytuj swoją frazę',
      edited: 'Fraza zaktualizowana',
      duplicate: 'Już jest w Twoim kursie:',
    },
    make: {
      title: 'Utwórz zestaw',
      into: (set) => `Dodaj do „${set}”`,
      entryDetail: 'Propozycje fraz na podstawie tematu, słów lub tekstu',
      intro: 'O czym chcesz mówić?',
      modesLabel: 'Proponuj na podstawie',
      modes: { topic: 'Temat', keywords: 'Słowa', text: 'Tekst' },
      field: { topic: 'Temat lub sytuacja', keywords: 'Kilka słów', text: 'Twój tekst' },
      placeholder: {
        topic: 'W aptece',
        keywords: 'hotel, ręcznik, śniadanie',
        text: 'Wiadomość, menu, kilka zdań, które chcesz umieć powiedzieć',
      },
      hintTopic: 'Najlepiej sprawdza się miejsce albo chwila.',
      hintKeywords: 'Oddziel je przecinkami.',
      hintText: (language) => `W dowolnym języku: frazy będą ${adverb(language)}.`,
      tryTopics: 'Albo wybierz jeden',
      suggest: 'Zaproponuj frazy',
      writing: 'Piszę frazy…',
      byAi: 'Propozycje pisze sztuczna inteligencja. Native speaker ich nie sprawdzał.',
      byBank: 'Z banku fraz Loro: ten serwer nie ma skonfigurowanej AI.',
      none: (input) => `Na razie brak fraz dla „${input}”.`,
      noneHint: 'Spróbuj innych słów albo napisz frazę samodzielnie.',
      writeOwn: 'Dodaj własną frazę',
      progress: (position, total) => `${position} z ${total}`,
      addedCount: (count) => `Dodano: ${count}`,
      cardLabel: (position, total) => `Propozycja ${position} z ${total}`,
      source: {
        course: (set) => `Z „${set}”`,
        mine: 'Twoja fraza',
        bank: 'Frazy Loro',
        ai: 'Napisane przez AI · niesprawdzone',
      },
      listen: (text) => `Posłuchaj: ${text}`,
      edit: 'Popraw',
      editLabel: (text) => `Popraw: ${text}`,
      add: 'Dodaj',
      skip: 'Pomiń',
      addLabel: (text) => `Dodaj: ${text}`,
      skipLabel: (text) => `Pomiń: ${text}`,
      undoLabel: (text) => `Cofnij: ${text}`,
      swipeHint: 'Przesuń w prawo, żeby dodać, w lewo, żeby pominąć.',
      keysHint: 'Klawisze: → dodaj, ← pomiń.',
      announceAdded: (text) => `Dodano: ${text}`,
      announceSkipped: (text) => `Pominięto: ${text}`,
      done: 'Gotowe',
      endTitle: (count) => (count === 1 ? 'To była jedyna propozycja' : `To już wszystkie propozycje: ${count}`),
      endAdded: (count) => (count === 0 ? 'Pominięto wszystkie.' : `Dodane frazy: ${count}.`),
      more: 'Więcej propozycji',
      noMore: 'Nie ma więcej propozycji na ten temat.',
      another: 'Spróbuj czegoś innego',
      review: (count) => n(count, { one: `Zapisz ${count} frazę`, few: `Zapisz ${count} frazy`, many: `Zapisz ${count} fraz`, other: `Zapisz ${count} frazy` }),
      saveTitle: 'Zapisz zestaw',
      keptHeading: (count) => `Fraz do zapisania: ${count}`,
      remove: (text) => `Pomiń: ${text}`,
      addInto: (count, set) => `Dodaj do „${set}”: ${phrases(count)}`,
      addedInto: (count, set) => `Dodano do „${set}”: ${phrases(count)}`,
      backToDeck: 'Wróć do propozycji',
      unsaved: (count) => `Niezapisane: ${phrases(count)}`,
      reopen: 'Otwórz ponownie',
      fromExplore: (query) => `Zaproponuj frazy o „${query}”`,
      fromSet: 'Zaproponuj frazy',
      originAi: 'Napisane przez AI. Native speaker tego nie sprawdzał.',
      originBank: 'Z fraz Loro.',
      defaultTitleText: 'Z mojego tekstu',
    },
    player: {
      dialog: 'Teraz gra',
      close: 'Zamknij odtwarzacz',
      openQueue: 'Otwórz kolejkę',
      summary: 'Podsumowanie sesji',
      position: (i, total) => `${i} z ${total}`,
      positionInQueue: (i, total) => `${i} z ${total} w kolejce`,
      hidden: () => 'Fraza jest ukryta, dopóki jej nie usłyszysz',
      steps: 'Kroki',
      yourTurn: 'Twoja kolej',
      again: 'Jeszcze raz',
      instruction: {
        native: (language) => `Posłuchaj: ${language}`,
        pause: (language) => `Twoja kolej — powiedz na głos ${adverb(language)}`,
        target: (language) => `Posłuchaj: ${language}`,
        echo: (language) => `Powtórz ${adverb(language)}, tak jak brzmiała fraza`,
        rate: 'Oceń albo poczekaj',
      },
      paused: 'Pauza',
      coach: 'Powiedz ją teraz, zanim ją usłyszysz. Nic nie jest nagrywane — potem ocenisz, jak poszło.',
      repetition: (r, total) => `Powtórzenie ${r} z ${total}`,
      howDidItGo: 'Udało się przypomnieć?',
      rateAfterTurn: 'Oceń, gdy ją powiesz',
      nextIn: (interval) => `za ${interval}`,
      rated: (grade, when) => `Ocena „${grade}” — wróci ${when}`,
      scheduled: 'Powtórka zaplanowana',
      backLater: 'Wróci na końcu kolejki',
      ratedPrevious: (grade) => `Poprzednia fraza: „${grade}”`,
      ratedAs: (grade) => `Ocena „${grade}”`,
      rateAs: (grade) => `Oceń: „${grade}”`,
      undoGrade: (grade) => `Cofnij „${grade}”`,
      pass: {
        title: 'Wszystko odsłuchane',
        again: 'Zaczynamy od początku, od pierwszej frazy',
        next: (title) => `Dalej — ${title}`,
        nextReview: 'Dalej — powtórka',
        done: 'Na razie nie ma nic nowego',
        goOn: (title) => `Następny zestaw: ${title}`,
      },
      undoFor: (time) => `Cofnij · ${time}`,
      undoLabel: (time) => `Cofnij ocenę (zostało ${time})`,
      previous: 'Poprzednia fraza',
      next: 'Następna fraza',
      repeats: {
        auto: 'Powtórzenia: auto (3 dla nowych lub niepewnych, 1 dla utrwalonych)',
        one: 'Powtórzenia: 1',
        three: 'Powtórzenia: 3',
      },
      playMode: {
        repeat: 'Na końcu: zacznij kolejkę od nowa',
        continue: 'Na końcu: kontynuuj kolejnymi frazami',
      },
      captions: { reps: 'powt.', again: 'Od nowa', continue: 'Dalej', auto: 'Auto' },
      repeatsToast: {
        auto: 'Każda fraza gra 3×, gdy jest nowa, i 1×, gdy już ją znasz',
        one: 'Każda fraza gra raz',
        three: 'Każda fraza gra 3 razy',
      },
      playModeToast: {
        repeat: 'Na końcu kolejka zacznie się od nowa',
        continue: 'Na końcu pojawią się nowe frazy',
      },
      speedIs: (speed) => `Prędkość: ${speed}×`,
      keys: 'Klawisze: spacja — odtwarzaj lub pauza · ← → wstecz, dalej · 1 2 3 — ocena',
      audioError: (language) => `Loro nie ma jeszcze nagrania tej frazy (${language}), więc nie może jej odtworzyć.`,
      showText: () => 'Pokaż tekst',
      end: {
        reviewTitle: 'Powtórka zakończona',
        listTitle: 'Wszystko odsłuchane',
        playedThrough: 'Odsłuchane do końca',
        rated: (count) => `Ocenione: ${count}`,
        nextReview: (when) => `Następna powtórka ${when}`,
        nothingDue: 'Na razie nic do powtórki',
        continueSet: (title) => `Kontynuuj: ${title}`,
        playAgain: 'Słuchaj jeszcze raz',
        demoTitle: 'Tak działa pętla',
        demoBody: 'Usłyszeć, powiedzieć na głos, usłyszeć, ocenić. Czas na cały zestaw?',
        startSet: (title) => `Zacznij: ${title}`,
        notNow: 'Nie teraz',
      },
      noClip: 'Nie ma jeszcze nagrania tej frazy',
      audioSilent: 'Nagranie się nie odtworzyło. Sprawdź połączenie i naciśnij „Słuchaj”.',
      silent: 'Nie zagrało — naciśnij „Słuchaj”',
    },
    toast: {
      updateReady: 'Nowa wersja Loro jest gotowa',
      reload: 'Odśwież',
      dismiss: 'Zamknij komunikat',
      learned: (pts) => `Wyuczona · +${pts}`,
      removed: 'Usunięto z kolejki',
      cleared: 'Kolejka wyczyszczona',
      saved: (title) => `Zapisano jako „${title}”`,
      storageFull: 'Pamięć Loro na tym urządzeniu jest pełna, więc nowe postępy nie są zapisywane.',
      storageUnavailable: 'Ta przeglądarka nie pozwala Loro zapisywać postępów na tym urządzeniu.',
      outdated: 'W innej karcie jest otwarta nowsza wersja Loro. Odśwież, żeby postępy zapisywały się też tutaj.',
    },
    queue: {
      title: 'Kolejka',
      back: 'Wróć do odtwarzacza',
      left: (c) => `Zostało: ${c}`,
      nowPlaying: 'Teraz gra',
      upNext: (c) => `Dalej · ${c}`,
      nothing: 'Po tej frazie nic nie ma.',
      hint: 'Przesuń w prawo, żeby odtworzyć teraz, w lewo, żeby usunąć. Przeciągnij uchwyt, żeby zmienić kolejność, albo dotknij go, żeby zobaczyć opcje.',
      handleHint: 'Enter — opcje; strzałki w górę i w dół — przesuń, Delete — usuń.',
      moveUp: 'Przesuń wyżej',
      moveDown: 'Przesuń niżej',
      removeFromQueue: 'Usuń z kolejki',
      moved: (position, total) => `Teraz na pozycji ${position} z ${total}`,
      playNow: (text) => `Odtwórz teraz: ${text}`,
      move: (text) => `Przesuń: ${text}`,
      swipePlay: 'Odtwórz',
      swipeRemove: 'Usuń',
      previously: 'Już odtworzone',
      again: 'Jeszcze raz',
      justNow: 'przed chwilą',
      playNext: (text) => `Odtwórz jako następną: ${text}`,
      clear: 'Wyczyść kolejkę',
      saveAsSet: 'Zapisz jako zestaw',
      shuffle: 'Wymieszaj kolejne',
      defaultSetName: 'Moja kolejka',
    },
    library: {
      learned: 'Wyuczone',
      learnedNote: (days, recalls) => `Pamięć na ${days}+ dni, po ${recalls}+ przypomnieniach`,
      recall: 'Pamięć teraz',
      recallNote: (rated) =>
        n(rated, { one: `Średnia z ${rated} ocenionej frazy`, few: `Średnia z ${rated} ocenionych fraz`, many: `Średnia z ${rated} ocenionych fraz`, other: `Średnia z ${rated} ocenionej frazy` }),
      recallNone: 'Najpierw oceń jakąś frazę',
      started: 'Rozpoczęte',
      startedNote: 'Wysłuchane lub ocenione przynajmniej raz',
      phrasesSegment: 'Frazy',
      setsSegment: 'Zestawy',
      albumsSegment: 'Albumy',
      filters: {
        liked: 'Polubione',
        mine: 'Własne',
        due: 'Do powtórki',
        learning: 'W nauce',
        missed: 'Ostatnio „Nie pamiętam”',
        learned: 'Wyuczone',
        ownSets: 'Moje zestawy',
        likedSets: 'Polubione zestawy',
        albums: 'Albumy',
      },
      empty: {
        liked: 'Dotknij serduszka przy frazie, żeby trafiła tutaj.',
        mine: 'Dodaj własną frazę — zagra jak każda inna.',
        due: 'Teraz nie ma nic do powtórki.',
        learning: 'Tu pojawią się frazy wysłuchane lub ocenione, ale jeszcze niewyuczone.',
        missed: 'Tu pojawią się frazy ocenione „Nie pamiętam” w ostatnim tygodniu.',
        learned: (days, recalls) =>
          `Fraza jest wyuczona, gdy pamięć o niej ma trwać ${n(days, { one: `${days} dzień`, few: `${days} dni`, many: `${days} dni`, other: `${days} dnia` })} lub dłużej, po co najmniej ${recalls} udanych przypomnieniach.`,
        ownSets: 'Utwórz zestaw, żeby grupować frazy po swojemu.',
        likedSets: 'Dotknij serduszka przy zestawie, żeby trafił tutaj.',
      },
      playAll: (c) => `Słuchaj wszystkiego (${c})`,
      addPhrase: 'Dodaj własną frazę',
      myPhrases: 'Moje frazy',
      likedPhrases: 'Polubione frazy',
      onDevice: (phrases, sets) => `Tylko na tym urządzeniu: Twoje frazy — ${phrases}, Twoje zestawy — ${sets}. Zaloguj się, żeby trzymać je na koncie; postępy pójdą razem z nimi.`,
      uploaded: 'Twoje frazy i zestawy z tego urządzenia są już na koncie.',
      newSet: 'Nowy zestaw',
      recallChart: 'Przewidywana pamięć teraz',
      recallBucket: (from, to) => `${from}–${to}%`,
      recallBelow: (to) => `poniżej ${to}%`,
      recallChartEmpty: 'Oceń frazę, żeby to zobaczyć.',
      bucketCount: (label, c) => `${label}: ${phrases(c)}`,
      weeklyChart: 'Wyuczone w tygodniu',
      weekOf: (date, c) => `Tydzień od ${date}: wyuczone ${c}`,
      progress: 'Postępy',
    },
    settings: {
      title: 'Ustawienia',
      switched: (language, queueCleared) => `Kurs: ${language}${queueCleared ? '. Kolejka wyczyszczona' : ''}`,
      courseUnavailable: (language) => `Nie udało się pobrać kursu: ${language}. Sprawdź połączenie i spróbuj ponownie.`,
      profile: 'Profil',
      name: 'Imię',
      native: 'Mój język',
      course: 'Uczę się',
      courseNote: 'Postępy są zapisywane osobno dla każdej pary języków. Wróć do pary, a postępy wrócą.',
      accessibility: 'Czytnik ekranu',
      announceEveryStep: 'Zapowiadaj każdy krok',
      announceHint: 'Wyłączone: zapowiadane są tylko „Twoja kolej” i odsłonięcie frazy.',
      listening: 'Słuchanie',
      pauseLength: 'Czas na powiedzenie',
      pause: { standard: 'Standardowy', longer: 'Dłuższy' },
      pauseHint: '„Dłuższy” to mniej więcej dwa razy tyle, ile trwa fraza.',
      privacy: 'Prywatność',
      shareUsage: 'Udostępniaj dane o użyciu',
      shareUsageHint: 'Dotknięcia, ekrany i nagranie ekranu pomagają nam ulepszać Loro. Nigdy Twój głos.',
    },
    onboarding: {
      step: (i, total) => `Krok ${i} z ${total}`,
      welcome: 'Ucz się języka frazami: usłyszeć, powiedzieć, usłyszeć.',
      name: 'Jak mamy się do Ciebie zwracać?',
      namePlaceholder: 'Twoje imię',
      native: 'Jakim językiem mówisz?',
      course: 'Jakiego języka się uczysz?',
      loop: 'Jak to działa',
      loopSteps: (native, target) => [
        `Posłuchaj frazy: ${native}.`,
        `Powiedz ją na głos ${adverb(target)}, gdy jest cicho.`,
        `Posłuchaj jej: ${target}.`,
        'Oceń, jak poszło: „Nie pamiętam”, „Trudno” albo „Łatwo”. Ocenę możesz zmienić w ciągu pięciu minut.',
      ],
      next: 'Dalej',
      start: 'Zacznij od jednej frazy',
      skip: 'Zacznij bez przykładu',
    },
    summary: {
      title: 'Ta sesja',
      phrases: 'Frazy',
      repetitions: 'Powtórzenia',
      ratings: 'Oceny',
      pending: (c) => `Nadal można zmienić: ${c}; ich punkty i następna powtórka zaliczą się po pięciu minutach`,
      points: 'Zdobyte punkty',
      passes: 'Przejść przez kolejkę',
      nextDue: 'Następna powtórka',
      nothingDue: 'Na razie nic nie zaplanowano',
      none: 'W tej sesji nic jeszcze nie zagrało.',
    },
    connection: {
      loading: 'Pobieram Twój kurs…',
      offlineTitle: 'Loro nie może połączyć się z serwerem',
      offlineBody: 'Kurs pobiera się raz, a potem działa bez sieci. Sprawdź połączenie i spróbuj ponownie.',
      retry: 'Spróbuj ponownie',
      useCourse: (language) => `Ucz się dalej: ${language}`,
    },
    account: {
      title: 'Konto',
      signIn: 'Zaloguj się',
      signInTitle: 'Logowanie do Loro',
      signInBody: 'Twórz zestawy fraz, piosenki i okładki z AI, trzymaj je na koncie i dziel się nimi. Postępy na tym urządzeniu zostają, jak są.',
      email: 'E-mail',
      emailPlaceholder: 'ty@przyklad.pl',
      sendCode: 'Wyślij mi kod e-mailem',
      sending: 'Wysyłam…',
      codeTitle: 'Sprawdź pocztę',
      codeBody: (email) => `Wysłaliśmy sześciocyfrowy kod na ${email}. Działa przez 10 minut.`,
      code: 'Sześciocyfrowy kod',
      verify: 'Zaloguj się',
      verifying: 'Logowanie…',
      resend: 'Wyślij nowy kod',
      changeEmail: 'Użyj innego adresu',
      signedInAs: (email) => `Zalogowano jako ${email}`,
      signedInWith: (provider) => `Zalogowano przez ${provider}`,
      signOut: 'Wyloguj się',
      deleteData: 'Usuń moje dane w Loro',
      deleteDataConfirm: 'Usunąć Twoje zestawy, albumy, piosenki, okładki i postępy zapisane na koncie? Osoby, z którymi się nimi dzielisz, też je stracą. Postępy na tym urządzeniu zostaną. Tego nie można cofnąć.',
      deletedData: 'Twoje dane w Loro zostały usunięte.',
      deleteAccount: 'Usuń moje konto',
      deleteAccountConfirm: 'Usunąć Twoje konto Loro ze wszystkim, co w nim jest: zestawami, albumami, piosenkami, okładkami i zapisanymi w nim postępami? Osoby, z którymi się nimi dzielisz, też je stracą. Postępy na tym urządzeniu zostaną. Tego nie można cofnąć.',
      deleteAccountYes: 'Usuń konto',
      deletedAccount: 'Twoje konto zostało usunięte.',
      synced: 'Twoje postępy są na koncie i podążają za Tobą na inne urządzenia.',
      syncFailed: 'Nie udało się teraz zapisać postępów na koncie. Są bezpieczne na tym urządzeniu i zapiszą się, gdy wróci połączenie.',
      signedOut: 'Wylogowano. Postępy na tym urządzeniu zostały.',
      welcome: 'Zalogowano',
      displayName: 'Imię przy tym, czym się dzielisz',
      displayNameHint: 'Pokazywane jako „od …” przy zestawach i albumach, które udostępnisz wszystkim. Zostaw puste, żeby było „od uczącego się”.',
      displayNameSaved: 'Imię zapisane',
      notNow: 'Nie teraz',
      google: 'Kontynuuj z Google',
      apple: 'Kontynuuj z Apple',
      needed: 'Zaloguj się, żeby tworzyć zestawy, piosenki i okładki z AI oraz się nimi dzielić.',
      errors: {
        badEmail: 'To nie wygląda na adres e-mail.',
        badCode: 'Ten kod jest niepoprawny albo wygasł.',
        tooMany: 'Za dużo prób. Poczekaj kilka minut i spróbuj ponownie.',
        unavailable: 'Logowanie e-mailem nie jest skonfigurowane na tym serwerze.',
        providerUnavailable: (provider: string) => `Logowanie przez ${provider} nie jest skonfigurowane dla tego adresu Loro.`,
        offline: 'Loro nie może połączyć się z serwerem. Sprawdź połączenie.',
        generic: 'Coś poszło nie tak. Spróbuj ponownie.',
        full: 'Twoje konto ma już maksimum takich elementów. Usuń któryś, żeby zrobić miejsce.',
        invalid: 'Nie udało się zapisać: coś jest za długie, brakuje czegoś albo jest tam link.',
      },
      today: 'Dzisiejszy limit',
      usage: {
        phrases: (left, limit) => `Zestawy fraz: zostało ${left} z ${limit}`,
        cover: (left, limit) => `Okładki: zostało ${left} z ${limit}`,
        song: (left, limit) => `Piosenki: zostało ${left} z ${limit}`,
      },
      kept: (s, a) => `${sets(s)} i ${albums(a)} na Twoim koncie`,
      resets: (time) => `Odnowi się o ${time}`,
      spent: (time) => `Dzisiejszy limit wykorzystany. Odnowi się o ${time}.`,
      writers: 'Kto to tworzy na tym serwerze',
      writer: {
        ai: 'AI',
        bank: 'Bank fraz Loro (AI nie jest skonfigurowana)',
        pattern: 'Rysowane wzory (AI nie jest skonfigurowana)',
        phrases: 'Twoje frazy jako tekst (AI nie jest skonfigurowana)',
        elevenlabs: 'Śpiewa ElevenLabs Music',
        demo: 'Dźwięk demo (brak dostawcy muzyki)',
      },
      writerKind: { phrases: 'Frazy', cover: 'Okładki', lyrics: 'Tekst', music: 'Dźwięk' },
    },
    tabs: {
      home: 'Start',
      explore: 'Odkrywaj',
      create: 'Twórz',
      library: 'Biblioteka',
    },
    share: {
      hidden: 'Ktoś to zgłosił, więc nie pokazuje się już w Społeczności. Każdy z linkiem nadal może to otworzyć.',
      noName: 'Inni widzą to jako „od uczącego się”. Dodaj imię, żeby było widać autora.',
      addName: 'Dodaj imię',
      visibility: 'Kto może to zobaczyć',
      private: 'Tylko Ty',
      privateDetail: 'Na Twoim koncie, na Twoich urządzeniach',
      link: 'Każdy z linkiem',
      linkDetail: 'Bez wpisu na listach; otwiera się z linku',
      public: 'Wszyscy',
      publicDetail: 'Na liście Społeczności Twojego kursu',
      share: 'Udostępnij',
      shareMessage: (title, url) => `${title} w Loro: ${url}`,
      copied: 'Link skopiowany',
      makeShareable: 'Widzisz to tylko Ty. Wybierz, kto jeszcze może, zanim się tym podzielisz.',
      by: (name) => `od ${name}`,
      byLearner: 'od uczącego się',
      yours: 'Twoje',
      save: 'Zapisz w bibliotece',
      saved: 'W Twojej bibliotece',
      unsave: 'Usuń z biblioteki',
      savedToast: 'Zapisano w bibliotece',
      unsavedToast: 'Usunięto z biblioteki',
      delete: 'Usuń',
      deleteSetConfirm: (title) => `Usunąć „${title}” z konta? Osoby, z którymi go dzielisz, też go stracą. Postępy w jego frazach zostaną.`,
      deleteAlbumConfirm: (title) => `Usunąć album „${title}” i jego piosenki?`,
      deleted: 'Usunięto',
      cover: 'Nowa okładka',
      coverMaking: 'Rysuję okładkę…',
      coverBy: { ai: 'Okładkę narysowała AI', pattern: 'Rysowany wzór' },
      coverLater: 'Okładka jeszcze się rysuje. Pojawi się, gdy będzie gotowa.',
      coverFor: (title) => `Nowa okładka dla „${title}”`,
      coverAsk: {
        own: 'Nowa narysowana okładka zajmie miejsce obecnej.',
        set: 'Zestawy Loro się nie zmieniają, więc dostaniesz własną kopię tego zestawu z nową okładką — w Bibliotece. Postępy w jego frazach zostaną.',
        album: 'Albumy Loro się nie zmieniają, więc dostaniesz własną kopię tego albumu i jego piosenek z nową okładką — w Bibliotece.',
        phrase: 'Okładka tej frazy, którą widzisz tylko Ty: wszędzie, gdzie fraza się pokazuje, na każdym urządzeniu, na którym się logujesz.',
        song: 'Okładka tej piosenki, którą widzisz tylko Ty, na każdym urządzeniu, na którym się logujesz.',
      },
      coverDrawn: 'Okładki to rysunki bez słów, nigdy zdjęcia.',
      coverDraw: 'Narysuj okładkę',
      coverCopied: 'Twoja kopia jest w Bibliotece',
      changed: 'Zapisano',
      notFound: 'Ten link niczego nie otwiera. Mógł zostać ustawiony jako prywatny albo usunięty.',
      opening: 'Otwieram…',
      report: 'Zgłoś',
      reported: 'Zgłoszone. Dziękujemy.',
      reason: { offensive: 'Obraźliwe lub krzywdzące', wrong: 'Zły język lub błędy', spam: 'Spam lub reklama', other: 'Coś innego' },
    },
    community: {
      title: 'Społeczność',
      sets: 'Udostępnione zestawy',
      albums: 'Udostępnione albumy',
      emptySets: 'W tym kursie nikt jeszcze nie udostępnił zestawu. Utwórz własny i wybierz „Wszyscy”.',
      emptyAlbums: 'W tym kursie nikt jeszcze nie udostępnił albumu.',
      search: 'Szukaj wśród udostępnionych zestawów',
      searchAlbums: 'Szukaj wśród udostępnionych albumów',
      moreBy: (name: string) => `Więcej od ${name}`,
      moreByLearner: 'Więcej od tej osoby',
      sortNew: 'Najnowsze',
      sortPopular: 'Najczęściej zapisywane',
      sortLabel: 'Kolejność',
      savedBy: (c: number) => `zapisało: ${c}`,
      noSetsFound: (q: string) => `Żaden udostępniony zestaw nie pasuje do „${q}”.`,
      noAlbumsFound: (q: string) => `Żaden udostępniony album nie pasuje do „${q}”.`,
      offline: 'Społeczność wymaga połączenia.',
    },
    phrasesTab: {
      title: 'Frazy',
      course: 'Kurs Loro',
      yourSets: 'Twoje zestawy',
      savedSets: 'Zapisane zestawy',
      makeSet: 'Utwórz zestaw z AI',
      signInToMake: 'Zaloguj się, żeby tworzyć zestawy z AI',
    },
    music: {
      likedSongs: 'Polubione piosenki',
      likedEmpty: 'Dotknij serduszka przy piosence, żeby trafiła tutaj.',
      songKind: 'Piosenka',
      likeSong: 'Polub piosenkę',
      rateSong: (c: number) => (c === 1 ? 'Jak poszło? Twoja ocena dotyczy frazy z tej piosenki.' : `Jak poszło? Twoja ocena dotyczy fraz z tej piosenki (${c}).`),
      songRated: (grade: string, c: number) => (c === 1 ? `${grade}: powtórzono frazę z piosenki.` : `${grade}: powtórzono frazy z piosenki (${c}).`),
      songReviewed: (c: number) => (c === 1 ? 'Powtórzono frazę z piosenki.' : `Powtórzono frazy z piosenki (${c}).`),
      songReady: (title: string) => `„${title}” jest gotowa`,
      songFailed: (title: string) => `Nie udało się stworzyć „${title}”. Spróbuj ponownie z jej albumu.`,
      play: 'Słuchaj',
      needsConnection: 'Piosenki wymagają połączenia. Spróbuj ponownie, gdy będziesz online.',
      cantPlay: 'Tej piosenki nie można teraz odtworzyć.',
      setSongs: 'Piosenki',
      title: 'Muzyka',
      loro: 'Od Loro',
      yours: 'Twoje albumy',
      saved: 'Zapisane albumy',
      songs,
      empty: 'W tym kursie nie ma jeszcze albumów.',
      noSongs: 'Nie ma tu jeszcze piosenek.',
      loroAlbum: 'Każdy zestaw Loro z tego kursu, zaśpiewany.',
      makeSong: 'Stwórz piosenkę',
      album: 'Album',
      playAlbum: 'Słuchaj albumu',
      playSong: (title) => `Słuchaj: ${title}`,
      demoSound: 'Dźwięk demo',
      spokenDemo: 'Demo z głosem',
      spokenNote: 'Wersy czyta głos Loro na tle podkładu stworzonego przez serwer; podświetlają się w trakcie. Piosenki będą śpiewane, gdy zostanie skonfigurowany dostawca muzyki.',
      demoNote: 'Ten podkład stworzył serwer; wersy tekstu podświetlają się w trakcie. Piosenki będą śpiewane, gdy zostanie skonfigurowany dostawca muzyki.',
      sung: 'Śpiewana',
      lyrics: 'Tekst',
      lyricsBy: { ai: 'Tekst od AI', phrases: 'Tekst: frazy zestawu' },
      meanings: 'Znaczenia',
      showMeanings: 'Pokaż znaczenia',
      hideMeanings: 'Ukryj znaczenia',
      section: { verse: 'Zwrotka', chorus: 'Refren', bridge: 'Przejście' },
      rendering: 'Tworzę piosenkę…',
      renderingNote: 'Chwilę to potrwa. Możesz opuścić ten ekran: piosenka nadal się tworzy.',
      failed: 'Nie udało się stworzyć tej piosenki.',
      retrySong: (title: string) => `Spróbuj ponownie: „${title}”`,
      removeSong: 'Usuń piosenkę',
      removeSongConfirm: (title: string) => `Usunąć „${title}” z albumu?`,
      nowPlaying: 'Teraz gra',
      previous: 'Poprzednia piosenka',
      next: 'Następna piosenka',
      openSet: 'Otwórz zestaw',
      fromSet: (title) => `Z zestawu „${title}”`,
      loadFailed: 'Nie udało się wczytać albumu.',
      style: {
        modern_pop: 'Pop',
        acoustic_folk: 'Folk',
        gentle_ballad: 'Ballada',
        upbeat_kids: 'Do śpiewania razem',
      },
    },
    create: {
      title: 'Twórz',
      phrasesTitle: 'Zestaw fraz',
      phrasesBody: 'Z tematu, kilku słów lub tekstu.',
      songTitle: 'Piosenka z zestawu',
      songBody: 'Usłysz swoje frazy w piosence.',
      left: (c) => `Na dziś zostało: ${c}`,
      none: 'Na dziś nic nie zostało',
      source: { ai: 'AI', bank: 'Bank fraz (bez AI)', elevenlabs: 'ElevenLabs Music', demo: 'Dźwięk demo' },
      pickSet: 'Który zestaw?',
      pickSetEmpty: 'W tym kursie nie ma jeszcze zestawów.',
      pickStyle: 'Styl',
      pickAlbum: 'Album',
      newAlbum: 'Nowy album',
      songTitleLabel: 'Tytuł piosenki',
      makeSong: 'Stwórz piosenkę',
      songStarted: 'Piosenka się tworzy',
      saveToAccount: 'Zapisz na koncie',
      saving: 'Zapisuję…',
      savedToAccount: 'Zapisano na koncie',
      setTitle: 'Tytuł',
      setDescription: 'Do czego służy (opcjonalnie)',
      withCover: 'Narysuj okładkę',
      from: { ai: 'Napisane przez AI', bank: 'Z banku fraz Loro' },
      bankOnly: 'Ten serwer nie ma skonfigurowanej AI, więc te frazy pochodzą z banku fraz Loro.',
      noMatch: 'W banku fraz nie ma nic na ten temat. Spróbuj jednego z tych:',
    },
    error: {
      title: 'Coś poszło nie tak',
      body: 'Zwykle pomaga odświeżenie, a postępy zostają. Jeśli błąd się powtarza, zapisane na tym urządzeniu postępy mogą nie pasować do tej wersji: skopiuj je, jeśli chcesz je zachować, a potem zresetuj, żeby zacząć od zera na tym urządzeniu.',
      reload: 'Odśwież',
      part: 'Nie udało się pokazać tej części ekranu. Twoje postępy są bezpieczne.',
      copy: 'Skopiuj postępy jako JSON',
      copied: 'Skopiowano',
      reset: 'Zresetuj postępy',
    },
  };
}
