// Russian UI copy. Awaiting native review (see content/meta.json).
import type { Copy, Plural } from './en';

export function makeRu(n: Plural): Copy {
  // "испанский" → "по-испански": the adverb a sentence needs ("скажите вслух по-испански").
  const adverb = (language: string) => (language.endsWith('ский') ? `по-${language.slice(0, -1)}` : `на языке: ${language}`);
  const phrases = (c: number) => n(c, { one: `${c} фраза`, few: `${c} фразы`, many: `${c} фраз`, other: `${c} фразы` });
  return {
    locale: 'ru-RU',
    common: {
      close: 'Закрыть',
      back: 'Назад',
      cancel: 'Отмена',
      charsLeft: (c) => n(c, { one: `Остался ${c} символ`, few: `Осталось ${c} символа`, many: `Осталось ${c} символов`, other: `Осталось ${c} символа` }),
      save: 'Сохранить',
      undo: 'Отменить',
      play: 'Слушать',
      pause: 'Пауза',
      delete: 'Удалить',
      moreOptions: 'Ещё',
      phrases,
      sets: (c) => n(c, { one: `${c} набор`, few: `${c} набора`, many: `${c} наборов`, other: `${c} набора` }),
      points: (c) => n(c, { one: `${c} очко`, few: `${c} очка`, many: `${c} очков`, other: `${c} очка` }),
      level: (level) => level,
      grade: { missed: 'Не помню', hard: 'Трудно', easy: 'Легко' },
      register: { formal: 'Вежливо', informal: 'Неформально', neutral: 'Нейтрально' },
      tag: {
        politeness: 'Вежливость',
        question: 'Вопросы',
        request: 'Просьбы',
        numbers: 'Числа',
        food: 'Еда и напитки',
        directions: 'Дорога',
        social: 'Общение',
      },
      fullPlay: (time) => `${time} при 1×`,
    },
    nav: {
      main: 'Главное меню',
      home: 'Главная',
      explore: 'Обзор',
      library: 'Библиотека',
      settings: (name) => (name ? `${name}: настройки` : 'Настройки'),
      learning: (language) => `Изучаете ${language}`,
      add: 'Добавить фразу или набор',
      addSheet: 'Добавление',
      points: (c) => n(c, { one: `${c} очко`, few: `${c} очка`, many: `${c} очков`, other: `${c} очка` }),
      pointsShort: () => 'очк.',
    },
    status: {
      new: 'Новая',
      listenedNotRated: 'Прослушана, без оценки',
      due: 'Пора повторить',
      learned: (pct) => `Выучена · память ${pct}%`,
      learning: (pct, when) => `Память ${pct}% · снова ${when}`,
      set: { new: 'Новый', 'in-progress': 'В процессе', learned: 'Всё выучено' },
    },
    home: {
      firstRun: 'Послушайте фразу и скажите её сами, прежде чем услышите снова.',
      learned: 'Выучено',
      started: 'Начато',
      today: (heard, rated) =>
        `Сегодня: ${n(heard, { one: `прослушана ${heard} фраза`, few: `прослушано ${heard} фразы`, many: `прослушано ${heard} фраз`, other: `прослушано ${heard} фразы` })} · оценок: ${rated}`,
      reviewTitle: 'Повторение',
      reviewBody: (due) => n(due, { one: `Пора повторить ${due} фразу`, few: `Пора повторить ${due} фразы`, many: `Пора повторить ${due} фраз`, other: `Пора повторить ${due} фразы` }),
      reviewCapped: (shown) => `В этом занятии — ${shown} самых давних.`,
      playPhrases: (c) => `Слушать: ${phrases(c)}`,
      duration: (time) => `${time} при 1×`,
      startTitle: 'С чего начать',
      continueTitle: 'Продолжить',
      nextTitle: 'Следующий набор',
      next: (c, when) => `Дальше: ${phrases(c)} ${when}`,
      nextAfter: (c, when) => `Потом: ещё ${phrases(c)} ${when}`,
      jumpBackIn: 'Вернуться',
      history: 'История',
      notStarted: 'Ещё не начатые',
      demoTitle: 'Попробуйте цикл',
      demoBody: 'Одна фраза: услышать, сказать, услышать.',
      demoButton: 'Послушать одну фразу',
      courseDoneTitle: 'Все фразы этого курса выучены',
      courseDoneBody: 'Повторения вернутся, когда подойдёт срок. А пока добавьте свои фразы или попробуйте другой курс.',
      addOwn: 'Своя фраза',
      otherCourse: 'Другой курс',
    },
    history: {
      title: 'История',
      empty: 'Пока ничего не прослушано.',
      mixed: 'Смешанная очередь',
      run: (p, points) => `${phrases(p)} · +${points} очк.`,
    },
    explore: {
      search: 'Фразы, заметки, темы',
      searchShort: 'Поиск',
      topics: 'Темы',
      levels: 'Уровни',
      tags: 'Метки',
      allSets: 'Все наборы',
      sets: (c) => n(c, { one: `${c} набор`, few: `${c} набора`, many: `${c} наборов`, other: `${c} набора` }),
      phrases,
      noPhrases: (q) => `Нет фраз по запросу «${q}».`,
      noPhrasesFiltered: 'Нет фраз с этими фильтрами.',
      noSets: 'Нет подходящих наборов.',
      addAsOwn: (q) => `Добавить «${q}» как свою фразу`,
      removeFilter: (label) => `Убрать фильтр: ${label}`,
      clearFilters: 'Сбросить фильтры',
      quickPlay: (title) => `Слушать «${title}»`,
      searchedSets: 'Наборы',
    },
    set: {
      phrasesHeading: 'Фразы',
      summary: (total, learned, due) => `${phrases(total)} · выучено ${learned}${due > 0 ? ` · к повторению ${due}` : ''}`,
      sort: { set: 'Как в наборе', az: 'А–Я', due: 'Сначала к повторению', weakest: 'Сначала слабые' },
      sortTitle: 'Сортировка фраз',
      playsIn: (order) => `Порядок: ${order}`,
      playAll: (title) => `Слушать «${title}»`,
      pauseAll: (title) => `Пауза: «${title}»`,
      resume: (title) => `Продолжить «${title}»`,
      pausedAt: (position, total) => `На паузе: ${position} из ${total}`,
      playDueNew: (c) => `Только новые и к повторению (${c})`,
      pauseDueNew: 'Пауза: новые и к повторению',
      shufflePlay: 'Вперемешку',
      like: 'Отметить набор',
      duration: (time) => `Целиком ${time} при 1×`,
      playNext: 'Поставить следующим',
      addToQueue: 'В очередь',
      share: 'Поделиться ссылкой',
      linkCopied: 'Ссылка скопирована',
      copyUnavailable: 'Копирование здесь недоступно',
      rename: 'Переименовать',
      delete: 'Удалить набор',
      deleted: 'Набор удалён',
      own: 'Ваш набор',
      ownEmpty: 'Добавляйте фразы из их подробностей (⋮) или из плеера.',
      addPhrases: 'Добавить фразы',
      addedNext: 'Будет следующей',
      addedEnd: 'Добавлено в очередь',
      notFound: 'Этот набор недоступен.',
      otherCourse: (language) => `Этот набор из курса: ${language}.`,
      switchCourse: (language) => `Учить: ${language}`,
    },
    phrase: {
      details: (text) => `Подробнее: ${text}`,
      play: (text) => `Слушать: ${text}`,
      playNext: 'Поставить следующей',
      addToQueue: 'В очередь',
      like: 'Отметить',
      liked: 'Отмечена',
      likeLabel: 'Отметить фразу',
      addToSet: 'В набор…',
      heard: (c) => `прослушана ${c}×`,
      notes: { mnemonic: 'Подсказка', grammar: 'Грамматика', pronunciation: 'Звуки' },
      notesTitle: 'Заметки',
      notesInEnglish: 'Заметки пока на английском.',
      words: 'Нажмите на слово, чтобы увидеть значение.',
      glossHint: 'Показывает значение',
      edit: 'Изменить фразу',
      delete: 'Удалить фразу',
      deleted: 'Фраза удалена',
      removeFromSet: 'Убрать из набора',
      removedFromSet: 'Убрана из набора',
      moveUp: 'Выше в наборе',
      moveDown: 'Ниже в наборе',
      yours: 'Ваша фраза',
      yoursShort: 'Ваша',
      sounds: 'Произношение:',
      notesByDevice: (language: string) => `Loro составил эти заметки на этом устройстве по правилам языка: ${language}. Носитель языка их не проверял.`,
      writeNotes: 'Попросить заметки у сервиса',
      writingNotes: 'Пишем заметки…',
      notesFailed: 'Сервис не ответил. Попробуйте ещё раз чуть позже.',
      notesByAi: 'Заметки к ней написал ИИ. Носитель языка их не проверял.',
    },
    addToSet: {
      title: 'Добавить в набор',
      newSet: 'Новый набор…',
      added: (title) => `Добавлено в «${title}»`,
      already: (title) => `Уже в «${title}»`,
      alreadyHere: 'Уже в этом наборе',
      none: 'У вас пока нет своих наборов.',
    },
    pickPhrases: {
      search: 'Поиск фраз',
      add: 'Добавить',
      added: 'Добавлена',
      done: 'Готово',
    },
    createSet: {
      title: 'Новый набор',
      renameTitle: 'Переименовать набор',
      name: 'Название',
      create: 'Создать',
      created: (title) => `Создан «${title}»`,
      taken: 'Набор с таким названием уже есть.',
    },
    addPhrase: {
      title: 'Своя фраза',
      target: (language) => `На языке: ${language}`,
      native: (language) => `На языке: ${language}`,
      hint: 'Звучит голосом устройства.',
      add: 'Добавить фразу',
      added: 'Фраза добавлена',
      editTitle: 'Изменить фразу',
      edited: 'Фраза обновлена',
      duplicate: 'Уже есть в курсе:',
    },
    make: {
      title: 'Собрать набор',
      into: (set) => `Добавить в «${set}»`,
      entryDetail: 'Фразы по теме, словам или тексту',
      intro: 'Скажите, о чём хотите говорить. Loro подберёт фразы: добавьте нужные, остальные пропустите.',
      modesLabel: 'Подобрать по',
      modes: { topic: 'Тема', keywords: 'Слова', text: 'Текст' },
      field: { topic: 'Тема или ситуация', keywords: 'Несколько слов', text: 'Ваш текст' },
      placeholder: {
        topic: 'В аптеке',
        keywords: 'отель, полотенце, завтрак',
        text: 'Сообщение, меню, несколько строк, которые хотите сказать',
      },
      hintTopic: 'Лучше всего — место или момент.',
      hintKeywords: 'Разделите их запятыми.',
      hintText: (language) => `На любом языке: фразы будут ${adverb(language)}.`,
      tryTopics: 'Или выберите',
      suggest: 'Подобрать фразы',
      writing: 'Пишем фразы…',
      byAi: 'Подсказки пишет ИИ. Носитель языка их не проверял.',
      byDevice: 'Подсказки берутся из фраз на этом устройстве.',
      fellBack: 'Сервис фраз не ответил, поэтому эти фразы — с этого устройства.',
      none: (input) => `Пока нет фраз для «${input}».`,
      noneHint: 'Попробуйте другие слова или напишите фразу сами.',
      writeOwn: 'Добавить свою фразу',
      progress: (position, total) => `${position} из ${total}`,
      addedCount: (count) => `Добавлено: ${count}`,
      cardLabel: (position, total) => `Подсказка ${position} из ${total}`,
      source: {
        course: (set) => `Из «${set}»`,
        mine: 'Ваша фраза',
        bank: 'Фразы Loro',
        ai: 'Написано ИИ · не проверено',
      },
      listen: (text) => `Прослушать: ${text}`,
      edit: 'Исправить',
      editLabel: (text) => `Исправить: ${text}`,
      add: 'Добавить',
      skip: 'Пропустить',
      addLabel: (text) => `Добавить: ${text}`,
      skipLabel: (text) => `Пропустить: ${text}`,
      undoLabel: (text) => `Отменить: ${text}`,
      swipeHint: 'Смахните вправо, чтобы добавить, влево — чтобы пропустить.',
      keysHint: 'Клавиши: → добавить, ← пропустить.',
      announceAdded: (text) => `Добавлено: ${text}`,
      announceSkipped: (text) => `Пропущено: ${text}`,
      done: 'Готово',
      endTitle: (count) => (count === 1 ? 'Это была единственная подсказка' : `Это все подсказки: ${count}`),
      endAdded: (count) => (count === 0 ? 'Вы пропустили все.' : `Добавлено фраз: ${count}.`),
      more: 'Ещё подсказки',
      noMore: 'Больше подсказок для этого нет.',
      another: 'Попробовать другое',
      review: (count) => n(count, { one: `Сохранить ${count} фразу`, few: `Сохранить ${count} фразы`, many: `Сохранить ${count} фраз`, other: `Сохранить ${count} фразы` }),
      saveTitle: 'Сохранить набор',
      keptHeading: (count) => `Фраз к сохранению: ${count}`,
      remove: (text) => `Убрать: ${text}`,
      addInto: (count, set) => `Добавить в «${set}»: ${phrases(count)}`,
      addedInto: (count, set) => `Добавлено в «${set}»: ${phrases(count)}`,
      backToDeck: 'Назад к подсказкам',
      unsaved: (count) => `Не сохранено: ${phrases(count)}`,
      reopen: 'Открыть снова',
      fromExplore: (query) => `Подобрать фразы про «${query}»`,
      fromSet: 'Подобрать фразы',
      originAi: 'Написано ИИ. Носитель языка это не проверял.',
      originBank: 'Из фраз Loro.',
      defaultTitleText: 'Из моего текста',
    },
    player: {
      dialog: 'Сейчас звучит',
      close: 'Закрыть плеер',
      openQueue: 'Открыть очередь',
      summary: 'Итоги занятия',
      position: (i, total) => `${i} из ${total}`,
      positionInQueue: (i, total) => `${i} из ${total} в очереди`,
      hidden: () => 'Фраза скрыта, пока вы её не услышите',
      steps: 'Шаги',
      yourTurn: 'Ваша очередь',
      instruction: {
        native: (language) => `Слушайте: ${language}`,
        pause: (language) => `Ваша очередь — скажите вслух ${adverb(language)}`,
        target: (language) => `Слушайте: ${language}`,
        rate: 'Оцените или подождите',
      },
      paused: 'Пауза',
      coach: 'Скажите её сейчас, до того как услышите. Ничего не записывается — потом вы сами оцените, как получилось.',
      repetition: (r, total) => `Повтор ${r} из ${total}`,
      howDidItGo: 'Удалось вспомнить?',
      rateAfterTurn: 'Оцените, когда скажете сами',
      nextIn: (interval) => `через ${interval}`,
      rated: (grade, when) => `Оценка «${grade}» — снова ${when}`,
      requeued: '· ещё раз в этой очереди',
      undoFor: (time) => `Отменить · ${time}`,
      undoLabel: (time) => `Отменить оценку (осталось ${time})`,
      previous: 'Предыдущая фраза',
      next: 'Следующая фраза',
      repeats: {
        auto: 'Повторы: авто (3 для новых или неуверенных, 1 для усвоенных)',
        one: 'Повторы: 1',
        three: 'Повторы: 3',
      },
      playMode: {
        repeat: 'В конце: начать очередь заново',
        continue: 'В конце: продолжить следующими фразами',
      },
      captions: { reps: 'повт.', again: 'Снова', continue: 'Дальше', auto: 'Авто' },
      repeatsToast: {
        auto: 'Каждая фраза звучит 3× пока новая, 1× когда запомнится',
        one: 'Каждая фраза звучит один раз',
        three: 'Каждая фраза звучит 3 раза',
      },
      playModeToast: {
        repeat: 'В конце очередь начнётся заново',
        continue: 'В конце пойдут новые фразы',
      },
      speed: 'Скорость',
      speedIs: (speed) => `Скорость: ${speed}×`,
      keys: 'Клавиши: пробел — пуск или пауза · ← → назад, вперёд · 1 2 3 — оценка',
      audioError: (language) =>
        `На устройстве нет голоса (${language}), поэтому фраза не звучит. Добавьте его в настройках речи системы и нажмите «Слушать».`,
      showText: () => 'Показать текст',
      end: {
        reviewTitle: 'Повторение завершено',
        listTitle: 'Всё прослушано',
        playedThrough: 'Прослушано до конца',
        rated: (count) => `Оценено: ${count}`,
        nextReview: (when) => `Следующее повторение ${when}`,
        nothingDue: 'Пока нечего повторять',
        continueSet: (title) => `Продолжить «${title}»`,
        playAgain: 'Слушать снова',
        demoTitle: 'Вот и весь цикл',
        demoBody: 'Услышать, сказать вслух, услышать, оценить. Готовы к целому набору?',
        startSet: (title) => `Начать «${title}»`,
        notNow: 'Не сейчас',
      },
      miniRate: 'Нажмите, чтобы оценить',
      noVoice: 'Нет голоса для этого языка',
      audioSilent: 'Речь остановилась до того, как фраза прозвучала. Нажмите «Слушать», чтобы попробовать снова.',
      silent: 'Речь остановилась — нажмите «Слушать»',
      voice: (name) => `Голос: ${name}`,
      changeVoice: (name) => `Голос: ${name}. Сменить голос`,
    },
    toast: {
      updateReady: 'Готова новая версия Loro',
      reload: 'Обновить',
      dismiss: 'Закрыть сообщение',
      learned: (points) => `Выучена · +${points}`,
      passComplete: 'Очередь пройдена',
      nextSet: (title) => `Дальше: ${title}`,
      removed: 'Убрано из очереди',
      cleared: 'Очередь очищена',
      saved: (title) => `Сохранено как «${title}»`,
      storageFull: 'Хранилище Loro на этом устройстве заполнено, новый прогресс не сохраняется.',
      storageUnavailable: 'Этот браузер не даёт Loro сохранять прогресс на устройстве.',
      outdated: 'В другой вкладке открыта новая версия Loro. Перезагрузите, чтобы прогресс сохранялся и здесь.',
    },
    queue: {
      title: 'Очередь',
      back: 'Назад к плееру',
      left: (c) => `Осталось ${c}`,
      nowPlaying: 'Сейчас звучит',
      upNext: (c) => `Дальше · ${c}`,
      nothing: 'После этой фразы ничего нет.',
      hint: 'Смахните вправо, чтобы включить сейчас, влево — чтобы убрать. Тяните за ручку, чтобы переставить, или коснитесь её для действий.',
      handleHint: 'Enter — действия; стрелки вверх и вниз — переставить, Delete — убрать.',
      moveUp: 'Переместить выше',
      moveDown: 'Переместить ниже',
      removeFromQueue: 'Убрать из очереди',
      moved: (position, total) => `Теперь на месте ${position} из ${total}`,
      playNow: (text) => `Слушать сейчас: ${text}`,
      move: (text) => `Переставить: ${text}`,
      swipePlay: 'Слушать',
      swipeRemove: 'Убрать',
      previously: 'Уже звучали',
      again: 'Снова',
      justNow: 'только что',
      playNext: (text) => `Поставить следующей: ${text}`,
      clear: 'Очистить очередь',
      saveAsSet: 'Сохранить как набор',
      shuffle: 'Перемешать дальнейшие',
      defaultSetName: 'Моя очередь',
    },
    library: {
      learned: 'Выучено',
      learnedNote: (days, recalls) => `Помнится ${days}+ дней, после ${recalls}+ вспоминаний`,
      recall: 'Память сейчас',
      recallNote: (rated) => n(rated, { one: `Среднее по ${rated} оценённой фразе`, other: `Среднее по ${rated} оценённым фразам` }),
      recallNone: 'Сначала оцените фразу',
      started: 'Начато',
      startedNote: 'Прослушаны или оценены хотя бы раз',
      phrasesSegment: 'Фразы',
      setsSegment: 'Наборы',
      filters: {
        liked: 'Отмеченные',
        mine: 'Свои',
        due: 'К повторению',
        learning: 'Изучаются',
        missed: 'Недавно не вспомнились',
        learned: 'Выученные',
        ownSets: 'Мои наборы',
        likedSets: 'Отмеченные наборы',
      },
      empty: {
        liked: 'Нажмите на сердечко у фразы, чтобы она была здесь.',
        mine: 'Добавьте свою фразу — она зазвучит, как любая другая.',
        due: 'Сейчас повторять нечего.',
        learning: 'Здесь фразы, которые вы слышали или оценили, но ещё не выучили.',
        missed: 'Здесь фразы с оценкой «Не помню» за последнюю неделю.',
        learned: (days, recalls) =>
          `Фраза выучена, когда память о ней должна держаться ${n(days, { one: `${days} день`, few: `${days} дня`, many: `${days} дней`, other: `${days} дня` })} и больше, после хотя бы ${recalls} удачных вспоминаний.`,
        ownSets: 'Создайте набор, чтобы сгруппировать фразы по-своему.',
        likedSets: 'Нажмите на сердечко у набора, чтобы он был здесь.',
      },
      playAll: (c) => `Слушать всё (${c})`,
      addPhrase: 'Своя фраза',
      newSet: 'Новый набор',
      recallChart: 'Прогноз памяти сейчас',
      recallBucket: (from, to) => `${from}–${to}%`,
      recallBelow: (to) => `меньше ${to}%`,
      recallChartEmpty: 'Оцените фразу, чтобы увидеть это.',
      bucketCount: (label, c) => `${label}: ${phrases(c)}`,
      weeklyChart: 'Выучено за неделю',
      weekOf: (date, c) => `Неделя с ${date}: выучено ${c}`,
      progress: 'Прогресс',
    },
    settings: {
      title: 'Настройки',
      switched: (language, queueCleared) => `Курс: ${language}${queueCleared ? '. Очередь очищена' : ''}`,
      profile: 'Профиль',
      name: 'Имя',
      native: 'Мой язык',
      course: 'Я изучаю',
      courseNote: 'Прогресс хранится для каждой пары языков. Переключитесь обратно — и он вернётся.',
      voices: 'Голоса',
      voiceAuto: (name) => `Автоматически (${name})`,
      accessibility: 'Экранный диктор',
      announceEveryStep: 'Объявлять каждый шаг',
      announceHint: 'Выключено: объявляются только «Ваша очередь» и ответ.',
      listening: 'Прослушивание',
      pauseLength: 'Время, чтобы сказать',
      pause: { standard: 'Обычное', longer: 'Подольше' },
      pauseHint: '«Подольше» — примерно вдвое дольше самой фразы.',
    },
    onboarding: {
      step: (i, total) => `Шаг ${i} из ${total}`,
      welcome: 'Учите язык фразами: услышать, сказать, услышать.',
      name: 'Как к вам обращаться?',
      namePlaceholder: 'Ваше имя',
      native: 'На каком языке вы говорите?',
      course: 'Какой язык вы изучаете?',
      voices: 'Проверяем голоса',
      voicesChecking: 'Ищем голоса на этом устройстве…',
      voiceOk: (language, name) => `${language}: ${name}`,
      voiceMissing: (language) => `${language}: на устройстве нет голоса`,
      voiceHint: 'Добавьте недостающий голос в настройках речи системы. Можно продолжить, но эти фразы не зазвучат, пока голоса нет.',
      test: (language) => `Проверить: ${language}`,
      testShort: 'Проверить',
      loop: 'Как это работает',
      loopSteps: (native, target) => [
        `Услышьте фразу: ${native}.`,
        `Скажите её вслух ${adverb(target)}, пока тихо.`,
        `Услышьте её: ${target}.`,
        'Оцените: «Не помню», «Трудно» или «Легко». Оценку можно менять пять минут.',
      ],
      next: 'Дальше',
      start: 'Начать с одной фразы',
      skip: 'Начать без примера',
    },
    summary: {
      title: 'Это занятие',
      phrases: 'Фразы',
      repetitions: 'Повторы',
      ratings: 'Оценки',
      pending: (c) => `ещё можно изменить: ${c}; их очки и следующее повторение учтутся через пять минут`,
      points: 'Заработано очков',
      passes: 'Прохождений очереди',
      nextDue: 'Следующее повторение',
      nothingDue: 'Пока ничего не запланировано',
      none: 'В этой сессии пока ничего не звучало.',
    },
    connection: {
      loading: 'Загружаем ваш курс…',
      offlineTitle: 'Loro не может связаться с сервером',
      offlineBody: 'Курс скачивается один раз, а потом работает без сети. Проверьте подключение и попробуйте снова.',
      retry: 'Попробовать снова',
    },
    account: {
      title: 'Аккаунт',
      signIn: 'Войти',
      signInTitle: 'Вход в Loro',
      signInBody: 'Создавайте наборы фраз, песни и обложки с ИИ, храните их в аккаунте и делитесь ими. Прогресс на этом устройстве останется как есть.',
      email: 'Эл. почта',
      emailPlaceholder: 'vy@primer.ru',
      sendCode: 'Прислать код на почту',
      sending: 'Отправляем…',
      codeTitle: 'Проверьте почту',
      codeBody: (email) => `Мы отправили шестизначный код на ${email}. Он действует 10 минут.`,
      code: 'Шестизначный код',
      verify: 'Войти',
      verifying: 'Входим…',
      resend: 'Прислать новый код',
      changeEmail: 'Другая почта',
      signedInAs: (email) => `Вы вошли как ${email}`,
      signOut: 'Выйти',
      signedOut: 'Вы вышли. Прогресс на этом устройстве сохранён.',
      welcome: 'Вы вошли',
      displayName: 'Имя на том, чем вы делитесь',
      displayNameHint: 'Показывается как «от …» на наборах и альбомах, которые вы сделали общими. Оставьте пустым, чтобы было «от ученика».',
      displayNameSaved: 'Имя сохранено',
      notNow: 'Не сейчас',
      needed: 'Войдите, чтобы создавать наборы, песни и обложки с ИИ и делиться ими.',
      errors: {
        badEmail: 'Это не похоже на адрес почты.',
        badCode: 'Код неверный или устарел.',
        tooMany: 'Слишком много попыток. Подождите несколько минут и попробуйте снова.',
        unavailable: 'Вход по почте на этом сервере не настроен.',
        offline: 'Loro не может связаться с сервером. Проверьте подключение.',
        generic: 'Что-то пошло не так. Попробуйте снова.',
      },
      today: 'Лимит на сегодня',
      usage: {
        phrases: (left, limit) => `Наборы фраз: осталось ${left} из ${limit}`,
        cover: (left, limit) => `Обложки: осталось ${left} из ${limit}`,
        song: (left, limit) => `Песни: осталось ${left} из ${limit}`,
      },
      kept: (sets, albums) =>
        `${n(sets, { one: `${sets} набор`, few: `${sets} набора`, many: `${sets} наборов`, other: `${sets} набора` })} и ${n(albums, { one: `${albums} альбом`, few: `${albums} альбома`, many: `${albums} альбомов`, other: `${albums} альбома` })} в аккаунте`,
      resets: (time) => `Обновится в ${time}`,
      spent: (time) => `Лимит на сегодня исчерпан. Он обновится в ${time}.`,
      writers: 'Кто создаёт это на этом сервере',
      writer: {
        claude: 'Claude (ИИ)',
        bank: 'Банк фраз Loro (ИИ не настроен)',
        pattern: 'Нарисованные узоры (ИИ не настроен)',
        phrases: 'Ваши фразы как текст (ИИ не настроен)',
        elevenlabs: 'Поёт ElevenLabs Music',
        demo: 'Демо-звук (музыка не настроена)',
      },
      writerKind: { phrases: 'Фразы', cover: 'Обложки', lyrics: 'Текст', music: 'Звук' },
    },
    tabs: {
      home: 'Главная',
      phrases: 'Фразы',
      music: 'Музыка',
      create: 'Создать',
      library: 'Библиотека',
    },
    share: {
      visibility: 'Кто может видеть',
      private: 'Только вы',
      privateDetail: 'В вашем аккаунте, на ваших устройствах',
      link: 'Все, у кого есть ссылка',
      linkDetail: 'Не в списках; открывается по ссылке',
      public: 'Все',
      publicDetail: 'В Сообществе вашего курса',
      share: 'Поделиться',
      shareMessage: (title, url) => `${title} в Loro: ${url}`,
      copied: 'Ссылка скопирована',
      makeShareable: 'Это видите только вы. Выберите, кто может видеть, прежде чем делиться.',
      by: (name) => `от ${name}`,
      byLearner: 'от ученика',
      yours: 'Ваше',
      save: 'Сохранить в библиотеку',
      saved: 'В вашей библиотеке',
      unsave: 'Убрать из библиотеки',
      savedToast: 'Сохранено в библиотеку',
      unsavedToast: 'Убрано из библиотеки',
      delete: 'Удалить',
      deleteSetConfirm: (title) => `Удалить «${title}» из аккаунта? Те, с кем вы им поделились, тоже его потеряют. Прогресс по его фразам сохранится.`,
      deleteAlbumConfirm: (title) => `Удалить альбом «${title}» и его песни?`,
      deleted: 'Удалено',
      cover: 'Новая обложка',
      coverMaking: 'Рисуем обложку…',
      coverBy: { claude: 'Обложка от Claude', pattern: 'Нарисованный узор' },
      changed: 'Сохранено',
      notFound: 'Эта ссылка ничего не открывает. Возможно, её сделали личной или удалили.',
      opening: 'Открываем…',
    },
    community: {
      title: 'Сообщество',
      sets: 'Общие наборы',
      albums: 'Общие альбомы',
      emptySets: 'В этом курсе ещё никто не поделился набором. Создайте свой и выберите «Все».',
      emptyAlbums: 'В этом курсе ещё никто не поделился альбомом.',
      search: 'Поиск по общим наборам',
      offline: 'Для Сообщества нужна сеть.',
    },
    phrasesTab: {
      title: 'Фразы',
      course: 'Курс Loro',
      yourSets: 'Ваши наборы',
      savedSets: 'Сохранённые наборы',
      makeSet: 'Создать набор с ИИ',
      signInToMake: 'Войдите, чтобы создавать наборы с ИИ',
    },
    music: {
      title: 'Музыка',
      loro: 'От Loro',
      yours: 'Ваши альбомы',
      saved: 'Сохранённые альбомы',
      songs: (c) => n(c, { one: `${c} песня`, few: `${c} песни`, many: `${c} песен`, other: `${c} песни` }),
      empty: 'В этом курсе пока нет альбомов.',
      noSongs: 'Здесь пока нет песен.',
      loroAlbum: 'Каждый набор Loro из этого курса, спетый.',
      makeSong: 'Создать песню',
      album: 'Альбом',
      playAlbum: 'Слушать альбом',
      playSong: (title) => `Слушать ${title}`,
      demoSound: 'Демо-звук',
      demoNote: 'Этот инструментал сделал сервер; строки текста подсвечиваются по ходу. Песни будут петься, когда настроят музыкальный сервис.',
      sung: 'Спета',
      lyrics: 'Текст',
      lyricsBy: { claude: 'Текст от Claude', phrases: 'Текст: фразы набора' },
      meanings: 'Значения',
      showMeanings: 'Показать значения',
      hideMeanings: 'Скрыть значения',
      section: { verse: 'Куплет', chorus: 'Припев', bridge: 'Бридж' },
      rendering: 'Создаём песню…',
      renderingNote: 'Это займёт немного времени. Можно уйти с этого экрана: песня продолжит создаваться.',
      failed: 'Эту песню не удалось создать.',
      nowPlaying: 'Сейчас звучит',
      previous: 'Предыдущая песня',
      next: 'Следующая песня',
      openSet: 'Открыть набор',
      fromSet: (title) => `Из набора «${title}»`,
      loadFailed: 'Альбом не удалось загрузить.',
      style: {
        modern_pop: 'Поп',
        acoustic_folk: 'Фолк',
        gentle_ballad: 'Баллада',
        upbeat_kids: 'Подпевка',
      },
    },
    create: {
      title: 'Создать',
      intro: 'Создавайте свои наборы фраз, песни и обложки с ИИ. Всё созданное — ваше: держите это при себе, делитесь ссылкой или опубликуйте для всех.',
      phrasesTitle: 'Набор фраз',
      phrasesBody: 'Назовите тему или вставьте текст. ИИ напишет фразы с заметками; оставьте те, что нужны.',
      songTitle: 'Песня из набора',
      songBody: 'Ваши фразы, спетые. Слушайте их в песне и следите за текстом.',
      coverTitle: 'Обложки',
      coverBody: 'У каждого вашего набора и альбома может быть своя нарисованная обложка.',
      left: (c) => n(c, { one: `Осталась ${c} на сегодня`, few: `Осталось ${c} на сегодня`, many: `Осталось ${c} на сегодня`, other: `Осталось ${c} на сегодня` }),
      none: 'На сегодня не осталось',
      pickSet: 'Какой набор?',
      pickSetEmpty: 'В этом курсе пока нет наборов.',
      pickStyle: 'Стиль',
      pickAlbum: 'Альбом',
      newAlbum: 'Новый альбом',
      songTitleLabel: 'Название песни',
      makeSong: 'Создать песню',
      songStarted: 'Песня создаётся',
      saveToAccount: 'Сохранить в аккаунт',
      savedToAccount: 'Сохранено в аккаунт',
      setTitle: 'Название',
      setDescription: 'Для чего он (необязательно)',
      withCover: 'Нарисовать обложку',
      signedOutSave: 'Сохранено на этом устройстве. Войдите, чтобы хранить это в аккаунте и делиться.',
      from: { claude: 'Написано Claude', bank: 'Из банка фраз Loro' },
      bankOnly: 'На этом сервере ИИ не настроен, поэтому эти фразы из банка фраз Loro.',
      noMatch: 'В банке фраз нет ничего на эту тему. Попробуйте одну из этих:',
    },
    error: {
      title: 'Что-то пошло не так',
      body: 'Обычно помогает перезагрузка, прогресс при этом сохраняется. Если ошибка повторяется, сохранённый прогресс может не подходить к этой версии: скопируйте его, если хотите сохранить, и сбросьте, чтобы начать заново на этом устройстве.',
      reload: 'Перезагрузить',
      part: 'Эту часть экрана не удалось показать. Ваш прогресс в сохранности.',
      copy: 'Скопировать прогресс в JSON',
      copied: 'Скопировано',
      reset: 'Сбросить прогресс',
    },
  };
}
