//! Golden values are generated by the official py-fsrs v6.3.2 package, not this crate.

use loro_core::fsrs::{review, FsrsState, Grade};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    package: String,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    state: FsrsState,
    grade: Grade,
    at_ms: i64,
    expected: FsrsState,
}

#[test]
fn fsrs_official_reference_reviews_match_at_the_storage_boundary() {
    let fixtures: Fixtures =
        serde_json::from_str(include_str!("fixtures/fsrs_v6_3_2.json")).unwrap();
    assert_eq!(fixtures.package, "fsrs==6.3.2");
    assert!(fixtures.cases.len() >= 40);
    for case in fixtures.cases {
        let actual = review(case.state, case.grade, case.at_ms).unwrap();
        assert_eq!(actual.due, case.expected.due, "{} due", case.name);
        assert_eq!(
            actual.last_review, case.expected.last_review,
            "{} last review",
            case.name
        );
        assert_eq!(actual.lapses, case.expected.lapses, "{} lapses", case.name);
        // f64 transcendental operations may vary in the last bit by architecture.
        // The bound is one f32 epsilon relative to the stored reference value.
        for (field, observed, expected) in [
            ("stability", actual.stability, case.expected.stability),
            ("difficulty", actual.difficulty, case.expected.difficulty),
        ] {
            assert!(
                (observed - expected).abs() <= expected.abs().max(1.0) * f32::EPSILON,
                "{} {field}: expected {expected}, got {observed}",
                case.name
            );
        }
    }
}
