import { describe, expect, it } from 'vitest'
import { space, typography } from '@loro/design-tokens'
import {
  BADGE_PAD_X,
  BADGE_PAD_Y,
  BURST_OFFSETS,
  DOCK_INSET,
  DOCK_MAX,
  DOCK_PAD_X,
  DOCK_PAD_Y,
  DOCK_RESERVE,
  DOCK_REVEAL_RESERVE,
  DRAWER_ABOVE_DOCK,
  RECEDDED_ABOVE_DOCK,
  AUTO_GAP,
  AUTO_MT,
  AUTO_PAD,
  CARD_GAP,
  COPY_GAP,
  TRACK_GAP,
  TRACK_PAD_Y,
  CARD_GUTTER,
  CARD_PAD,
  CARD_RADIUS,
  CHEVRON_FACE,
  CHEVRON_SIZE,
  DECK_LINE,
  DECK_TITLE,
  ECHO,
  HEAR_FACE,
  EQ_BAR,
  EQ_H,
  EQ_MARK,
  EQ_MT,
  INDEX_FACE,
  INDEX_TRACK,
  MEANING,
  MEANING_LINE,
  MEANING_MT,
  RESP_MT,
  TAGS_MB,
  DUE_CHIP_WEIGHT,
  LABEL_SM_WEIGHT,
  PHRASE_LINE,
  PHRASE_TITLE,
  PHRASE_TRACK,
  PHRASE_TRACK_RECEDED,
  TAG_PAD_X,
  TAG_PAD_Y,
  reviewIndex,
  DRAWER_GAP,
  DRAWER_MT,
  DRAWER_PAD,
  DRAWER_RADIUS,
  TAB_BAR,
  TAB_BAR_PT,
  TAB_BAR_PX,
  TAB_FACE,
  TAB_GAP,
  TAB_MARK,
  TAB_MARK_GRAMMAR,
  TAB_MARK_MNEMONIC,
  TAB_MARK_PHONETICS,
  TAB_ON_WEIGHT,
  TAB_PB,
  TAB_WEIGHT,
  TAB_RULE,
  TAB_X,
  GRADE_FACE,
  GRADE_FACE_LINE,
  GRADE_FACE_TRACK,
  GRADE_GAP,
  GRADE_INNER_DIR,
  GRADE_INNER_GAP,
  GRADE_PAD_X,
  GRADE_PAD_Y,
  HERO_GAP,
  HERO_INNER_GAP,
  HERO_PAD,
  HERO_PAD_BOTTOM,
  HERO_SUB_MT,
  HERO_TITLE,
  HERO_TITLE_LINE,
  HERO_TITLE_TRACK,
  ICON,
  MINI_COPY_GAP,
  MINI_KICKER_WEIGHT,
  MINI_LEAD_GAP,
  MINI_PLAY_ML,
  PLAYER_GAP,
  MINI_PAUSE_H,
  MINI_PAUSE_W,
  MINI_PLAY,
  MINI_PLAY_FACE,
  PLAY_TRI_H,
  PLAY_TRI_W,
  MODE_PAD_X,
  MODE_PAD_Y,
  NOTE_PAD,
  NOTE_RADIUS,
  BACK,
  BACK_FACE,
  BACK_NUDGE,
  HEADER_GUTTER,
  HEADER_H,
  HEADER_TITLE_TRACK,
  PACK_PAUSE_H,
  PACK_PAUSE_W,
  PACK_PLAY_FACE,
  PACK_PLAY_TRI_H,
  PACK_PLAY_TRI_W,
  PLAY,
  LOVE_FACE,
  LOVE_ROW_PT,
  PLAY_CLUSTER_GAP,
  PLAY_ROW_PT,
  PLAYER_PAD,
  SHUFFLE,
  SLEEVE,
  SLEEVE_GAP,
  SLEEVE_GLYPH,
  SLEEVE_RADIUS,
  STATS_PAD_X,
  STATS_PAD_Y,
  STATS_RADIUS,
  THUMB,
  THUMB_RADIUS,
} from './geometry'
import {
  STAGE_PILL_GRAMMAR,
  STAGE_PILL_MNEMONIC,
  STAGE_PILL_PHONETICS,
} from '../_stream/geometry'

describe('review geometry', () => {
  it('keeps the named HTML measurements without rounding them onto the space scale', () => {
    expect(SLEEVE).toBe(112)
    expect(SLEEVE_GLYPH).toBe(72)
    expect(SLEEVE_RADIUS).toBe(12)
    expect(SLEEVE_GAP).toBe(16)
    expect(PLAY).toBe(56)
    expect(PACK_PLAY_FACE).toBe(30)
    expect(PACK_PLAY_TRI_W).toBe(30)
    expect(PACK_PLAY_TRI_H).toBe(15)
    expect(PACK_PAUSE_W).toBe(4)
    expect(PACK_PAUSE_H).toBe(30)
    expect(SHUFFLE).toBe(20)
    expect(HERO_PAD).toBe(16)
    expect(HERO_PAD_BOTTOM).toBe(24)
    expect(HERO_GAP).toBe(24)
    expect(HERO_INNER_GAP).toBe(16)
    expect(HERO_INNER_GAP).toBe(space['4'])
    expect(HERO_TITLE).toBe(30)
    expect(HERO_TITLE_LINE).toBe(36)
    expect(HERO_TITLE_TRACK).toBe(-0.45)
    expect(HERO_SUB_MT).toBe(2)
    expect(HERO_SUB_MT).toBe(space['0.5'])
    expect(BADGE_PAD_X).toBe(8)
    expect(BADGE_PAD_Y).toBe(2)
    expect(STATS_PAD_X).toBe(8)
    expect(STATS_PAD_Y).toBe(6)
    expect(STATS_RADIUS).toBe(8)
    expect(LOVE_ROW_PT).toBe(4)
    expect(LOVE_ROW_PT).toBe(space['1'])
    expect(LOVE_FACE).toBe(18)
    expect(PLAY_ROW_PT).toBe(4)
    expect(PLAY_CLUSTER_GAP).toBe(8)
    expect(PLAY_CLUSTER_GAP).toBe(space['2'])
    expect(MODE_PAD_X).toBe(16)
    expect(MODE_PAD_Y).toBe(10)
    expect(GRADE_FACE).toBe(12)
    expect(GRADE_FACE_LINE).toBe(16)
    expect(GRADE_FACE_TRACK).toBe(0.3)
    expect(ICON).toBe(36)
    expect(BACK).toBe(44)
    expect(BACK_FACE).toBe(24)
    expect(BACK_NUDGE).toBe(-8)
    expect(BACK_NUDGE).toBe(-space['2'])
    expect(HEADER_H).toBe(64)
    expect(HEADER_GUTTER).toBe(16)
    expect(HEADER_TITLE_TRACK).toBe(-0.5)
    expect(HEADER_GUTTER).toBe(HERO_PAD)
    expect(HEADER_GUTTER).toBe(space['4'])
    expect(DOCK_INSET).toBe(12)
    expect(DOCK_MAX).toBe(384)
    expect(DOCK_PAD_X).toBe(6)
    expect(DOCK_PAD_Y).toBe(4)
    expect(GRADE_GAP).toBe(6)
    expect(GRADE_GAP).toBe(space['1.5'])
    expect(GRADE_INNER_GAP).toBe(6)
    expect(GRADE_INNER_GAP).toBe(space['1.5'])
    expect(GRADE_INNER_DIR).toBe('row')
    expect(GRADE_FACE).toBe(12)
    expect(GRADE_FACE_LINE).toBe(16)
    expect(GRADE_FACE_TRACK).toBe(0.3)
    expect(GRADE_FACE).toBe(typography.scale.captionSm.size)
    expect(GRADE_FACE_LINE).toBe(
      Math.round(typography.scale.captionSm.size * typography.scale.captionSm.lineHeight),
    )
    expect(GRADE_FACE_TRACK).not.toBe(typography.scale.captionSm.tracking)
    expect(GRADE_PAD_X).toBe(14)
    expect(GRADE_PAD_Y).toBe(0)
    expect(THUMB).toBe(44)
    expect(THUMB_RADIUS).toBe(8)
    expect(PLAYER_PAD).toBe(10)
    expect(MINI_PLAY).toBe(40)
    expect(MINI_PLAY_FACE).toBe(20)
    expect(PLAY_TRI_W).toBe(20)
    expect(PLAY_TRI_H).toBe(10)
    expect(MINI_PAUSE_W).toBe(4)
    expect(MINI_PAUSE_H).toBe(20)
    expect(MINI_COPY_GAP).toBe(0)
    expect(MINI_KICKER_WEIGHT).toBe('700')
    expect(MINI_LEAD_GAP).toBe(8)
    expect(MINI_LEAD_GAP).toBe(space['2'])
    expect(PLAYER_GAP).toBe(0)
    expect(MINI_PLAY_ML).toBe(8)
    expect(MINI_PLAY_ML).toBe(space['2'])
    expect(CARD_PAD).toBe(16)
    expect(CARD_RADIUS).toBe(16)
    expect(CARD_GAP).toBe(8)
    expect(COPY_GAP).toBe(0)
    expect(TAGS_MB).toBe(4)
    expect(TAGS_MB).toBe(space['1'])
    expect(DUE_CHIP_WEIGHT).toBe('600')
    expect(LABEL_SM_WEIGHT).toBe('700')
    expect(AUTO_MT).toBe(4)
    expect(AUTO_MT).toBe(space['1'])
    expect(AUTO_PAD).toBe(8)
    expect(AUTO_PAD).toBe(space['2'])
    expect(AUTO_GAP).toBe(6)
    expect(AUTO_GAP).toBe(space['1.5'])
    expect(TRACK_GAP).toBe(8)
    expect(TRACK_GAP).toBe(space['2'])
    expect(TRACK_GAP).not.toBe(16)
    expect(TRACK_PAD_Y).toBe(16)
    expect(TRACK_PAD_Y).toBe(space['4'])
    expect(TRACK_PAD_Y).not.toBe(24)
    expect(CARD_GUTTER).toBe(16)
    expect(EQ_MARK).toBe(28)
    expect(EQ_H).toBe(14)
    expect(EQ_MT).toBe(2)
    expect(INDEX_FACE).toBe(12)
    expect(INDEX_FACE).toBe(typography.scale.captionSm.size)
    expect(INDEX_TRACK).toBe(0.3)
    expect(INDEX_TRACK).toBe(GRADE_FACE_TRACK)
    expect(EQ_BAR).toBe(2)
    expect(ECHO).toBe(40)
    expect(HEAR_FACE).toBe(18)
    expect(CHEVRON_SIZE).toBe(32)
    expect(CHEVRON_FACE).toBe(20)
    expect(PHRASE_TITLE).toBe(20)
    expect(PHRASE_LINE).toBe(28)
    expect(PHRASE_TRACK).toBe(-0.5)
    expect(PHRASE_TRACK_RECEDED).toBe(0)
    expect(MEANING).toBe(12)
    expect(MEANING_LINE).toBe(18)
    expect(MEANING).not.toBe(typography.scale.bodySm.size)
    expect(MEANING_LINE).not.toBe(
      Math.round(typography.scale.bodySm.size * typography.scale.bodySm.lineHeight),
    )
    expect(MEANING_MT).toBe(2)
    expect(MEANING_MT).toBe(space['0.5'])
    expect(RESP_MT).toBe(2)
    expect(RESP_MT).toBe(space['0.5'])
    expect(DECK_TITLE).toBe(24)
    expect(DECK_LINE).toBe(32)
    expect(TAG_PAD_X).toBe(8)
    expect(TAG_PAD_Y).toBe(2)
    expect(DRAWER_PAD).toBe(14)
    expect(DRAWER_RADIUS).toBe(12)
    expect(DRAWER_GAP).toBe(10)
    expect(DRAWER_MT).toBe(6)
    expect(NOTE_PAD).toBe(10)
    expect(NOTE_RADIUS).toBe(8)
    expect(DOCK_RESERVE).toBe(148)
    expect(TAB_BAR_PX).toBe(8)
    expect(TAB_BAR_PT).toBe(6)
    expect(TAB_X).toBe(10)
    expect(TAB_PB).toBe(8)
    expect(TAB_FACE).toBe(11)
    expect(TAB_WEIGHT).toBe('500')
    expect(TAB_ON_WEIGHT).toBe('600')
    expect(TAB_RULE).toBe(2)
    expect(TAB_GAP).toBe(6)
    expect(TAB_MARK).toBe(14)
    expect(TAB_MARK_MNEMONIC).toBe('💡')
    expect(TAB_MARK_GRAMMAR).toBe('📖')
    expect(TAB_MARK_PHONETICS).toBe('🗣️')
    expect(TAB_MARK_MNEMONIC).toBe(STAGE_PILL_MNEMONIC)
    expect(TAB_MARK_GRAMMAR).toBe(STAGE_PILL_GRAMMAR)
    expect(TAB_MARK_PHONETICS).toBe(STAGE_PILL_PHONETICS)
    expect(TAB_BAR).toBe(30)
    expect(DRAWER_ABOVE_DOCK).toBe(150)
    expect(DOCK_REVEAL_RESERVE).toBe(298)
    expect(RECEDDED_ABOVE_DOCK).toBe(114)
    expect(BURST_OFFSETS).toHaveLength(8)
    expect(reviewIndex(2)).toBe('02')
    expect(reviewIndex(10)).toBe('10')
  })
})
