// Bulgarian UI copy. Awaiting native review (see content/meta.json).
import type { Copy, Plural } from './en';

export function makeBg(n: Plural): Copy {
  const phrases = (c: number) => n(c, { one: `${c} фраза`, other: `${c} фрази` });
  const sets = (c: number) => n(c, { one: `${c} набор`, other: `${c} набора` });
  return {
    locale: 'bg-BG',
    common: {
      close: 'Затвори',
      back: 'Назад',
      cancel: 'Отказ',
      charsLeft: (c) => n(c, { one: `Остава ${c} знак`, other: `Остават ${c} знака` }),
      save: 'Запази',
      undo: 'Отмени',
      play: 'Пусни',
      pause: 'Пауза',
      delete: 'Изтрий',
      moreOptions: 'Още',
      phrases,
      sets,
      points: (c) => n(c, { one: `${c} точка`, other: `${c} точки` }),
      level: (level) => level,
      grade: { missed: 'Не се сетих', hard: 'Трудно', easy: 'Лесно' },
      register: { formal: 'Учтиво', informal: 'Неофициално', neutral: 'Неутрално' },
      tag: {
        politeness: 'Учтивост',
        question: 'Въпроси',
        request: 'Молби',
        numbers: 'Числа',
        food: 'Храна и напитки',
        directions: 'Посоки',
        social: 'Общуване',
      },
      fullPlay: (time) => `${time} при 1×`,
    },
    nav: {
      main: 'Главно меню',
      home: 'Начало',
      explore: 'Разгледай',
      library: 'Библиотека',
      settings: (name) => (name ? `${name}: настройки` : 'Настройки'),
      points: (c) => n(c, { one: `${c} точка`, other: `${c} точки` }),
      pointsShort: 'т.',
    },
    status: {
      new: 'Нова',
      listenedNotRated: 'Чута, без оценка',
      due: 'За преговор',
      learned: (pct) => `Научена · ${pct}%`,
      learning: (pct, when) => `${pct}% · отново ${when}`,
      set: { new: 'Нов', 'in-progress': 'Започнат', learned: 'Всичко научено' },
    },
    home: {
      firstRun: 'Чуйте фраза и я кажете сами, преди да я чуете отново.',
      learned: 'Научени',
      started: 'Започнати',
      today: (heard, rated) => `Днес: ${phrases(heard)} чути · ${rated} оценени`,
      reviewTitle: 'Преговор',
      reviewBody: (due) => n(due, { one: `${due} фраза е за преговор`, other: `${due} фрази са за преговор` }),
      reviewCapped: (shown) => `В това занимание — ${shown}-те най-отдавна чакащи.`,
      playPhrases: (c) => `Пусни ${phrases(c)}`,
      duration: (time) => `${time} при 1×`,
      startTitle: 'Започнете оттук',
      continueTitle: 'Продължете',
      continueBody: (title, learned, total) => `${title} · научени ${learned} от ${total}`,
      next: (c, when) => `Следва: ${phrases(c)} ${when}`,
      jumpBackIn: 'Върнете се',
      history: 'История',
      notStarted: 'Още незапочнати',
      demoTitle: 'Опитайте цикъла',
      demoBody: 'Една фраза: чуйте, кажете, чуйте.',
      demoButton: 'Пусни една фраза',
      courseDoneTitle: 'Всички фрази от курса са научени',
      courseDoneBody: 'Преговорите ще се върнат, когато им дойде времето. Дотогава добавете свои фрази или опитайте друг курс.',
      addOwn: 'Ваша фраза',
      otherCourse: 'Друг курс',
    },
    history: {
      title: 'История',
      empty: 'Все още нищо не е пускано.',
      mixed: 'Смесена опашка',
      run: (p, points) => `${phrases(p)} · +${points} т.`,
    },
    explore: {
      search: 'Търсене във фрази, бележки и теми',
      topics: 'Теми',
      levels: 'Нива',
      tags: 'Етикети',
      allSets: 'Всички набори',
      sets,
      phrases,
      noPhrases: (q) => `Няма фрази за „${q}“.`,
      noSets: 'Няма подходящи набори.',
      addAsOwn: (q) => `Добавете „${q}“ като своя фраза`,
      removeFilter: (label) => `Махни филтъра: ${label}`,
      clearFilters: 'Изчисти филтрите',
      quickPlay: (title) => `Пусни „${title}“`,
      filtered: 'Избрани набори',
    },
    set: {
      phrasesHeading: 'Фрази',
      summary: (total, learned, due) => `${phrases(total)} · научени ${learned}${due > 0 ? ` · за преговор ${due}` : ''}`,
      sort: { set: 'Ред в набора', az: 'А–Я', due: 'Първо за преговор', weakest: 'Първо най-слабите' },
      sortTitle: 'Подреждане на фразите',
      playsIn: (order) => `Ред: ${order}`,
      playAll: (title) => `Пусни „${title}“`,
      pauseAll: (title) => `Пауза: „${title}“`,
      playDueNew: (c) => `Само нови и за преговор (${c})`,
      shufflePlay: 'Разбъркано',
      like: 'Харесай набора',
      duration: (time) => `Целият набор: ${time} при 1×`,
      playNext: 'Пусни следващо',
      addToQueue: 'Добави в опашката',
      share: 'Сподели връзка',
      linkCopied: 'Връзката е копирана',
      copyUnavailable: 'Копирането не е достъпно тук',
      rename: 'Преименувай',
      delete: 'Изтрий набора',
      deleted: 'Наборът е изтрит',
      own: 'Ваш набор',
      ownEmpty: 'Добавяйте фрази от подробностите им (⋮) или от плейъра.',
      findPhrases: 'Намерете фрази',
      addedNext: 'Ще е следваща',
      addedEnd: 'Добавено в опашката',
      notFound: 'Този набор не е достъпен.',
      otherCourse: (language) => `Този набор е от курса по ${language}.`,
      switchCourse: (language) => `Учи ${language}`,
    },
    phrase: {
      details: (text) => `Подробности: ${text}`,
      play: (text) => `Пусни: ${text}`,
      playNext: 'Пусни следваща',
      addToQueue: 'Добави в опашката',
      like: 'Харесай',
      liked: 'Харесана',
      likeLabel: 'Харесай фразата',
      addToSet: 'Добави в набор…',
      heard: (c) => `чута ${c}×`,
      notes: { mnemonic: 'Подсказка', grammar: 'Граматика', pronunciation: 'Звуци' },
      notesTitle: 'Бележки',
      notesInEnglish: 'Засега бележките са на английски.',
      words: 'Докоснете дума, за да видите значението ѝ.',
      glossHint: 'Показва значението',
      edit: 'Редактирай фразата',
      delete: 'Изтрий фразата',
      deleted: 'Фразата е изтрита',
      removeFromSet: 'Махни от набора',
      removedFromSet: 'Махната от набора',
      moveUp: 'Премести нагоре в набора',
      moveDown: 'Премести надолу в набора',
      yours: 'Ваша фраза',
    },
    addToSet: {
      title: 'Добави в набор',
      newSet: 'Нов набор…',
      added: (title) => `Добавено в „${title}“`,
      already: (title) => `Вече е в „${title}“`,
      alreadyHere: 'Вече е в този набор',
      none: 'Все още нямате свои набори.',
    },
    createSet: {
      title: 'Нов набор',
      renameTitle: 'Преименувай набора',
      name: 'Име',
      create: 'Създай',
      created: (title) => `Създаден е „${title}“`,
      taken: 'Набор с това име вече съществува.',
    },
    addPhrase: {
      title: 'Ваша фраза',
      target: (language) => `На ${language}`,
      native: (language) => `На ${language}`,
      hint: 'Звучи с гласа на устройството.',
      add: 'Добави фразата',
      added: 'Фразата е добавена',
      editTitle: 'Редактиране на фразата',
      edited: 'Фразата е обновена',
      duplicate: 'Вече е в курса:',
    },
    player: {
      dialog: 'Сега звучи',
      close: 'Затвори плейъра',
      openQueue: 'Отвори опашката',
      summary: 'Обобщение на заниманието',
      position: (i, total) => `${i} от ${total}`,
      hidden: (language) => `Текстът на ${language} е скрит, докато не го чуете`,
      steps: 'Стъпки',
      yourTurn: 'Ваш ред',
      instruction: {
        native: (language) => `Слушайте на ${language}`,
        pause: (language) => `Ваш ред — кажете го на ${language}`,
        target: (language) => `Чуйте го на ${language}`,
        rate: 'Оценете или изчакайте',
      },
      paused: 'Пауза',
      repetition: (r, total) => `Повторение ${r} от ${total}`,
      howDidItGo: 'Как се получи?',
      rated: (grade, when) => `Оценка „${grade}“ — отново ${when}`,
      changeFor: (time) => `Може да я смените или отмените още ${time}`,
      previous: 'Предишна фраза',
      next: 'Следваща фраза',
      repeats: {
        auto: 'Повторения: автоматично (3 за нови или несигурни, 1 за усвоени)',
        one: 'Повторения: 1',
        three: 'Повторения: 3',
      },
      playMode: {
        repeat: 'Накрая: пусни опашката отново',
        continue: 'Накрая: продължи със следващите фрази',
      },
      speed: 'Скорост',
      keys: 'Клавиши: интервал — пусни или пауза · ← → предишна, следваща · 1 2 3 — оценка',
      audioError: (language) =>
        `На устройството няма глас за ${language}, затова фразата не звучи. Добавете го в настройките за реч на системата и натиснете „Пусни“.`,
      noVoice: 'Няма глас за този език',
      audioSilent: 'Речта спря, преди фразата да прозвучи. Натиснете „Пусни“, за да опитате отново.',
      silent: 'Речта спря — натиснете „Пусни“',
      voice: (name) => `Глас: ${name}`,
      changeVoice: (name) => `Глас: ${name}. Смени гласа`,
    },
    toast: {
      updateReady: 'Има нова версия на Loro',
      reload: 'Презареди',
      dismiss: 'Затвори съобщението',
      learned: (points) => `Научена · +${points}`,
      passComplete: 'Опашката е изсвирена докрай',
      removed: 'Махнато от опашката',
      cleared: 'Опашката е изчистена',
      saved: (title) => `Запазено като „${title}“`,
      storageFull: 'Паметта на устройството за Loro е пълна, затова новият напредък не се запазва.',
      storageUnavailable: 'Този браузър не позволява на Loro да запазва напредъка на устройството.',
    },
    queue: {
      title: 'Опашка',
      back: 'Назад към плейъра',
      left: (c) => `Остават ${c}`,
      nowPlaying: 'Сега звучи',
      upNext: (c) => `Следват · ${c}`,
      nothing: 'След тази фраза няма нищо.',
      hint: 'Плъзнете надясно, за да пуснете сега, наляво — за да махнете. Хванете дръжката, за да пренаредите, или я докоснете за още.',
      handleHint: 'Enter — още действия; стрелки нагоре и надолу — премести, Delete — махни.',
      moveUp: 'Премести нагоре',
      moveDown: 'Премести надолу',
      removeFromQueue: 'Махни от опашката',
      moved: (position, total) => `Преместено на място ${position} от ${total}`,
      playNow: (text) => `Пусни сега: ${text}`,
      move: (text) => `Премести: ${text}`,
      swipePlay: 'Пусни',
      swipeRemove: 'Махни',
      previously: 'Вече звучали',
      playNext: (text) => `Пусни следваща: ${text}`,
      clear: 'Изчисти опашката',
      saveAsSet: 'Запази като набор',
      shuffle: 'Разбъркай следващите',
      defaultSetName: 'Моята опашка',
    },
    library: {
      learned: 'Научени',
      learnedNote: (days, recalls) => `Помни се ${days}+ дни, след ${recalls}+ сещания`,
      recall: 'Памет сега',
      recallNote: (rated) => n(rated, { one: `Средно за ${rated} оценена фраза`, other: `Средно за ${rated} оценени фрази` }),
      recallNone: 'Първо оценете фраза',
      started: 'Започнати',
      startedNote: 'Чути или оценени поне веднъж',
      phrasesSegment: 'Фрази',
      setsSegment: 'Набори',
      filters: {
        liked: 'Харесани',
        mine: 'Мои',
        due: 'За преговор',
        learning: 'Учат се',
        missed: 'Скоро несетени',
        learned: 'Научени',
        ownSets: 'Мои набори',
        likedSets: 'Харесани набори',
      },
      empty: {
        liked: 'Докоснете сърцето на фраза, за да я пазите тук.',
        mine: 'Добавете своя фраза — ще звучи като всяка друга.',
        due: 'В момента няма нищо за преговор.',
        learning: 'Тук са фразите, които сте чули или оценили, но още не сте научили.',
        missed: 'Тук са фразите с оценка „Не се сетих“ от последната седмица.',
        learned: (days, recalls) =>
          `Една фраза е научена, когато се очаква да се помни ${days} дни или повече, след поне ${recalls} успешни сещания.`,
        ownSets: 'Създайте набор, за да групирате фрази по свой начин.',
        likedSets: 'Докоснете сърцето на набор, за да го пазите тук.',
      },
      playAll: (c) => `Пусни всички (${c})`,
      addPhrase: 'Ваша фраза',
      newSet: 'Нов набор',
      recallChart: 'Очаквана памет сега',
      recallBucket: (from, to) => `${from}–${to}%`,
      recallBelow: (to) => `под ${to}%`,
      recallChartEmpty: 'Оценете фраза, за да видите това.',
      bucketCount: (label, c) => `${label}: ${phrases(c)}`,
      weeklyChart: 'Научени по седмици',
      weekOf: (date, c) => `Седмицата от ${date}: научени ${c}`,
      progress: 'Напредък',
    },
    settings: {
      title: 'Настройки',
      switched: (language, queueCleared) => `Курс: ${language}${queueCleared ? '. Опашката е изчистена' : ''}`,
      profile: 'Профил',
      name: 'Име',
      native: 'Говоря',
      course: 'Уча',
      courseNote: 'Напредъкът се пази за всяка двойка езици. Щом превключите обратно, той се връща.',
      voices: 'Гласове',
      voiceAuto: (name) => `Автоматично (${name})`,
      accessibility: 'Екранен четец',
      announceEveryStep: 'Обявявай всяка стъпка',
      announceHint: 'Изключено: обявяват се само „Ваш ред“ и отговорът.',
    },
    onboarding: {
      step: (i, total) => `Стъпка ${i} от ${total}`,
      welcome: 'Учете език фраза по фраза: чуйте, кажете, чуйте.',
      name: 'Как да ви наричаме?',
      namePlaceholder: 'Вашето име',
      native: 'Какъв език говорите?',
      course: 'Какъв език учите?',
      voices: 'Проверка на гласовете',
      voicesChecking: 'Търсим гласове на това устройство…',
      voiceOk: (language, name) => `${language}: ${name}`,
      voiceMissing: (language) => `${language}: няма глас на това устройство`,
      voiceHint: 'Добавете липсващия глас в настройките за реч на системата. Може да продължите, но тези фрази няма да звучат дотогава.',
      test: (language) => `Изпробвай: ${language}`,
      testShort: 'Изпробвай',
      loop: 'Как работи',
      loopSteps: (native, target) => [
        `Чуйте фразата на ${native}.`,
        `Кажете я сами на ${target}, докато е тихо.`,
        `Чуйте я на ${target}.`,
        'Оценете как мина: „Не се сетих“, „Трудно“ или „Лесно“. Може да смените оценката в рамките на пет минути.',
      ],
      next: 'Напред',
      start: 'Започни с една фраза',
      skip: 'Започни без пример',
    },
    summary: {
      title: 'Това занимание',
      phrases: 'Фрази',
      repetitions: 'Повторения',
      ratings: 'Оценки',
      pending: (c) => `още могат да се сменят: ${c}; точките и следващият преговор се броят след пет минути`,
      points: 'Спечелени точки',
      passes: 'Пъти през опашката',
      nextDue: 'Следващ преговор',
      nothingDue: 'Все още нищо не е насрочено',
    },
    error: {
      title: 'Нещо се обърка',
      body: 'Презареждането обикновено помага и напредъкът се запазва. Ако се повтаря, запазеният напредък може да не пасва на тази версия: копирайте го, ако искате да го пазите, и нулирайте, за да започнете отначало на това устройство.',
      reload: 'Презареди',
      part: 'Тази част от екрана не можа да се покаже. Напредъкът ви е запазен.',
      copy: 'Копирай напредъка като JSON',
      copied: 'Копирано',
      reset: 'Нулирай напредъка',
    },
  };
}
