// Every learner-facing string, in English. bg.ts and ru.ts must have the same
// shape (the Copy type enforces it). Numbers arrive already formatted; plurals
// go through `n()` so each language can use its own plural rules.
import type { Grade } from '../core/fsrs';
import type { Level, Register, Tag } from '../content';
import type { PlayMode, SortKey } from '../state/types';
import type { PluralForms } from './plural';

export interface Plural {
  (count: number, forms: PluralForms): string;
}

export function makeEn(n: Plural) {
  return {
    locale: 'en-GB',
    common: {
      close: 'Close',
      back: 'Back',
      cancel: 'Cancel',
      charsLeft: (count: number) => n(count, { one: `${count} character left`, other: `${count} characters left` }),
      save: 'Save',
      undo: 'Undo',
      play: 'Play',
      pause: 'Pause',
      delete: 'Delete',
      moreOptions: 'More options',
      phrases: (count: number) => n(count, { one: `${count} phrase`, other: `${count} phrases` }),
      sets: (count: number) => n(count, { one: `${count} set`, other: `${count} sets` }),
      points: (count: number) => n(count, { one: `${count} point`, other: `${count} points` }),
      level: (level: Level) => level,
      grade: { missed: 'Missed', hard: 'Hard', easy: 'Easy' } satisfies Record<Grade, string>,
      register: { formal: 'Formal', informal: 'Informal', neutral: 'Neutral' } satisfies Record<Register, string>,
      tag: {
        politeness: 'Politeness',
        question: 'Questions',
        request: 'Requests',
        numbers: 'Numbers',
        food: 'Food & drink',
        directions: 'Directions',
        social: 'Social',
      } satisfies Record<Tag, string>,
      fullPlay: (time: string) => `${time} at 1×`,
    },
    nav: {
      main: 'Main',
      home: 'Home',
      explore: 'Explore',
      library: 'Library',
      settings: (name: string) => (name ? `${name}: settings` : 'Settings'),
      points: (count: number) => n(count, { one: `${count} point`, other: `${count} points` }),
      pointsShort: 'pts',
    },
    status: {
      new: 'New',
      listenedNotRated: 'Listened, not rated',
      due: 'Due now',
      learned: (pct: number) => `Learned · ${pct}%`,
      learning: (pct: number, when: string) => `${pct}% · next ${when}`,
      set: { new: 'New', 'in-progress': 'In progress', learned: 'All learned' },
    },
    home: {
      firstRun: 'Listen to a phrase, then say it before you hear it again.',
      learned: 'Learned',
      started: 'Started',
      today: (heard: number, rated: number) =>
        `Today: ${n(heard, { one: `${heard} phrase heard`, other: `${heard} phrases heard` })} · ${rated} rated`,
      reviewTitle: 'Review',
      reviewBody: (due: number) => n(due, { one: `${due} phrase is due`, other: `${due} phrases are due` }),
      reviewCapped: (shown: number) => `This session plays the ${shown} most overdue.`,
      playPhrases: (count: number) => n(count, { one: `Play ${count} phrase`, other: `Play ${count} phrases` }),
      duration: (time: string) => `${time} at 1×`,
      startTitle: 'Start here',
      continueTitle: 'Continue',
      continueBody: (title: string, learned: number, total: number) => `${title} · ${learned} of ${total} learned`,
      next: (count: number, when: string) => n(count, { one: `Next: ${count} phrase ${when}`, other: `Next: ${count} phrases ${when}` }),
      jumpBackIn: 'Jump back in',
      history: 'History',
      notStarted: 'Not started yet',
      demoTitle: 'Try the loop',
      demoBody: 'One phrase: hear it, say it, hear it.',
      demoButton: 'Play one phrase',
      courseDoneTitle: 'Every phrase in this course is learned',
      courseDoneBody: 'Reviews come back as they fall due. Meanwhile, add phrases of your own or try another course.',
      addOwn: 'Add your phrase',
      otherCourse: 'Try another course',
    },
    history: {
      title: 'History',
      empty: 'Nothing played yet.',
      mixed: 'Mixed queue',
      run: (phrases: number, points: number) =>
        `${n(phrases, { one: `${phrases} phrase`, other: `${phrases} phrases` })} · +${points} pts`,
    },
    explore: {
      search: 'Search phrases, notes and topics',
      topics: 'Topics',
      levels: 'Levels',
      tags: 'Tags',
      allSets: 'All sets',
      sets: (count: number) => n(count, { one: `${count} set`, other: `${count} sets` }),
      phrases: (count: number) => n(count, { one: `${count} phrase`, other: `${count} phrases` }),
      noPhrases: (query: string) => `No phrases match “${query}”.`,
      noSets: 'No sets match.',
      addAsOwn: (query: string) => `Add “${query}” as your phrase`,
      removeFilter: (label: string) => `Remove filter: ${label}`,
      clearFilters: 'Clear filters',
      quickPlay: (title: string) => `Play ${title}`,
      filtered: 'Filtered sets',
    },
    set: {
      phrasesHeading: 'Phrases',
      summary: (total: number, learned: number, due: number) =>
        `${n(total, { one: `${total} phrase`, other: `${total} phrases` })} · ${learned} learned${due > 0 ? ` · ${due} due` : ''}`,
      sort: { set: 'Set order', az: 'A–Z', due: 'Due first', weakest: 'Lowest recall first' } satisfies Record<SortKey, string>,
      sortTitle: 'Sort phrases',
      playsIn: (order: string) => `Plays in: ${order}`,
      playAll: (title: string) => `Play ${title}`,
      pauseAll: (title: string) => `Pause ${title}`,
      playDueNew: (count: number) => `Play due and new (${count})`,
      shufflePlay: 'Shuffle play',
      like: 'Like set',
      unlike: 'Unlike set',
      duration: (time: string) => `Full play ${time} at 1×`,
      playNext: 'Play next',
      addToQueue: 'Add to queue',
      share: 'Share link',
      linkCopied: 'Link copied',
      copyUnavailable: 'Copy is not available here',
      rename: 'Rename set',
      delete: 'Delete set',
      deleted: 'Set deleted',
      own: 'Your set',
      ownEmpty: 'Add phrases from their details (⋮) or from the player.',
      findPhrases: 'Find phrases',
      addedNext: 'Plays next',
      addedEnd: 'Added to queue',
      notFound: 'This set isn’t available.',
      otherCourse: (language: string) => `This set is in the ${language} course.`,
      switchCourse: (language: string) => `Learn ${language}`,
    },
    phrase: {
      details: (text: string) => `Details for ${text}`,
      play: (text: string) => `Play ${text}`,
      playNext: 'Play next',
      addToQueue: 'Add to queue',
      like: 'Like',
      liked: 'Liked',
      likeLabel: 'Like phrase',
      unlikeLabel: 'Unlike phrase',
      addToSet: 'Add to set…',
      heard: (count: number) => `heard ${count}×`,
      notes: { mnemonic: 'Memory tip', grammar: 'Grammar', pronunciation: 'Sounds' },
      notesTitle: 'Notes',
      notesInEnglish: 'Notes are in English for now.',
      words: 'Tap a word for its meaning.',
      wordMeaning: (word: string, gloss: string) => `${word}: ${gloss}`,
      edit: 'Edit phrase',
      delete: 'Delete phrase',
      deleted: 'Phrase deleted',
      removeFromSet: 'Remove from this set',
      removedFromSet: 'Removed from the set',
      moveUp: 'Move up in this set',
      moveDown: 'Move down in this set',
      yours: 'Your phrase',
    },
    addToSet: {
      title: 'Add to set',
      newSet: 'New set…',
      added: (title: string) => `Added to ${title}`,
      already: (title: string) => `Already in ${title}`,
      alreadyHere: 'Already in this set',
      none: 'You haven’t made a set yet.',
    },
    createSet: {
      title: 'New set',
      renameTitle: 'Rename set',
      name: 'Name',
      create: 'Create',
      created: (title: string) => `Created ${title}`,
      taken: 'A set with this name already exists.',
    },
    addPhrase: {
      title: 'Add your phrase',
      target: (language: string) => `In ${language}`,
      native: (language: string) => `In ${language}`,
      hint: 'It plays with the device voice.',
      add: 'Add phrase',
      added: 'Phrase added',
      editTitle: 'Edit your phrase',
      edited: 'Phrase updated',
      duplicate: 'Already in your course:',
    },
    player: {
      dialog: 'Now playing',
      close: 'Close player',
      openQueue: 'Open queue',
      summary: 'Session summary',
      position: (i: number, total: number) => `${i} of ${total}`,
      hidden: (language: string) => `${language} hidden until you hear it`,
      steps: 'Steps',
      yourTurn: 'Your turn',
      rateStep: 'Rate',
      instruction: {
        native: (language: string) => `Listen in ${language}`,
        pause: (language: string) => `Your turn — say it in ${language}`,
        target: (language: string) => `Hear it in ${language}`,
        rate: 'Rate it, or wait to go on',
      },
      paused: 'Paused',
      repetition: (r: number, total: number) => `Repetition ${r} of ${total}`,
      howDidItGo: 'How did saying it go?',
      gradeButton: (grade: string, interval: string) => `${grade} · ${interval}`,
      rated: (grade: string, when: string) => `Rated ${grade} — back ${when}`,
      changeFor: (time: string) => `Change or undo for ${time}`,
      counts: 'It counts when the window closes.',
      previous: 'Previous phrase',
      next: 'Next phrase',
      repeats: {
        auto: 'Repetitions: automatic (3 while new or shaky, 1 once it sticks)',
        one: 'Repetitions: 1',
        three: 'Repetitions: 3',
      },
      playMode: {
        repeat: 'At the end: play the queue again',
        continue: 'At the end: continue with the next phrases',
      } satisfies Record<PlayMode, string>,
      speed: 'Speed',
      keys: 'Keys: Space play or pause · ← → previous, next · 1 2 3 rate',
      audioError: (language: string) =>
        `This device has no ${language} voice, so the phrase can’t play. Add one in your system’s speech settings, then press Play.`,
      noVoice: 'No voice for this language',
      audioSilent: 'Speech stopped before the phrase played. Press Play to try again.',
      silent: 'Speech stopped — press Play',
      voice: (name: string) => `Voice: ${name}`,
      changeVoice: (name: string) => `Voice: ${name}. Change voice`,
      hide: 'Tap to reveal',
    },
    toast: {
      updateReady: 'A new version of Loro is ready',
      reload: 'Reload',
      dismiss: 'Dismiss message',
      learned: (points: number) => `Learned · +${points}`,
      passComplete: 'Queue played through',
      removed: 'Removed from queue',
      cleared: 'Queue cleared',
      saved: (title: string) => `Saved as ${title}`,
      storageFull: 'This device’s storage for Loro is full, so new progress isn’t being saved.',
      storageUnavailable: 'This browser isn’t letting Loro save progress on this device.',
    },
    queue: {
      title: 'Queue',
      back: 'Back to player',
      left: (count: number) => `${count} left`,
      nowPlaying: 'Now playing',
      upNext: (count: number) => `Up next · ${count}`,
      nothing: 'Nothing queued after this phrase.',
      hint: 'Swipe right to play now, left to remove. Drag the handle to reorder, or tap it for options.',
      handleHint: 'Enter for options; arrow up or down to move, Delete to remove.',
      moveUp: 'Move up',
      moveDown: 'Move down',
      removeFromQueue: 'Remove from queue',
      moved: (position: number, total: number) => `Moved to position ${position} of ${total}`,
      playNow: (text: string) => `Play ${text} now`,
      move: (text: string) => `Move ${text}`,
      swipePlay: 'Play now',
      swipeRemove: 'Remove',
      previously: 'Previously played',
      playNext: (text: string) => `Play ${text} next`,
      clear: 'Clear queue',
      saveAsSet: 'Save as set',
      shuffle: 'Shuffle up next',
      defaultSetName: 'My queue',
    },
    library: {
      learned: 'Learned',
      learnedNote: (days: number, recalls: number) => `Recall lasts ${days}+ days, after ${recalls}+ recalls`,
      recall: 'Recall now',
      recallNote: (rated: number) => n(rated, { one: `Average of ${rated} rated phrase`, other: `Average of ${rated} rated phrases` }),
      recallNone: 'Rate a phrase first',
      started: 'Started',
      startedNote: 'Heard or rated at least once',
      phrasesSegment: 'Phrases',
      setsSegment: 'Sets',
      filters: {
        liked: 'Liked',
        mine: 'Mine',
        due: 'Due',
        learning: 'Learning',
        missed: 'Missed recently',
        learned: 'Learned',
        ownSets: 'My sets',
        likedSets: 'Liked sets',
      },
      empty: {
        liked: 'Tap the heart on a phrase to keep it here.',
        mine: 'Add a phrase of your own and it plays like any other.',
        due: 'Nothing is due right now.',
        learning: 'Phrases you have heard or rated but not yet learned show here.',
        missed: 'Phrases rated Missed in the last week show here.',
        learned: (days: number, recalls: number) =>
          `A phrase is learned once recall is expected to last ${days} days or more, after at least ${recalls} successful recalls.`,
        ownSets: 'Make a set to group phrases your way.',
        likedSets: 'Tap the heart on a set to keep it here.',
      },
      playAll: (count: number) => `Play all (${count})`,
      addPhrase: 'Add your phrase',
      newSet: 'New set',
      recallChart: 'Predicted recall now',
      recallBucket: (from: number, to: number) => `${from}–${to}%`,
      recallBelow: (to: number) => `under ${to}%`,
      recallChartEmpty: 'Rate a phrase to see this.',
      bucketCount: (label: string, count: number) => `${label}: ${n(count, { one: `${count} phrase`, other: `${count} phrases` })}`,
      weeklyChart: 'Learned per week',
      weekOf: (date: string, count: number) => `Week of ${date}: ${count} learned`,
      progress: 'Progress',
    },
    settings: {
      title: 'Settings',
      switched: (language: string, queueCleared: boolean) => `Now learning ${language}${queueCleared ? '. The queue was cleared' : ''}`,
      profile: 'Profile',
      name: 'Name',
      native: 'I speak',
      course: 'I’m learning',
      courseNote: 'Progress is kept for each pair of languages. Switching back brings it back.',
      accessibility: 'Screen reader',
      voices: 'Voices',
      voiceAuto: (name: string) => `Automatic (${name})`,
      announceEveryStep: 'Announce every step',
      announceHint: 'Off: only “Your turn” and the reveal are announced.',
    },
    onboarding: {
      step: (i: number, total: number) => `Step ${i} of ${total}`,
      welcome: 'Learn a language by the phrase: hear it, say it, hear it.',
      name: 'What should we call you?',
      namePlaceholder: 'Your name',
      native: 'Which language do you speak?',
      course: 'Which language are you learning?',
      voices: 'Checking voices',
      voicesChecking: 'Looking for voices on this device…',
      voiceOk: (language: string, name: string) => `${language}: ${name}`,
      voiceMissing: (language: string) => `${language}: no voice on this device`,
      voiceHint: 'Add the missing voice in your system’s speech settings. You can go on, but those phrases won’t play until then.',
      test: (language: string) => `Test ${language}`,
      testShort: 'Test',
      loop: 'How it works',
      loopSteps: (native: string, target: string) => [
        `Hear the phrase in ${native}.`,
        `Say it yourself in ${target} while it’s quiet.`,
        `Hear it in ${target}.`,
        'Rate how it went: Missed, Hard or Easy. You can change it for five minutes.',
      ],
      next: 'Continue',
      start: 'Start with one phrase',
      skip: 'Start without the demo',
    },
    summary: {
      title: 'This session',
      phrases: 'Phrases',
      repetitions: 'Repetitions',
      ratings: 'Ratings',
      pending: (count: number) => `${count} still changeable: their points and next review count once the five minutes are up`,
      points: 'Points earned',
      passes: 'Times through the queue',
      nextDue: 'Next review',
      nothingDue: 'Nothing scheduled yet',
    },
    error: {
      title: 'Something went wrong',
      body: 'Reloading usually fixes it, and your progress is kept. If it keeps happening, the progress saved on this device may not fit this version: copy it first if you want to keep it, then reset to start from zero on this device.',
      reload: 'Reload',
      part: 'This part of the screen couldn’t be shown. Your progress is safe.',
      copy: 'Copy progress JSON',
      copied: 'Copied',
      reset: 'Reset progress',
    },
  };
}

export type Copy = ReturnType<typeof makeEn>;
