// Russian UI copy. Awaiting native review (see content/meta.json).
import type { Copy, Plural } from './en';

export function makeRu(n: Plural): Copy {
  const phrases = (c: number) => n(c, { one: `${c} фраза`, few: `${c} фразы`, many: `${c} фраз`, other: `${c} фразы` });
  return {
    locale: 'ru-RU',
    common: {
      close: 'Закрыть',
      back: 'Назад',
      cancel: 'Отмена',
      save: 'Сохранить',
      undo: 'Отменить',
      play: 'Играть',
      pause: 'Пауза',
      delete: 'Удалить',
      moreOptions: 'Ещё',
      phrases,
      sets: (c) => n(c, { one: `${c} набор`, few: `${c} набора`, many: `${c} наборов`, other: `${c} набора` }),
      points: (c) => n(c, { one: `${c} очко`, few: `${c} очка`, many: `${c} очков`, other: `${c} очка` }),
      level: (level) => level,
      grade: { missed: 'Не помню', hard: 'Трудно', easy: 'Легко' },
      register: { formal: 'Вежливо', informal: 'Неформально', neutral: 'Нейтрально' },
      tag: {
        politeness: 'Вежливость',
        question: 'Вопросы',
        request: 'Просьбы',
        numbers: 'Числа',
        food: 'Еда и напитки',
        directions: 'Дорога',
        social: 'Общение',
      },
      fullPlay: (time) => `${time} при 1×`,
    },
    nav: {
      main: 'Главное меню',
      home: 'Главная',
      explore: 'Обзор',
      library: 'Библиотека',
      settings: (name) => (name ? `${name}: настройки` : 'Настройки'),
      points: (c) => n(c, { one: `${c} очко`, few: `${c} очка`, many: `${c} очков`, other: `${c} очка` }),
      pointsShort: 'очк.',
    },
    status: {
      new: 'Новая',
      listenedNotRated: 'Прослушана, без оценки',
      due: 'Пора повторить',
      learned: (pct) => `Выучена · ${pct}%`,
      learning: (pct, when) => `${pct}% · снова ${when}`,
      set: { new: 'Новый', 'in-progress': 'В процессе', learned: 'Всё выучено' },
    },
    home: {
      firstRun: 'Послушайте фразу и скажите её сами, прежде чем услышите снова.',
      learned: 'Выучено',
      started: 'Начато',
      today: (heard, rated) =>
        `Сегодня: ${n(heard, { one: `прослушана ${heard} фраза`, few: `прослушано ${heard} фразы`, many: `прослушано ${heard} фраз`, other: `прослушано ${heard} фразы` })} · оценок: ${rated}`,
      reviewTitle: 'Повторение',
      reviewBody: (due) => n(due, { one: `Пора повторить ${due} фразу`, few: `Пора повторить ${due} фразы`, many: `Пора повторить ${due} фраз`, other: `Пора повторить ${due} фразы` }),
      reviewCapped: (shown) => `В этом занятии — ${shown} самых давних.`,
      playPhrases: (c) => `Играть: ${phrases(c)}`,
      duration: (time) => `${time} при 1×`,
      startTitle: 'С чего начать',
      continueTitle: 'Продолжить',
      continueBody: (title, learned, total) => `${title} · выучено ${learned} из ${total}`,
      next: (c, when) => `Дальше: ${phrases(c)} ${when}`,
      jumpBackIn: 'Вернуться',
      history: 'История',
      notStarted: 'Ещё не начатые',
      demoTitle: 'Попробуйте цикл',
      demoBody: 'Одна фраза, около 20 секунд: услышать, сказать, услышать.',
      demoButton: 'Сыграть одну фразу',
      courseDoneTitle: 'Все фразы этого курса выучены',
      courseDoneBody: 'Повторения вернутся, когда подойдёт срок. А пока добавьте свои фразы или попробуйте другой курс.',
      addOwn: 'Своя фраза',
      otherCourse: 'Другой курс',
    },
    history: {
      title: 'История',
      empty: 'Пока ничего не прослушано.',
      mixed: 'Смешанная очередь',
      run: (p, points) => `${phrases(p)} · +${points}`,
    },
    explore: {
      search: 'Поиск по фразам, заметкам и темам',
      topics: 'Темы',
      levels: 'Уровни',
      tags: 'Метки',
      allSets: 'Все наборы',
      sets: (c) => n(c, { one: `${c} набор`, few: `${c} набора`, many: `${c} наборов`, other: `${c} набора` }),
      phrases,
      noPhrases: (q) => `Нет фраз по запросу «${q}».`,
      noSets: 'Нет подходящих наборов.',
      removeFilter: (label) => `Убрать фильтр: ${label}`,
      clearFilters: 'Сбросить фильтры',
      quickPlay: (title) => `Играть «${title}»`,
      filtered: 'Отобранные наборы',
    },
    set: {
      phrasesHeading: 'Фразы',
      summary: (total, learned, due) => `${phrases(total)} · выучено ${learned}${due > 0 ? ` · к повторению ${due}` : ''}`,
      sort: { set: 'Порядок набора', az: 'А–Я', due: 'Сначала к повторению', weakest: 'Сначала слабые' },
      sortTitle: 'Сортировка фраз',
      playsIn: (order) => `Порядок: ${order}`,
      playAll: (title) => `Играть «${title}»`,
      pauseAll: (title) => `Пауза: «${title}»`,
      playDueNew: (c) => `Только новые и к повторению (${c})`,
      shufflePlay: 'Вперемешку',
      like: 'Отметить набор',
      unlike: 'Снять отметку с набора',
      duration: (time) => `Целиком ${time} при 1×`,
      playNext: 'Играть следующим',
      addToQueue: 'В очередь',
      share: 'Поделиться ссылкой',
      linkCopied: 'Ссылка скопирована',
      copyUnavailable: 'Копирование здесь недоступно',
      rename: 'Переименовать',
      delete: 'Удалить набор',
      deleted: 'Набор удалён',
      own: 'Ваш набор',
      ownEmpty: 'Добавляйте фразы из их подробностей или из плеера.',
      addedNext: 'Будет следующей',
      addedEnd: 'Добавлено в очередь',
      notFound: 'Этот набор недоступен.',
    },
    phrase: {
      details: (text) => `Подробнее: ${text}`,
      play: (text) => `Играть: ${text}`,
      playNext: 'Играть следующей',
      addToQueue: 'В очередь',
      like: 'Нравится',
      liked: 'Отмечена',
      likeLabel: 'Отметить фразу',
      unlikeLabel: 'Снять отметку',
      addToSet: 'В набор…',
      heard: (c) => `прослушана ${c}×`,
      notes: { mnemonic: 'Подсказка', grammar: 'Грамматика', pronunciation: 'Звуки' },
      notesTitle: 'Заметки',
      notesInEnglish: 'Заметки пока на английском.',
      words: 'Нажмите на слово, чтобы увидеть значение.',
      wordMeaning: (word, gloss) => `${word}: ${gloss}`,
      delete: 'Удалить фразу',
      deleted: 'Фраза удалена',
      removeFromSet: 'Убрать из набора',
      yours: 'Ваша фраза',
    },
    addToSet: {
      title: 'Добавить в набор',
      newSet: 'Новый набор…',
      added: (title) => `Добавлено в «${title}»`,
      already: (title) => `Уже в «${title}»`,
      none: 'У вас пока нет своих наборов.',
    },
    createSet: {
      title: 'Новый набор',
      renameTitle: 'Переименовать набор',
      name: 'Название',
      create: 'Создать',
      created: (title) => `Создан «${title}»`,
    },
    addPhrase: {
      title: 'Своя фраза',
      target: (language) => `На языке: ${language}`,
      native: (language) => `На языке: ${language}`,
      hint: 'Звучит голосом устройства.',
      add: 'Добавить фразу',
      added: 'Фраза добавлена',
    },
    player: {
      dialog: 'Сейчас играет',
      close: 'Закрыть плеер',
      openQueue: 'Открыть очередь',
      summary: 'Итоги занятия',
      position: (i, total) => `${i} из ${total}`,
      queueTitle: (c) => `Очередь · ${phrases(c)}`,
      hidden: (language) => `Текст (${language}) скрыт, пока вы его не услышите`,
      steps: 'Шаги',
      yourTurn: 'Ваша очередь',
      rateStep: 'Оценка',
      instruction: {
        native: (language) => `Слушайте: ${language}`,
        pause: (language) => `Ваша очередь — скажите это (${language})`,
        target: (language) => `Слушайте: ${language}`,
        rate: 'Оцените или подождите',
      },
      paused: 'Пауза',
      repetition: (r, total) => `Повтор ${r} из ${total}`,
      howDidItGo: 'Как получилось сказать?',
      gradeButton: (grade, interval) => `${grade} · ${interval}`,
      rated: (grade, when) => `Оценка «${grade}» — снова ${when}`,
      changeFor: (time) => `Можно изменить или отменить ещё ${time}`,
      counts: 'Оценка засчитается, когда окно закроется.',
      previous: 'Предыдущая фраза',
      next: 'Следующая фраза',
      repeats: {
        auto: 'Повторы: авто (3 для новых, 1 для повторения)',
        one: 'Повторы: 1',
        three: 'Повторы: 3',
      },
      playMode: {
        repeat: 'В конце: сыграть очередь снова',
        continue: 'В конце: продолжить следующими фразами',
      },
      speed: 'Скорость',
      audioError: (language) =>
        `На устройстве нет голоса (${language}), поэтому фраза не звучит. Добавьте его в настройках речи системы и нажмите «Играть».`,
      noVoice: 'Нет голоса для этого языка',
      audioSilent: 'Речь остановилась до того, как фраза прозвучала. Нажмите «Играть», чтобы попробовать снова.',
      silent: 'Речь остановилась — нажмите «Играть»',
      voice: (name) => `Голос: ${name}`,
      hide: 'Нажмите, чтобы показать',
    },
    toast: {
      learned: (points) => `Выучена · +${points}`,
      passComplete: 'Очередь пройдена',
      removed: 'Убрано из очереди',
      cleared: 'Очередь очищена',
      saved: (title) => `Сохранено как «${title}»`,
      storageFull: 'Хранилище Loro на этом устройстве заполнено, новый прогресс не сохраняется.',
      storageUnavailable: 'Этот браузер не даёт Loro сохранять прогресс на устройстве.',
    },
    queue: {
      title: 'Очередь',
      back: 'Назад к плееру',
      left: (c) => `Осталось ${c}`,
      nowPlaying: 'Сейчас играет',
      upNext: (c) => `Дальше · ${c}`,
      nothing: 'После этой фразы ничего нет.',
      hint: 'Смахните вправо, чтобы играть сейчас, влево — чтобы убрать. Тяните за ручку, чтобы переставить.',
      handleHint: 'Стрелки вверх и вниз — переставить, Delete — убрать.',
      moved: (position, total) => `Теперь на месте ${position} из ${total}`,
      playNow: (text) => `Играть сейчас: ${text}`,
      move: (text) => `Переставить: ${text}`,
      swipePlay: 'Играть',
      swipeRemove: 'Убрать',
      previously: 'Уже звучали',
      playNext: (text) => `Играть следующей: ${text}`,
      clear: 'Очистить очередь',
      saveAsSet: 'Сохранить как набор',
      shuffle: 'Перемешать дальнейшие',
      defaultSetName: 'Моя очередь',
    },
    library: {
      learned: 'Выучено',
      learnedNote: (days, recalls) => `Помнится ${days}+ дней, после ${recalls}+ вспоминаний`,
      recall: 'Память сейчас',
      recallNote: (rated) => n(rated, { one: `Среднее по ${rated} оценённой фразе`, other: `Среднее по ${rated} оценённым фразам` }),
      recallNone: 'Сначала оцените фразу',
      started: 'Начато',
      startedNote: 'Прослушаны или оценены хотя бы раз',
      phrasesSegment: 'Фразы',
      setsSegment: 'Наборы',
      filters: {
        liked: 'Отмеченные',
        mine: 'Свои',
        due: 'К повторению',
        learning: 'Изучаются',
        missed: 'Недавно не вспомнились',
        learned: 'Выученные',
        ownSets: 'Мои наборы',
        likedSets: 'Отмеченные наборы',
      },
      empty: {
        liked: 'Нажмите на сердечко у фразы, чтобы она была здесь.',
        mine: 'Добавьте свою фразу — она зазвучит, как любая другая.',
        due: 'Сейчас повторять нечего.',
        learning: 'Здесь фразы, которые вы оценили, но ещё не выучили.',
        missed: 'Здесь фразы с оценкой «Не помню» за последнюю неделю.',
        learned: (days, recalls) =>
          `Фраза выучена, когда память о ней должна держаться ${days} дней и больше, после хотя бы ${recalls} удачных вспоминаний.`,
        ownSets: 'Создайте набор, чтобы сгруппировать фразы по-своему.',
        likedSets: 'Нажмите на сердечко у набора, чтобы он был здесь.',
      },
      playAll: (c) => `Играть всё (${c})`,
      addPhrase: 'Своя фраза',
      newSet: 'Новый набор',
      recallChart: 'Прогноз памяти сейчас',
      recallBucket: (from, to) => `${from}–${to}%`,
      recallBelow: (to) => `меньше ${to}%`,
      recallChartEmpty: 'Оцените фразу, чтобы увидеть это.',
      bucketCount: (label, c) => `${label}: ${phrases(c)}`,
      weeklyChart: 'Выучено за неделю',
      weekOf: (date, c) => `Неделя с ${date}: выучено ${c}`,
      progress: 'Прогресс',
    },
    settings: {
      title: 'Настройки',
      profile: 'Профиль',
      name: 'Имя',
      native: 'Мой язык',
      course: 'Я изучаю',
      courseNote: 'Прогресс хранится для каждой пары языков. Переключитесь обратно — и он вернётся.',
      accessibility: 'Экранный диктор',
      announceEveryStep: 'Объявлять каждый шаг',
      announceHint: 'Выключено: объявляются только «Ваша очередь» и ответ.',
    },
    onboarding: {
      step: (i, total) => `Шаг ${i} из ${total}`,
      welcome: 'Учите язык фразами: услышать, сказать, услышать.',
      name: 'Как к вам обращаться?',
      namePlaceholder: 'Ваше имя',
      native: 'На каком языке вы говорите?',
      course: 'Какой язык вы изучаете?',
      voices: 'Проверяем голоса',
      voicesChecking: 'Ищем голоса на этом устройстве…',
      voiceOk: (language, name) => `${language}: ${name}`,
      voiceMissing: (language) => `${language}: на устройстве нет голоса`,
      voiceHint: 'Добавьте недостающий голос в настройках речи системы. Можно продолжить, но эти фразы не зазвучат, пока голоса нет.',
      test: (language) => `Проверить: ${language}`,
      loop: 'Как это работает',
      loopSteps: (native, target) => [
        `Услышьте фразу: ${native}.`,
        `Скажите её сами (${target}), пока тихо.`,
        `Услышьте её: ${target}.`,
        'Оцените: «Не помню», «Трудно» или «Легко». Оценку можно менять пять минут.',
      ],
      next: 'Дальше',
      start: 'Начать с одной фразы',
      skip: 'Начать без примера',
    },
    summary: {
      title: 'Это занятие',
      phrases: 'Фразы',
      repetitions: 'Повторы',
      ratings: 'Оценки',
      pending: (c) => `ещё можно изменить: ${c}`,
      points: 'Заработано очков',
      passes: 'Прохождений очереди',
      nextDue: 'Следующее повторение',
      nothingDue: 'Пока ничего не запланировано',
    },
    error: {
      title: 'Что-то пошло не так',
      body: 'Обычно помогает перезагрузка, прогресс при этом сохраняется. Если ошибка повторяется, сохранённый прогресс может не подходить к этой версии: скопируйте его, если хотите сохранить, и сбросьте, чтобы начать заново на этом устройстве.',
      reload: 'Перезагрузить',
      part: 'Эту часть экрана не удалось показать. Ваш прогресс в сохранности.',
      copy: 'Скопировать прогресс в JSON',
      copied: 'Скопировано',
      reset: 'Сбросить прогресс',
    },
  };
}
