// The native app's icon fonts: the Material Symbols list in src/shared/ui/icons.ts, as
// two static TrueType subsets (outlined and filled: React Native can't vary the FILL axis), and
// each name's codepoint, so an icon is one character rather than a ligature. Run after the web
// list changes: `npm run icons`. Fonts are bundled; the app never loads them from the network.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const registry = fs.readFileSync(path.join(root, 'src/shared/ui/icons.ts'), 'utf8');
const names = [...registry.matchAll(/^\s+'([a-z0-9_]+)',$/gm)].map((m) => m[1]).sort();
if (names.length === 0) throw new Error('No icon names found in the registry');

const codepointsUrl =
  'https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/MaterialSymbolsOutlined%5BFILL,GRAD,opsz,wght%5D.codepoints';
const codepoints = new Map(
  (await (await fetch(codepointsUrl)).text())
    .trim()
    .split('\n')
    .map((line) => line.split(' ')),
);
const missing = names.filter((n) => !codepoints.has(n));
if (missing.length) throw new Error(`No codepoint for: ${missing.join(', ')}`);

// An agent Google Fonts doesn't know gets TrueType.
async function subset(fill) {
  const css = await fetch(
    `https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,${fill},0&icon_names=${names.join(',')}&display=block`,
    { headers: { 'User-Agent': 'curl/8' } },
  ).then((r) => {
    if (!r.ok) throw new Error(`Google Fonts CSS: ${r.status}`);
    return r.text();
  });
  const url = css.match(/src:\s*url\(([^)]+)\)/)?.[1];
  if (!url) throw new Error(`No font URL in:\n${css}`);
  return Buffer.from(await (await fetch(url)).arrayBuffer());
}

const out = path.join(root, 'assets/fonts');
fs.mkdirSync(out, { recursive: true });
for (const [fill, file] of [[0, 'MaterialSymbols.ttf'], [1, 'MaterialSymbolsFill.ttf']]) {
  const font = await subset(fill);
  if (font.subarray(0, 4).toString('hex') !== '00010000') throw new Error(`${file}: not TrueType`);
  fs.writeFileSync(path.join(out, file), font);
  console.log(`${file}: ${names.length} icons, ${(font.length / 1024).toFixed(1)} KB`);
}
// Every codepoint drawn by the glyph its ligature draws (scripts/fix-cmap.py; needs uv).
const namesFile = path.join(os.tmpdir(), 'loro-icon-codepoints.json');
fs.writeFileSync(namesFile, JSON.stringify(Object.fromEntries(names.map((n) => [n, parseInt(codepoints.get(n), 16)]))));
for (const file of ['MaterialSymbols.ttf', 'MaterialSymbolsFill.ttf']) {
  execFileSync('uv', ['run', '--quiet', '--with', 'fonttools', 'python3', path.join(root, 'scripts/fix-cmap.py'), path.join(out, file), namesFile], { stdio: 'inherit' });
}
const table = names.map((n) => `  ${n}: 0x${codepoints.get(n)},`).join('\n');
fs.writeFileSync(
  path.join(root, 'src/ui/iconCodepoints.ts'),
  `// GENERATED by scripts/icons.mjs from src/shared/ui/icons.ts. Do not edit.\nexport const ICON_CODEPOINTS = {\n${table}\n} as const;\n\nexport type IconName = keyof typeof ICON_CODEPOINTS;\n`,
);
