import { describe, expect, it } from 'vitest'
import { space, typography } from '@loro/design-tokens'
import {
  COVER,
  COVER_BORDER,
  COVER_CROP,
  COVER_GLYPH,
  COVER_RADIUS,
  DISMISS,
  DISMISS_FACE,
  LOVE_FACE,
  EARLIER_MARK,
  EARLIER_REPLAY,
  EARLIER_REPLAY_EDITORIAL,
  earlierReplayHit,
  EARLIER_REPLAY_GLYPH,
  REPLAY_GLYPH,
  EARLIER_MARK_RADIUS,
  EARLIER_MARK_RADIUS_EDITORIAL,
  earlierMarkRadius,
  EARLIER_PHRASE,
  EARLIER_PHRASE_LINE,
  EARLIER_PHRASE_LINE_SIMPLE,
  EARLIER_PHRASE_SIMPLE,
  earlierOpacity,
  earlierPhraseFace,
  earlierPhraseLine,
  FOCUSED_GAP,
  LANDING_GAP,
  LANDING_PAD_TOP_EDITORIAL,
  LANDING_PAD_TOP_SIMPLE,
  landingPadBottom,
  landingPadTop,
  FOCUSED_GUTTER,
  HEADER_HIT_NUDGE,
  HEADER_PAD_BOTTOM,
  HEADER_PAD_TOP,
  KICKER_PAD_X,
  QUEUE_HEADER_COUNT,
  QUEUE_HEADER_COUNT_MAX,
  QUEUE_HEADER_COUNT_MT,
  QUEUE_HEADER_PAD_BOTTOM_EDITORIAL,
  QUEUE_HEADER_PAD_BOTTOM_SIMPLE,
  QUEUE_HEADER_TITLE,
  LANDING_HEADER_GUTTER,
  QUEUE_HEADER_TITLE_LINE,
  QUEUE_HEADER_TITLE_TRACK,
  queueHeaderPadBottom,
  STAGE_TITLE_GAP,
  STAGE_WRAP_Y,
  TITLE_COUNTER_GAP,
  COUNTER_WEIGHT,
  THEME_TRACK,
  COUNTER_NOTE_GAP,
  NOTE_TRANSPORT_GAP,
  EDITORIAL_BORDER,
  EDITORIAL_MEANING,
  EDITORIAL_MEANING_MT,
  EDITORIAL_MEANING_WEIGHT,
  EDITORIAL_PAD,
  EDITORIAL_PLAY,
  SIMPLE_PLAY,
  SIMPLE_FOOTER_PAD_TOP,
  SIMPLE_FOOTER_PAD_X,
  SIMPLE_FOOTER_RESERVE,
  SIMPLE_PAD,
  SIMPLE_RADIUS,
  SIMPLE_COVER_RADIUS,
  SIMPLE_TITLE,
  SIMPLE_TITLE_LINE,
  SIMPLE_RULE_MT,
  SIMPLE_RULE_PT,
  EDITORIAL_RADIUS,
  EDITORIAL_RESP,
  EDITORIAL_RESP_MT,
  EDITORIAL_COPY_PE,
  SIMPLE_COPY_PE,
  EDITORIAL_RATE_GAP,
  EDITORIAL_RULE_MT,
  EDITORIAL_RULE_PT,
  EDITORIAL_TITLE,
  EDITORIAL_TITLE_LINE,
  EDITORIAL_TITLE_LINES,
  EDITORIAL_TRANSPORT,
  EDITORIAL_TRANSPORT_GAP,
  EDITORIAL_TRANSPORT_MT,
  SIMPLE_TRANSPORT_GAP,
  SIMPLE_TRANSPORT_MT,
  PULSE_DOT,
  PULSE_DOT_SIMPLE,
  PULSE_GAP,
  PULSE_GAP_SIMPLE,
  queuePulseDot,
  queuePulseGap,
  QUEUE_CHIP_FACE,
  QUEUE_CHIP_LETTER,
  QUEUE_CHIP_PX,
  QUEUE_CHIP_PX_EDITORIAL,
  QUEUE_CHIP_PY,
  QUEUE_CHIP_PY_EDITORIAL,
  QUEUE_CHIP_RADIUS,
  QUEUE_CHIP_RADIUS_EDITORIAL,
  QUEUE_CHIP_WEIGHT,
  queueChipPadX,
  queueChipPadY,
  queueChipRadius,
  QUEUE_REORDER,
  QUEUE_REORDER_FACE,
  QUEUE_REORDER_GLYPH,
  QUEUE_TRAIL_GAP,
  QUEUE_MEANING,
  QUEUE_MEANING_MT,
  QUEUE_PHRASE,
  QUEUE_PHRASE_LINES,
  QUEUE_TRACK_FACE,
  QUEUE_TRACK_LETTER,
  QUEUE_TRACK_WEIGHT,
  QUEUE_ROW_RADIUS,
  QUEUE_ROW_RADIUS_EDITORIAL,
  QUEUE_STACK_GAP,
  QUEUE_STACK_GAP_EDITORIAL,
  queueStackGap,
  ROW_PAD_X_EDITORIAL,
  ROW_PAD,
  EARLIER_OPACITY,
  EARLIER_OPACITY_EDITORIAL,
  EARLIER_ROW_GAP,
  EARLIER_TOGGLE_FACE,
  EARLIER_TOGGLE_TRACK,
  EARLIER_TOGGLE_WEIGHT,
  SECTION_KICKER,
  SECTION_KICKER_PAD_X,
  PLAY_SIZE,
  FOCUSED_PLAY_FACE,
  PLAY_TRI_H,
  PLAY_TRI_W,
  PAUSE_BAR_H,
  PAUSE_BAR_W,
  PAUSE_GAP,
  COMPACT_PLAY_TRI_H,
  COMPACT_PLAY_TRI_W,
  SIMPLE_PLAY_FACE,
  EDITORIAL_PLAY_FACE,
  EDITORIAL_PLAY_TRI_H,
  EDITORIAL_PLAY_TRI_W,
  COMPACT_PAUSE_H,
  COMPACT_PAUSE_W,
  EDITORIAL_PAUSE_H,
  EDITORIAL_PAUSE_W,
  HERO_RADIUS,
  STAGE,
  STAGE_BORDER,
  STAGE_GLYPH,
  STAGE_TITLE,
  STAGE_TITLE_LINE,
  STAGE_TITLE_TRACK,
  TITLE_PAD_BOTTOM,
  TITLE_PAD_END,
  TITLE_PAD_TOP,
  TITLE_ROW_GAP,
  DRILL_PAD_TOP,
  STAGE_MEANING,
  STAGE_PANEL_MAX,
  STAGE_PANEL_RADIUS,
  STAGE_PILL_ARROW,
  STAGE_PILL_CLOSED,
  STAGE_PILL_FACE,
  STAGE_PILL_GRAMMAR,
  STAGE_PILL_MARK_GAP,
  STAGE_PILL_MNEMONIC,
  STAGE_PILL_OPEN,
  STAGE_PILL_PHONETICS,
  STAGE_PILL_RING,
  STAGE_PILL_WEIGHT,
  STAGE_PILL_WEIGHT_ON,
  STAGE_PILL_X,
  STAGE_PILL_Y,
  RATE_PILL_RING,
  ratePillShadows,
  CADENCE_PAD_X,
  CADENCE_PAD_X_ON,
  CADENCE_PAD_Y,
  CADENCE_ROW_Y,
  CAPSULE_PAD,
  CAPSULE_PAD_BOTTOM,
  CAPSULE_PAD_TOP,
  CADENCE_FACE_WEIGHT,
  CADENCE_FACE_WEIGHT_ON,
  cadenceFaceWeight,
  cadencePadX,
  stagePillShadows,
  DONE_FACE,
  DONE_PX,
  DONE_PX_SIMPLE,
  DONE_PY,
  DONE_PY_SIMPLE,
  DONE_WEIGHT,
  DONE_WEIGHT_SIMPLE,
  donePadX,
  donePadY,
  doneWeight,
  TRANSPORT_MARGIN_TOP,
  TRANSPORT_PAD_X,
  TRANSPORT_PAD_Y,
  TRANSPORT,
  TRANSPORT_GLYPH,
  LOOP_BADGE_END,
  LOOP_BADGE_FACE,
  LOOP_BADGE_LETTER,
  LOOP_BADGE_LINE,
  LOOP_BADGE_PX,
  LOOP_BADGE_TOP,
  LOOP_FACE,
  LOOP_GLYPH,
  EDITORIAL_LOOP_FACE,
  EDITORIAL_LOOP_GAP,
  EDITORIAL_TRANSPORT_FACE,
  SIMPLE_TRANSPORT_FACE,
  compactTransportFace,
  HEARD_FACE,
  OPTIONS_FACE,
  OPTIONS_FACE_HORIZ,
  OPTIONS_GLYPH,
  OPTIONS_GLYPH_HORIZ,
  OPTIONS_EDITORIAL,
  OPTIONS_PILL,
  OPTIONS_SIMPLE,
  OPTIONS_SIMPLE_RADIUS,
  queueCoverRadius,
  queueDressingFromParam,
  queueHeroElevation,
  queueHeroCopyPadEnd,
  queueHeroTransportGap,
  queueHeroTransportMt,
  queueHeroPad,
  queueHeroRadius,
  queueHeroRuleMt,
  queueHeroRulePt,
  queueRowPadX,
  queueRowRadius,
  queueOptionsRadius,
  queueOptionsSize,
  queueTrack,
} from './geometry'

describe('queueTrack', () => {
  it('pads the real queue index, inventing nothing', () => {
    expect(queueTrack(1)).toBe('01')
    expect(queueTrack(10)).toBe('10')
  })
})

describe('queueHeroElevation', () => {
  it('keeps editorial shadow-sm and simple-queue shadow-md', () => {
    expect(queueHeroElevation('editorial')).toBe('emblemSoft')
    expect(queueHeroElevation('simple')).toBe('emblemRaised')
  })
})

describe('queue hero geometry', () => {
  it('keeps editorial 24/14 and simple-queue 16/12', () => {
    expect(queueHeroRadius('editorial')).toBe(24)
    expect(queueHeroPad('editorial')).toBe(14)
    expect(queueHeroCopyPadEnd('editorial')).toBe(2)
    expect(queueHeroTransportGap('editorial')).toBe(16)
    expect(queueHeroTransportMt('editorial')).toBe(8)
    expect(queueHeroRuleMt('editorial')).toBe(14)
    expect(queueHeroRulePt('editorial')).toBe(12)
    expect(landingPadTop('editorial')).toBe(14)
    expect(landingPadBottom('editorial')).toBe(14)
    expect(queueCoverRadius('editorial')).toBe(16)
    expect(queueRowRadius('editorial')).toBe(16)
    expect(queueRowPadX('editorial')).toBe(12)
    expect(queueStackGap('editorial')).toBe(8)
    expect(donePadX('editorial')).toBe(16)
    expect(donePadY('editorial')).toBe(6)
    expect(doneWeight('editorial')).toBe(600)
    expect(queueHeaderPadBottom('editorial')).toBe(10)
    expect(queueHeaderPadBottom('simple')).toBe(8)
    expect(earlierMarkRadius('editorial')).toBe(12)
    expect(earlierReplayHit('editorial')).toBe(32)
    expect(earlierPhraseFace('editorial')).toBe(13)
    expect(earlierPhraseLine('editorial')).toBe(17.875)
    expect(earlierOpacity('editorial')).toBe(1)
    expect(queueHeroRadius('simple')).toBe(16)
    expect(queueHeroPad('simple')).toBe(12)
    expect(queueHeroCopyPadEnd('simple')).toBe(4)
    expect(queueHeroTransportGap('simple')).toBe(12)
    expect(queueHeroTransportMt('simple')).toBe(0)
    expect(queueHeroRuleMt('simple')).toBe(12)
    expect(queueHeroRulePt('simple')).toBe(10)
    expect(landingPadTop('simple')).toBe(12)
    expect(landingPadBottom('simple')).toBe(80)
    expect(landingPadBottom('simple')).toBe(SIMPLE_FOOTER_RESERVE)
    expect(queueCoverRadius('simple')).toBe(12)
    expect(queueRowRadius('simple')).toBe(12)
    expect(queueRowPadX('simple')).toBe(10)
    expect(queueStackGap('simple')).toBe(6)
    expect(donePadX('simple')).toBe(12)
    expect(donePadY('simple')).toBe(4)
    expect(doneWeight('simple')).toBe(700)
    expect(earlierMarkRadius('simple')).toBe(8)
    expect(earlierReplayHit('simple')).toBe(28)
    expect(earlierPhraseFace('simple')).toBe(14)
    expect(earlierPhraseLine('simple')).toBe(20)
    expect(earlierOpacity('simple')).toBe(0.75)
    expect(SIMPLE_PAD).toBe(12)
    expect(SIMPLE_RADIUS).toBe(16)
    expect(SIMPLE_COVER_RADIUS).toBe(12)
    expect(SIMPLE_TITLE).toBe(17.6)
    expect(SIMPLE_TITLE_LINE).toBe(22)
    expect(SIMPLE_RULE_MT).toBe(12)
    expect(SIMPLE_RULE_MT).toBe(space['3'])
    expect(SIMPLE_RULE_PT).toBe(10)
  })
})

describe('queueDressingFromParam', () => {
  it('keeps the landing editorial unless the path asks for simple', () => {
    expect(queueDressingFromParam(undefined)).toBe('editorial')
    expect(queueDressingFromParam('editorial')).toBe('editorial')
    expect(queueDressingFromParam('simple')).toBe('simple')
    expect(queueDressingFromParam(['simple'])).toBe('simple')
  })
})

describe('now-playing geometry', () => {
  it('keeps the named HTML measurements without rounding them onto the space scale', () => {
    expect(STAGE).toBe(280)
    expect(STAGE_BORDER).toBe(1)
    expect(HERO_RADIUS).toBe(24)
    expect(STAGE_GLYPH).toBe(616)
    expect(COVER_CROP).toBe(2.2)
    expect(STAGE_TITLE).toBe(23.2)
    expect(STAGE_TITLE_LINE).toBe(29)
    expect(STAGE_TITLE_TRACK).toBe(-0.58)
    expect(TITLE_PAD_TOP).toBe(4)
    expect(TITLE_PAD_TOP).toBe(space['1'])
    expect(TITLE_PAD_BOTTOM).toBe(4)
    expect(TITLE_PAD_BOTTOM).toBe(space['1'])
    expect(TITLE_PAD_END).toBe(8)
    expect(TITLE_PAD_END).toBe(space['2'])
    expect(TITLE_ROW_GAP).toBe(0)
    expect(DRILL_PAD_TOP).toBe(4)
    expect(DRILL_PAD_TOP).toBe(space['1'])
    expect(PLAY_SIZE).toBe(58)
    expect(FOCUSED_PLAY_FACE).toBe(30)
    expect(PLAY_TRI_W).toBe(30)
    expect(PLAY_TRI_H).toBe(15)
    expect(PAUSE_BAR_W).toBe(4)
    expect(PAUSE_BAR_H).toBe(30)
    expect(PAUSE_GAP).toBe(6)
    expect(EDITORIAL_PLAY_FACE).toBe(20)
    expect(EDITORIAL_PLAY_TRI_W).toBe(20)
    expect(EDITORIAL_PLAY_TRI_H).toBe(10)
    expect(SIMPLE_PLAY_FACE).toBe(16)
    expect(COMPACT_PLAY_TRI_W).toBe(16)
    expect(COMPACT_PLAY_TRI_H).toBe(8)
    expect(EDITORIAL_PAUSE_W).toBe(3)
    expect(EDITORIAL_PAUSE_H).toBe(20)
    expect(COMPACT_PAUSE_W).toBe(3)
    expect(COMPACT_PAUSE_H).toBe(16)
    expect(TRANSPORT).toBe(40)
    expect(TRANSPORT_GLYPH).toBe(30)
    expect(LOOP_BADGE_FACE).toBe(8.5)
    expect(LOOP_BADGE_LINE).toBe(10.625)
    expect(LOOP_BADGE_LINE).toBe(LOOP_BADGE_FACE * 1.25)
    expect(LOOP_BADGE_LETTER).toBe(0)
    expect(LOOP_BADGE_PX).toBe(4)
    expect(LOOP_BADGE_PX).toBe(space['1'])
    expect(LOOP_BADGE_TOP).toBe(4)
    expect(LOOP_BADGE_TOP).toBe(space['1'])
    expect(LOOP_BADGE_END).toBe(2)
    expect(LOOP_BADGE_END).toBe(space['0.5'])
    expect(STAGE_PILL_X).toBe(10)
    expect(STAGE_PILL_Y).toBe(4)
    expect(STAGE_PILL_MNEMONIC).toBe('💡')
    expect(STAGE_PILL_GRAMMAR).toBe('📖')
    expect(STAGE_PILL_PHONETICS).toBe('🗣️')
    expect(STAGE_PILL_ARROW).toBe(13)
    expect(STAGE_PILL_MARK_GAP).toBe(4)
    expect(STAGE_PILL_OPEN).toBe('⌃')
    expect(STAGE_PILL_CLOSED).toBe('⌄')
    expect(STAGE_PILL_RING).toBe(2)
    expect(STAGE_PILL_WEIGHT).toBe('600')
    expect(STAGE_PILL_WEIGHT_ON).toBe('700')
    expect(stagePillShadows(false)).toEqual(['emblemRaised'])
    expect(stagePillShadows(true)).toEqual(['playRaised', 'pillRing'])
    expect(RATE_PILL_RING).toBe(2)
    expect(ratePillShadows(false)).toEqual([])
    expect(ratePillShadows(true)).toEqual(['emblemSoft', 'rateRing'])
    expect(CADENCE_PAD_X).toBe(10)
    expect(CADENCE_PAD_X).toBe(space['2.5'])
    expect(CADENCE_PAD_X_ON).toBe(12)
    expect(CADENCE_PAD_X_ON).toBe(space['3'])
    expect(CADENCE_PAD_Y).toBe(4)
    expect(CADENCE_ROW_Y).toBe(2)
    expect(CADENCE_ROW_Y).toBe(space['0.5'])
    expect(CAPSULE_PAD).toBe(4)
    expect(CAPSULE_PAD_TOP).toBe(4)
    expect(CAPSULE_PAD_TOP).toBe(space['1'])
    expect(CAPSULE_PAD_BOTTOM).toBe(2)
    expect(CAPSULE_PAD_BOTTOM).toBe(space['0.5'])
    expect(cadencePadX(false)).toBe(10)
    expect(cadencePadX(true)).toBe(12)
    expect(CADENCE_FACE_WEIGHT).toBe(500)
    expect(CADENCE_FACE_WEIGHT).toBe(typography.scale.labelSm.weight)
    expect(CADENCE_FACE_WEIGHT_ON).toBe(700)
    expect(typography.family.sans.weights).toContain(CADENCE_FACE_WEIGHT_ON)
    expect(cadenceFaceWeight(false)).toBe(500)
    expect(cadenceFaceWeight(true)).toBe(700)
    expect(STAGE_PANEL_MAX).toBe(230)
    expect(EARLIER_MARK).toBe(32)
    expect(EARLIER_REPLAY).toBe(28)
    expect(EARLIER_REPLAY_EDITORIAL).toBe(32)
    expect(EARLIER_REPLAY_GLYPH).toBe(18)
    expect(REPLAY_GLYPH).toBe('↺')
    expect(QUEUE_REORDER).toBe(24)
    expect(QUEUE_REORDER_GLYPH).toBe('≡')
    expect(QUEUE_REORDER_FACE).toBe(18)
    expect(QUEUE_TRAIL_GAP).toBe(4)
    expect(QUEUE_TRAIL_GAP).toBe(space['1'])
    expect(COVER).toBe(64)
    expect(COVER_GLYPH).toBe(141)
    expect(COVER_RADIUS).toBe(16)
    expect(COVER_BORDER).toBe(1)
    expect(EDITORIAL_PLAY).toBe(36)
    expect(SIMPLE_PLAY).toBe(28)
    expect(SIMPLE_FOOTER_RESERVE).toBe(80)
    expect(SIMPLE_FOOTER_PAD_X).toBe(16)
    expect(SIMPLE_FOOTER_PAD_X).toBe(space['4'])
    expect(SIMPLE_FOOTER_PAD_TOP).toBe(8)
    expect(SIMPLE_FOOTER_PAD_TOP).toBe(space['2'])
    expect(EDITORIAL_TRANSPORT).toBe(32)
    expect(EDITORIAL_PAD).toBe(14)
    expect(EDITORIAL_RADIUS).toBe(24)
    expect(EDITORIAL_BORDER).toBe(2)
    expect(EDITORIAL_TITLE).toBe(18)
    expect(EDITORIAL_TITLE_LINE).toBe(22.5)
    expect(EDITORIAL_TITLE_LINES).toBe(1)
    expect(EDITORIAL_RULE_MT).toBe(14)
    expect(EDITORIAL_RULE_MT).toBe(space['3.5'])
    expect(EDITORIAL_RULE_PT).toBe(12)
    expect(EDITORIAL_RATE_GAP).toBe(0)
    expect(EDITORIAL_TRANSPORT_GAP).toBe(16)
    expect(EDITORIAL_TRANSPORT_GAP).toBe(space['4'])
    expect(EDITORIAL_TRANSPORT_MT).toBe(8)
    expect(EDITORIAL_TRANSPORT_MT).toBe(space['2'])
    expect(SIMPLE_TRANSPORT_GAP).toBe(12)
    expect(SIMPLE_TRANSPORT_GAP).toBe(space['3'])
    expect(SIMPLE_TRANSPORT_MT).toBe(0)
    expect(EDITORIAL_MEANING).toBe(12)
    expect(EDITORIAL_MEANING_WEIGHT).toBe('500')
    expect(EDITORIAL_MEANING_MT).toBe(2)
    expect(EDITORIAL_MEANING_MT).toBe(space['0.5'])
    expect(EDITORIAL_RESP).toBe(10)
    expect(EDITORIAL_RESP_MT).toBe(4)
    expect(EDITORIAL_RESP_MT).toBe(space['1'])
    expect(EDITORIAL_COPY_PE).toBe(2)
    expect(EDITORIAL_COPY_PE).toBe(space['0.5'])
    expect(SIMPLE_COPY_PE).toBe(4)
    expect(SIMPLE_COPY_PE).toBe(space['1'])
    expect(PULSE_DOT).toBe(8)
    expect(PULSE_DOT_SIMPLE).toBe(6)
    expect(PULSE_DOT_SIMPLE).toBe(space['1.5'])
    expect(PULSE_GAP).toBe(6)
    expect(PULSE_GAP).toBe(space['1.5'])
    expect(PULSE_GAP_SIMPLE).toBe(4)
    expect(PULSE_GAP_SIMPLE).toBe(space['1'])
    expect(queuePulseDot('editorial')).toBe(8)
    expect(queuePulseDot('simple')).toBe(6)
    expect(queuePulseGap('editorial')).toBe(6)
    expect(queuePulseGap('simple')).toBe(4)
    expect(SECTION_KICKER).toBe(10)
    expect(SECTION_KICKER_PAD_X).toBe(2)
    expect(SECTION_KICKER_PAD_X).toBe(space['0.5'])
    expect(EARLIER_TOGGLE_FACE).toBe(10)
    expect(EARLIER_TOGGLE_WEIGHT).toBe('600')
    expect(EARLIER_TOGGLE_TRACK).toBe(0.5)
    expect(EARLIER_MARK_RADIUS).toBe(8)
    expect(EARLIER_MARK_RADIUS_EDITORIAL).toBe(12)
    expect(QUEUE_PHRASE).toBe(13.5)
    expect(QUEUE_PHRASE_LINES).toBe(1)
    expect(QUEUE_CHIP_PX).toBe(6)
    expect(QUEUE_CHIP_PY).toBe(0.8)
    expect(QUEUE_CHIP_FACE).toBe(9)
    expect(QUEUE_CHIP_WEIGHT).toBe('700')
    expect(QUEUE_CHIP_LETTER).toBe(0)
    expect(QUEUE_CHIP_RADIUS).toBe(4)
    expect(QUEUE_CHIP_PX_EDITORIAL).toBe(8)
    expect(QUEUE_CHIP_PX_EDITORIAL).toBe(space['2'])
    expect(QUEUE_CHIP_PY_EDITORIAL).toBe(2)
    expect(QUEUE_CHIP_PY_EDITORIAL).toBe(space['0.5'])
    expect(QUEUE_CHIP_RADIUS_EDITORIAL).toBe(999)
    expect(queueChipPadX('simple')).toBe(6)
    expect(queueChipPadY('simple')).toBe(0.8)
    expect(queueChipRadius('simple')).toBe(4)
    expect(queueChipPadX('editorial')).toBe(8)
    expect(queueChipPadY('editorial')).toBe(2)
    expect(queueChipRadius('editorial')).toBe(999)
    expect(QUEUE_TRACK_FACE).toBe(12)
    expect(QUEUE_TRACK_WEIGHT).toBe('700')
    expect(QUEUE_TRACK_LETTER).toBe(0)
    expect(QUEUE_MEANING).toBe(11)
    expect(QUEUE_MEANING_MT).toBe(2)
    expect(QUEUE_MEANING_MT).toBe(space['0.5'])
    expect(QUEUE_STACK_GAP).toBe(6)
    expect(QUEUE_STACK_GAP).toBe(space['1.5'])
    expect(QUEUE_STACK_GAP_EDITORIAL).toBe(8)
    expect(QUEUE_STACK_GAP_EDITORIAL).toBe(space['2'])
    expect(QUEUE_ROW_RADIUS).toBe(12)
    expect(QUEUE_ROW_RADIUS_EDITORIAL).toBe(16)
    expect(ROW_PAD).toBe(10)
    expect(ROW_PAD_X_EDITORIAL).toBe(12)
    expect(EARLIER_ROW_GAP).toBe(12)
    expect(EARLIER_OPACITY).toBe(0.75)
    expect(EARLIER_OPACITY_EDITORIAL).toBe(1)
    expect(earlierOpacity('editorial')).toBe(1)
    expect(earlierOpacity('simple')).toBe(0.75)
    expect(EARLIER_PHRASE).toBe(13)
    expect(EARLIER_PHRASE_LINE).toBe(17.875)
    expect(EARLIER_PHRASE_LINE).toBe(EARLIER_PHRASE * 1.375)
    expect(EARLIER_PHRASE_SIMPLE).toBe(14)
    expect(EARLIER_PHRASE_LINE_SIMPLE).toBe(20)
    expect(earlierPhraseLine('editorial')).toBe(17.875)
    expect(earlierPhraseLine('simple')).toBe(20)
    expect(FOCUSED_GUTTER).toBe(20)
    expect(FOCUSED_GAP).toBe(0)
    expect(LANDING_GAP).toBe(16)
    expect(LANDING_GAP).toBe(space['4'])
    expect(LANDING_PAD_TOP_EDITORIAL).toBe(14)
    expect(LANDING_PAD_TOP_EDITORIAL).toBe(space['3.5'])
    expect(LANDING_PAD_TOP_SIMPLE).toBe(12)
    expect(LANDING_PAD_TOP_SIMPLE).toBe(space['3'])
    expect(HEADER_PAD_TOP).toBe(4)
    expect(HEADER_PAD_TOP).toBe(space['1'])
    expect(HEADER_PAD_BOTTOM).toBe(4)
    expect(HEADER_PAD_BOTTOM).toBe(space['1'])
    expect(KICKER_PAD_X).toBe(8)
    expect(KICKER_PAD_X).toBe(space['2'])
    expect(QUEUE_HEADER_TITLE).toBe(16)
    expect(QUEUE_HEADER_TITLE_LINE).toBe(20)
    expect(QUEUE_HEADER_TITLE_TRACK).toBe(-0.4)
    expect(QUEUE_HEADER_COUNT).toBe(11)
    expect(QUEUE_HEADER_COUNT_MT).toBe(2)
    expect(QUEUE_HEADER_COUNT_MT).toBe(space['0.5'])
    expect(QUEUE_HEADER_COUNT_MAX).toBe(210)
    expect(QUEUE_HEADER_PAD_BOTTOM_EDITORIAL).toBe(10)
    expect(QUEUE_HEADER_PAD_BOTTOM_EDITORIAL).toBe(space['2.5'])
    expect(QUEUE_HEADER_PAD_BOTTOM_SIMPLE).toBe(8)
    expect(QUEUE_HEADER_PAD_BOTTOM_SIMPLE).toBe(space['2'])
    expect(LANDING_HEADER_GUTTER).toBe(16)
    expect(LANDING_HEADER_GUTTER).toBe(space['4'])
    expect(HEADER_HIT_NUDGE).toBe(-8)
    expect(HEADER_HIT_NUDGE).toBe(-space['2'])
    expect(STAGE_WRAP_Y).toBe(2)
    expect(STAGE_WRAP_Y).toBe(space['0.5'])
    expect(STAGE_TITLE_GAP).toBe(0)
    expect(TITLE_COUNTER_GAP).toBe(0)
    expect(COUNTER_WEIGHT).toBe('600')
    expect(THEME_TRACK).toBe(0)
    expect(COUNTER_NOTE_GAP).toBe(0)
    expect(NOTE_TRANSPORT_GAP).toBe(0)
    expect(STAGE_MEANING).toBe(12)
    expect(STAGE_PILL_FACE).toBe(11)
    expect(STAGE_PANEL_RADIUS).toBe(16)
    expect(TRANSPORT_PAD_X).toBe(12)
    expect(TRANSPORT_PAD_Y).toBe(2)
    expect(TRANSPORT_MARGIN_TOP).toBe(0)
    expect(DISMISS).toBe(36)
    expect(DISMISS_FACE).toBe(24)
    expect(LOVE_FACE).toBe(20)
    expect(OPTIONS_EDITORIAL).toBe(28)
    expect(OPTIONS_SIMPLE).toBe(24)
    expect(OPTIONS_PILL).toBe(999)
    expect(OPTIONS_SIMPLE_RADIUS).toBe(4)
    expect(OPTIONS_GLYPH).toBe('⋮')
    expect(OPTIONS_FACE).toBe(20)
    expect(OPTIONS_GLYPH_HORIZ).toBe('⋯')
    expect(OPTIONS_FACE_HORIZ).toBe(16)
    expect(LOOP_GLYPH).toBe('↻')
    expect(LOOP_FACE).toBe(22)
    expect(EDITORIAL_LOOP_FACE).toBe(12)
    expect(EDITORIAL_LOOP_GAP).toBe(4)
    expect(EDITORIAL_LOOP_GAP).toBe(space['1'])
    expect(EDITORIAL_TRANSPORT_FACE).toBe(20)
    expect(SIMPLE_TRANSPORT_FACE).toBe(18)
    expect(compactTransportFace('editorial')).toBe(20)
    expect(compactTransportFace('simple')).toBe(18)
    expect(HEARD_FACE).toBe(16)
    expect(queueOptionsSize('editorial')).toBe(28)
    expect(queueOptionsSize('simple')).toBe(24)
    expect(queueOptionsRadius('editorial')).toBe(999)
    expect(queueOptionsRadius('simple')).toBe(4)
    expect(DONE_PX).toBe(16)
    expect(DONE_PY).toBe(6)
    expect(DONE_FACE).toBe(12)
    expect(DONE_WEIGHT).toBe(600)
    expect(DONE_PX_SIMPLE).toBe(12)
    expect(DONE_PY_SIMPLE).toBe(4)
    expect(DONE_WEIGHT_SIMPLE).toBe(700)
  })
})
