// Every Material Symbols icon the app draws, and nothing else. The local icon
// font (public/fonts/material-symbols.woff2) is subset to exactly this list by
// `npm run icons`; `npm test` fails if the font and this list drift apart, and
// the content test fails if a set or topic names an icon that isn't here.
export const ICON_NAMES = [
  'add',
  'arrow_back',
  'arrow_downward',
  'arrow_upward',
  'check',
  'check_circle',
  'chevron_right',
  'clear_all',
  'close',
  'coffee',
  'content_copy',
  'delete',
  'directions_bus',
  'drag_handle',
  'edit',
  'edit_note',
  'error',
  'favorite',
  'format_list_numbered',
  'forum',
  'headphones',
  'hearing',
  'history',
  'home',
  'hourglass_empty',
  'insights',
  'keyboard_arrow_down',
  'library_music',
  'lightbulb',
  'local_taxi',
  'menu_book',
  'mic',
  'more_horiz',
  'more_vert',
  'pause',
  'person',
  'play_arrow',
  'play_circle',
  'playlist_add',
  'playlist_play',
  'playlist_remove',
  'queue_music',
  'queue_play_next',
  'record_voice_over',
  'repeat',
  'replay',
  'restart_alt',
  'restaurant',
  'schedule',
  'search',
  'share',
  'shopping_basket',
  'shuffle',
  'skip_next',
  'skip_previous',
  'sort',
  'sort_by_alpha',
  'stars',
  'storefront',
  'subway',
  'tapas',
  'task_alt',
  'train',
  'trending_down',
  'verified',
  'volume_off',
  'volume_up',
] as const;

export type IconName = (typeof ICON_NAMES)[number];
