import { describe, expect, it } from 'vitest'
import { space } from '@loro/design-tokens'
import {
  GREETING_CYCLE_GAP,
  GREETING_CYCLE_MB,
  GREETING_CYCLE_TRACK,
  PULSE_DOT,
  GREETING_DUE,
  GREETING_DUE_LINE,
  GREETING_DUE_MT,
  GREETING_DUE_WEIGHT,
  GREETING_GAP,
  GREETING_LINE,
  GREETING_TITLE,
  GREETING_TRACK,
  FIRST_FOLD_TILES,
  HEADER_CLUSTER_GAP,
  HEADER_H,
  INSIGHT_GAP,
  INSIGHT_ICON,
  INSIGHT_ICON_RADIUS,
  INSIGHT_BODY,
  INSIGHT_BODY_LINE,
  INSIGHT_PAD,
  INSIGHT_PB,
  INSIGHT_RADIUS,
  INSIGHT_COUNT,
  INSIGHT_COUNT_LINE,
  INSIGHT_TITLE,
  INSIGHT_TITLE_LINE,
  JUMP_BROWSE_TRACK,
  LABEL_BOLD_WEIGHT,
  JUMP_COPY_GAP,
  JUMP_COPY_X,
  JUMP_COPY_Y,
  JUMP_TITLE,
  JUMP_TITLE_LINE,
  JUMP_TITLE_TRACK,
  JUMP_GAP,
  JUMP_HEADING,
  JUMP_HEADING_LINE,
  JUMP_RADIUS,
  PAGE_GUTTER,
  PROFILE_ML,
  SECTION_GAP,
  PLAY_TRI_H,
  PLAY_TRI_W,
  START_TRI_FACE,
  START_LABEL,
  START_LABEL_LINE,
  START_LABEL_TRACK,
  START_PILL_GAP,
  START_PILL_PX,
  START_PILL_PY,
  STAT_BAR_GAP,
  STAT_CELL_GAP,
  STAT_NEXT_PAD_END,
  STAT_ICON,
  STAT_MARK_FACE,
  STAT_PAD,
  STAT_RADIUS,
  STAT_VALUE,
  STAT_VALUE_LINE,
  STAT_VALUE_TRACK,
  STREAK_FLAME,
  STREAK_GAP,
  STREAK_PX,
  STREAK_PY,
  TARGET_PX,
  TILE_THUMB,
  WAVE_BLEED,
  WAVE_CARD_GAP,
  WAVE_CARD_MAX,
  WAVE_CARD_PAD,
  WAVE_CARD_RADIUS,
  WAVE_HEADING,
  WAVE_HEADING_LINE,
  WAVE_HEAD_GAP,
  WAVE_MANNER,
  WAVE_MANNER_LINE,
  WAVE_MANNER_LINES,
  WAVE_CARD_VW,
  WAVE_LATER_OPACITY,
  WAVE_PASSED_OPACITY,
  WAVE_SNAP_GAP,
  WAVE_TRACK_PB,
  WAVE_FOOTER_PT,
  WAVE_TITLE,
  WAVE_TITLE_GAP,
  WAVE_TITLE_LINE,
  WAVE_BADGE_TRACK,
  WAVE_MIXES_TRACK,
  STAT_LABEL_TRACK,
  WAVE_TITLE_MT,
  WAVEFORM_GAP,
  WAVEFORM_H,
  WAVEFORM_PAD,
  WORDMARK_TRACK,
} from './geometry'

describe('today wave-card geometry', () => {
  it('keeps the HTML headline-sm time and 84vw card without rounding onto the space scale', () => {
    expect(WAVE_TITLE).toBe(20)
    expect(WAVE_TITLE_LINE).toBe(28)
    expect(WAVE_HEADING).toBe(20)
    expect(WAVE_HEADING_LINE).toBe(28)
    expect(WAVE_HEADING).toBe(WAVE_TITLE)
    expect(JUMP_HEADING).toBe(20)
    expect(JUMP_HEADING_LINE).toBe(28)
    expect(JUMP_HEADING).toBe(WAVE_HEADING)
    expect(WAVE_TITLE_GAP).toBe(0)
    expect(WAVE_MANNER).toBe(12)
    expect(WAVE_MANNER_LINE).toBe(18)
    expect(WAVE_MANNER_LINES).toBe(2)
    expect(WAVEFORM_GAP).toBe(4)
    expect(WAVEFORM_GAP).toBe(space['1'])
    expect(WAVE_TITLE_MT).toBe(4)
    expect(WAVE_TITLE_MT).toBe(space['1'])
    expect(GREETING_TITLE).toBe(30)
    expect(GREETING_LINE).toBe(36)
    expect(WAVE_CARD_VW).toBe(0.84)
    expect(WAVE_CARD_MAX).toBe(384)
    expect(WAVE_CARD_RADIUS).toBe(16)
    expect(WAVE_CARD_PAD).toBe(16)
    expect(WAVE_CARD_GAP).toBe(0)
    expect(WAVE_HEAD_GAP).toBe(4)
    expect(WAVE_HEAD_GAP).toBe(space['1'])
    expect(WAVE_SNAP_GAP).toBe(16)
    expect(WAVE_BLEED).toBe(16)
    expect(WAVE_TRACK_PB).toBe(8)
    expect(WAVE_TRACK_PB).toBe(space['2'])
    expect(WAVE_FOOTER_PT).toBe(4)
    expect(WAVE_FOOTER_PT).toBe(space['1'])
    expect(WAVE_LATER_OPACITY).toBe(0.6)
    expect(WAVE_PASSED_OPACITY).toBe(0.8)
    expect(WAVEFORM_H).toBe(48)
    expect(WAVEFORM_PAD).toBe(10)
    expect(WAVEFORM_PAD).toBe(space['2.5'])
    expect(TILE_THUMB).toBe(56)
    expect(FIRST_FOLD_TILES).toBe(4)
    expect(STAT_ICON).toBe(32)
    expect(STAT_MARK_FACE).toBe(18)
    expect(STAT_PAD).toBe(8)
    expect(STAT_RADIUS).toBe(12)
    expect(STAT_CELL_GAP).toBe(4)
    expect(STAT_CELL_GAP).toBe(space['1'])
    expect(STAT_BAR_GAP).toBe(0)
    expect(STAT_NEXT_PAD_END).toBe(4)
    expect(STAT_NEXT_PAD_END).toBe(space['1'])
    expect(GREETING_GAP).toBe(8)
    expect(PULSE_DOT).toBe(8)
    expect(GREETING_CYCLE_GAP).toBe(6)
    expect(GREETING_CYCLE_GAP).toBe(space['1.5'])
    expect(LABEL_BOLD_WEIGHT).toBe('700')
    expect(GREETING_CYCLE_TRACK).toBe(0.55)
    expect(WAVE_BADGE_TRACK).toBe(0.55)
    expect(WAVE_BADGE_TRACK).toBe(GREETING_CYCLE_TRACK)
    expect(WAVE_MIXES_TRACK).toBe(0.55)
    expect(WAVE_MIXES_TRACK).toBe(GREETING_CYCLE_TRACK)
    expect(STAT_LABEL_TRACK).toBe(0.55)
    expect(STAT_LABEL_TRACK).toBe(GREETING_CYCLE_TRACK)
    expect(STAT_VALUE).toBe(12)
    expect(STAT_VALUE_LINE).toBe(16)
    expect(STAT_VALUE_TRACK).toBe(0.3)
    expect(GREETING_CYCLE_MB).toBe(4)
    expect(GREETING_CYCLE_MB).toBe(space['1'])
    expect(GREETING_DUE_MT).toBe(2)
    expect(GREETING_DUE_MT).toBe(space['0.5'])
    expect(GREETING_DUE).toBe(14)
    expect(GREETING_DUE_LINE).toBe(22)
    expect(GREETING_DUE_WEIGHT).toBe('600')
    expect(STREAK_PX).toBe(10)
    expect(STREAK_PY).toBe(4)
    expect(STREAK_PY).toBe(space['1'])
    expect(STREAK_GAP).toBe(4)
    expect(STREAK_GAP).toBe(space['1'])
    expect(TARGET_PX).toBe(10)
    expect(TARGET_PX).toBe(STREAK_PX)
    expect(STREAK_FLAME).toBe(14)
    expect(JUMP_GAP).toBe(8)
    expect(SECTION_GAP).toBe(32)
    expect(HEADER_H).toBe(64)
    expect(PAGE_GUTTER).toBe(16)
    expect(HEADER_CLUSTER_GAP).toBe(4)
    expect(PROFILE_ML).toBe(2)
    expect(PROFILE_ML).toBe(space['0.5'])
    expect(WORDMARK_TRACK).toBe(-0.5)
    expect(JUMP_RADIUS).toBe(12)
    expect(JUMP_COPY_X).toBe(10)
    expect(JUMP_COPY_Y).toBe(6)
    expect(JUMP_COPY_GAP).toBe(0)
    expect(JUMP_TITLE).toBe(12)
    expect(JUMP_TITLE_LINE).toBe(16)
    expect(JUMP_TITLE_TRACK).toBe(0.3)
    expect(JUMP_BROWSE_TRACK).toBe(0.55)
    expect(JUMP_BROWSE_TRACK).toBe(GREETING_CYCLE_TRACK)
    expect(GREETING_TRACK).toBe(-0.45)
    expect(INSIGHT_ICON).toBe(48)
    expect(INSIGHT_ICON_RADIUS).toBe(12)
    expect(INSIGHT_PAD).toBe(16)
    expect(INSIGHT_PB).toBe(24)
    expect(INSIGHT_PB).toBe(space['6'])
    expect(INSIGHT_RADIUS).toBe(16)
    expect(INSIGHT_GAP).toBe(16)
    expect(INSIGHT_TITLE).toBe(14)
    expect(INSIGHT_TITLE_LINE).toBe(22)
    expect(INSIGHT_BODY).toBe(12)
    expect(INSIGHT_BODY_LINE).toBe(18)
    expect(INSIGHT_COUNT).toBe(24)
    expect(INSIGHT_COUNT_LINE).toBe(32)
    expect(START_PILL_PX).toBe(16)
    expect(START_PILL_PY).toBe(8)
    expect(START_PILL_GAP).toBe(6)
    expect(START_PILL_GAP).toBe(space['1.5'])
    expect(START_TRI_FACE).toBe(18)
    expect(PLAY_TRI_W).toBe(18)
    expect(PLAY_TRI_H).toBe(9)
    expect(START_LABEL).toBe(12)
    expect(START_LABEL_LINE).toBe(16)
    expect(START_LABEL_TRACK).toBe(0.3)
  })
})
