import { expect, onboard, test } from './fixtures'
import { mockAccountService, openAccount, requestCode, finishSignIn } from './accountFlow'
test('optional email sign-in syncs and sign-out keeps durable local practice', async ({ page }) => {
  await mockAccountService(page)
  await onboard(page)
  await openAccount(page)
  await requestCode(page)
  await finishSignIn(page)
  await expect(page.getByText('Your progress is up to date.')).toBeVisible()
  expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toContain('e2e-refresh')
  expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toContain('e2e-access')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Email address' })).toBeVisible()
  await page.goto('/')
  await expect(page.getByText('Your day', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /Stream, 10 phrases/ })).toBeVisible()
})
test('web reload retains progress while requiring a fresh sign-in', async ({ page }) => {
  await mockAccountService(page)
  await onboard(page)
  await openAccount(page)
  await requestCode(page)
  await finishSignIn(page)
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'Email address' })).toBeVisible()
  await page.goto('/')
  await expect(page.getByText('Your day', { exact: true })).toBeVisible()
})
